/* GENERATED by scripts/src/gen-consolidations.ts — do not edit.
   Consolidation specs are authored as JSON under lib/backend-catalogue/assets/consolidations/;
   run `pnpm --filter @workspace/scripts run gen-consolidations` to regenerate. */
import type { ConsolidationSpec } from "./consolidation";

export const CONSOLIDATIONS_DATA: ConsolidationSpec[] = [
  {
    "id": "benefits",
    "measures": [
      "planned",
      "actual",
      "expected"
    ],
    "derived": [
      {
        "key": "realisation",
        "op": "ratioPct",
        "a": "actual",
        "b": "planned"
      }
    ],
    "sort": {
      "key": "realisation",
      "dir": "asc"
    }
  },
  {
    "id": "income",
    "measures": [
      "projected",
      "invoiced"
    ],
    "derived": [
      {
        "key": "unbilled",
        "op": "diffFloor0",
        "a": "projected",
        "b": "invoiced"
      },
      {
        "key": "billedPct",
        "op": "ratioPct",
        "a": "invoiced",
        "b": "projected"
      }
    ],
    "sort": {
      "key": "unbilled",
      "dir": "desc"
    }
  }
];
