/* GENERATED by scripts/src/gen-consolidations.ts — do not edit.
   Consolidation specs are authored as JSON under lib/backend-catalogue/assets/consolidations/;
   run `pnpm --filter @workspace/scripts run gen-consolidations` to regenerate. */
import type { ConsolidationSpec } from "./consolidation";

export const CONSOLIDATIONS_DATA: ConsolidationSpec[] = [
  {
    "id": "benefits",
    "measures": [
      {
        "key": "planned",
        "agg": "sum",
        "field": "plannedBenefitValue"
      },
      {
        "key": "actual",
        "agg": "sum",
        "field": "actualBenefitValue"
      },
      {
        "key": "expected",
        "agg": "weightedSum",
        "field": "plannedBenefitValue",
        "weightField": "benefitConfidence",
        "weightScale": 0.01,
        "weightDefault": 100,
        "weightMax": 100
      }
    ],
    "derived": [
      {
        "key": "realisation",
        "op": "ratioPct",
        "a": "actual",
        "b": "planned"
      }
    ],
    "sort": {
      "key": "realisation",
      "dir": "asc"
    }
  },
  {
    "id": "costs",
    "measures": [
      {
        "key": "budget",
        "agg": "sum",
        "field": "budget"
      },
      {
        "key": "actual",
        "agg": "sum",
        "field": "actualCost"
      }
    ],
    "derived": [
      {
        "key": "variance",
        "op": "diff",
        "a": "budget",
        "b": "actual"
      },
      {
        "key": "pctConsumed",
        "op": "ratioPct",
        "a": "actual",
        "b": "budget"
      }
    ],
    "sort": {
      "key": "variance",
      "dir": "asc"
    }
  },
  {
    "id": "income",
    "measures": [
      {
        "key": "projected",
        "agg": "sum",
        "field": "revenue"
      },
      {
        "key": "invoiced",
        "agg": "sum",
        "field": "invoicedAmount"
      }
    ],
    "derived": [
      {
        "key": "unbilled",
        "op": "diffFloor0",
        "a": "projected",
        "b": "invoiced"
      },
      {
        "key": "billedPct",
        "op": "ratioPct",
        "a": "invoiced",
        "b": "projected"
      }
    ],
    "sort": {
      "key": "unbilled",
      "dir": "desc"
    }
  }
];
