/* GENERATED by scripts/src/gen-dashboard-presets.ts — do not edit.
   Presets are authored as JSON under lib/backend-catalogue/assets/dashboard-presets/;
   run `pnpm --filter @workspace/scripts run gen-dashboard-presets` to regenerate. */
import type { DashboardPreset } from "./dashboard-preset-catalogue";

export const DASHBOARD_PRESETS_DATA: DashboardPreset[] = [
  {
    "id": "head-of-projects-today",
    "role": "head-of-projects",
    "name": "What needs me today — Head of Projects",
    "summary": "Portfolio-wide triage: RAG health, where projects are stuck, and the trend that decides where to spend your attention.",
    "order": 10,
    "widgets": [
      {
        "type": "portfolioHealth",
        "span": 3
      },
      {
        "type": "statusBreakdown",
        "span": 1
      },
      {
        "type": "portfolioTrends",
        "span": 2
      },
      {
        "type": "recentActivity",
        "span": 1
      }
    ]
  },
  {
    "id": "programme-manager-today",
    "role": "programme-manager",
    "name": "What needs me today — Programme Manager",
    "summary": "The cross-project picture: which projects threaten a shared milestone, programme-level counts, and the movement since yesterday.",
    "order": 20,
    "widgets": [
      {
        "type": "portfolioHealth",
        "span": 3
      },
      {
        "type": "programmeCount",
        "span": 1
      },
      {
        "type": "statusBreakdown",
        "span": 1
      },
      {
        "type": "portfolioTrends",
        "span": 2
      },
      {
        "type": "recentActivity",
        "span": 1
      }
    ]
  },
  {
    "id": "project-manager-today",
    "role": "project-manager",
    "name": "What needs me today — Project Manager",
    "summary": "Your delivery lens: where work is stuck, how many projects you carry, the trend, and the latest activity that needs a nudge.",
    "order": 30,
    "widgets": [
      {
        "type": "statusBreakdown",
        "span": 2
      },
      {
        "type": "projectCount",
        "span": 1
      },
      {
        "type": "portfolioTrends",
        "span": 2
      },
      {
        "type": "recentActivity",
        "span": 1
      }
    ]
  }
];
