/* GENERATED by scripts/src/gen-deployment-types.ts — do not edit.
   Deployment types are authored as JSON under lib/backend-catalogue/assets/deployment-types/;
   run `pnpm --filter @workspace/scripts run gen-deployment-types` to regenerate. */
import type { DeploymentType } from "./deployment-type-catalogue";

export const DEPLOYMENT_TYPES_DATA: DeploymentType[] = [
  {
    "id": "cloud-saas",
    "label": "Managed cloud",
    "description": "Hosted for you, SSO on, scheduled backups. A team that wants to log in and go.",
    "order": 30,
    "questions": [
      {
        "id": "methodology",
        "label": "How does the team work?",
        "options": [
          {
            "value": "scrum",
            "label": "Scrum (sprints)"
          },
          {
            "value": "kanban",
            "label": "Kanban (flow)"
          }
        ],
        "default": "scrum"
      }
    ],
    "setup": {
      "storage": "omnistore",
      "auth": "idp",
      "broker": "builtin:omnistore",
      "residency": "off",
      "methodology": "scrum",
      "audit": "standard",
      "backups": "scheduled"
    },
    "refinements": [
      {
        "when": {
          "methodology": "kanban"
        },
        "set": {
          "methodology": "kanban"
        }
      }
    ]
  },
  {
    "id": "enterprise-onprem",
    "label": "Enterprise on-prem",
    "description": "Your data centre, your SSO, a durable SQL system of record and strict audit. Portfolio-scale governance.",
    "order": 40,
    "questions": [
      {
        "id": "external-sor",
        "label": "Federate to existing enterprise systems (Jira, SAP, ServiceNow)?",
        "options": [
          {
            "value": "no",
            "label": "No — OmniProject is the SoR"
          },
          {
            "value": "yes",
            "label": "Yes — broker + federate"
          }
        ],
        "default": "yes"
      },
      {
        "id": "residency",
        "label": "Pin data residency to a region?",
        "options": [
          {
            "value": "off",
            "label": "No restriction"
          },
          {
            "value": "on",
            "label": "Yes — enforce residency"
          }
        ],
        "default": "on"
      }
    ],
    "setup": {
      "storage": "sql-sidecar",
      "auth": "idp",
      "broker": "builtin:postgres",
      "residency": "on",
      "methodology": "safe",
      "audit": "strict",
      "backups": "scheduled"
    },
    "refinements": [
      {
        "when": {
          "external-sor": "yes"
        },
        "set": {
          "broker": "n8n"
        }
      },
      {
        "when": {
          "residency": "off"
        },
        "set": {
          "residency": "off"
        }
      }
    ]
  },
  {
    "id": "regulated-selfhost",
    "label": "Regulated self-host",
    "description": "Self-hosted under a compliance regime: encrypted at rest, data residency enforced, strict audit, SSO.",
    "order": 50,
    "questions": [
      {
        "id": "residency",
        "label": "Which residency posture?",
        "options": [
          {
            "value": "on",
            "label": "Enforce a single region"
          },
          {
            "value": "multi",
            "label": "Multi-region, each pinned"
          }
        ],
        "default": "on"
      },
      {
        "id": "dr",
        "label": "Disaster-recovery backups?",
        "options": [
          {
            "value": "scheduled",
            "label": "Scheduled"
          },
          {
            "value": "continuous",
            "label": "Continuous replication"
          }
        ],
        "default": "scheduled"
      }
    ],
    "setup": {
      "storage": "omnistore",
      "auth": "idp",
      "broker": "builtin:omnistore",
      "residency": "on",
      "methodology": "prince2",
      "audit": "strict",
      "backups": "scheduled"
    },
    "refinements": [
      {
        "when": {
          "dr": "continuous"
        },
        "set": {
          "backups": "continuous"
        }
      }
    ],
    "notes": "OmniStore's hash-chained, encrypted, tamper-evident log fits a regulated self-host; residency + strict audit are on by default."
  },
  {
    "id": "small-team",
    "label": "Small team",
    "description": "A handful of people sharing a board. OmniStore by default, or point at a system of record you already run.",
    "order": 20,
    "questions": [
      {
        "id": "idp",
        "label": "Sign in with an identity provider?",
        "options": [
          {
            "value": "no",
            "label": "No — internal login"
          },
          {
            "value": "yes",
            "label": "Yes — SSO / IdP"
          }
        ],
        "default": "no"
      },
      {
        "id": "external-sor",
        "label": "Do you already run a system of record (Jira, Todoist, …)?",
        "help": "If yes, OmniProject brokers to it; if no, OmniStore is the home.",
        "options": [
          {
            "value": "no",
            "label": "No — use OmniStore"
          },
          {
            "value": "yes",
            "label": "Yes — broker to it"
          }
        ],
        "default": "no"
      }
    ],
    "setup": {
      "storage": "omnistore",
      "auth": "internal",
      "broker": "builtin:omnistore",
      "residency": "off",
      "methodology": "kanban",
      "audit": "standard",
      "backups": "scheduled"
    },
    "refinements": [
      {
        "when": {
          "idp": "yes"
        },
        "set": {
          "auth": "both"
        }
      },
      {
        "when": {
          "external-sor": "yes"
        },
        "set": {
          "storage": "external",
          "broker": "n8n"
        }
      }
    ]
  },
  {
    "id": "solo-selfhost",
    "label": "Solo self-hoster",
    "description": "One person, your own box, zero external dependencies. OmniStore holds everything; you log in with a username and password.",
    "order": 10,
    "questions": [
      {
        "id": "idp",
        "label": "Sign in with an identity provider (Google, Okta…)?",
        "help": "The default is a built-in username + password. You can add an IdP later.",
        "options": [
          {
            "value": "no",
            "label": "No — internal login"
          },
          {
            "value": "yes",
            "label": "Yes — add an IdP"
          }
        ],
        "default": "no"
      },
      {
        "id": "backups",
        "label": "How should backups run?",
        "options": [
          {
            "value": "manual",
            "label": "Manual export when I want"
          },
          {
            "value": "scheduled",
            "label": "Scheduled automatic backups"
          }
        ],
        "default": "manual"
      }
    ],
    "setup": {
      "storage": "omnistore",
      "auth": "internal",
      "broker": "builtin:omnistore",
      "residency": "off",
      "methodology": "gtd",
      "audit": "standard",
      "backups": "manual"
    },
    "refinements": [
      {
        "when": {
          "idp": "yes"
        },
        "set": {
          "auth": "both"
        }
      },
      {
        "when": {
          "backups": "scheduled"
        },
        "set": {
          "backups": "scheduled"
        }
      }
    ],
    "notes": "The self-hoster on-ramp: OmniStore as the sole system of record (100% of the data), internal auth by default, GTD as the personal methodology."
  }
];
