/* GENERATED by scripts/src/gen-deployment-profiles.ts — do not edit.
   Deployment profiles are authored as JSON under lib/backend-catalogue/assets/deployment-profiles/;
   run `pnpm --filter @workspace/scripts run gen-deployment-profiles` to regenerate. */
import type { ProfilePosture } from "./deployment-profile-catalogue";

export const DEPLOYMENT_PROFILES_DATA: ProfilePosture[] = [
  {
    "id": "business",
    "label": "Business / SME",
    "order": 20,
    "default": true,
    "audience": "A company deployment reachable beyond a LAN.",
    "tls": "required",
    "demoAuthSeverity": "critical",
    "summary": "SSO + HTTPS expected; advanced hardening optional.",
    "relaxes": [],
    "presetEnv": [
      {
        "key": "OIDC_ISSUER_URL",
        "why": "SSO (Google Workspace / Entra / Authentik…)"
      },
      {
        "key": "PUBLIC_TLS",
        "value": "1",
        "why": "serve over HTTPS"
      },
      {
        "key": "SESSION_SECRET",
        "why": "signs cookies (required in prod)"
      },
      {
        "key": "BROKER_PSK",
        "why": "authenticate the gateway↔broker hop"
      }
    ],
    "recommend": [
      "Configure OIDC SSO",
      "Serve over HTTPS",
      "Set SESSION_SECRET + BROKER_PSK"
    ]
  },
  {
    "id": "demo",
    "label": "Demo / evaluation",
    "order": 50,
    "audience": "Throwaway evaluation. Nothing to protect.",
    "tls": "lan-ok",
    "demoAuthSeverity": "info",
    "summary": "No auth, sample data, nothing at rest.",
    "relaxes": [
      "Everything — no auth, no TLS, sample data"
    ],
    "presetEnv": [],
    "recommend": [
      "Switch to a real profile before storing anything that matters"
    ]
  },
  {
    "id": "enterprise",
    "label": "Enterprise",
    "order": 10,
    "audience": "Large or regulated organisation, shared deployment, compliance obligations.",
    "tls": "required",
    "demoAuthSeverity": "critical",
    "summary": "SSO + the full hardening surface expected.",
    "relaxes": [],
    "presetEnv": [
      {
        "key": "OIDC_ISSUER_URL",
        "why": "SSO via your IdP"
      },
      {
        "key": "SCIM_TOKEN",
        "why": "user provisioning/deprovisioning"
      },
      {
        "key": "KMS_PROVIDER",
        "value": "aws|azure",
        "why": "BYOK envelope for keys"
      },
      {
        "key": "IP_ALLOWLIST",
        "why": "restrict to your networks"
      },
      {
        "key": "DUAL_CONTROL_ACTIONS",
        "value": "key.revoke,maintenance.engage,role_map.update",
        "why": "four-eyes on sensitive ops (incl. admin-authority mapping)"
      },
      {
        "key": "AUDIT_HTTP_URL",
        "why": "ship the tamper-evident audit to your SIEM"
      }
    ],
    "recommend": [
      "OIDC SSO + SCIM",
      "KMS/BYOK",
      "IP allowlist",
      "Maker-checker",
      "Ship audit to a SIEM",
      "Serve over HTTPS"
    ]
  },
  {
    "id": "nonprofit",
    "label": "Non-profit / charity",
    "order": 30,
    "audience": "Small team, often without a corporate IdP, cost-sensitive.",
    "tls": "lan-ok",
    "demoAuthSeverity": "warn",
    "summary": "The bundled IdP gives real accounts; HTTP on a trusted network is acceptable by choice.",
    "relaxes": [
      "Plain HTTP on a trusted LAN",
      "No corporate IdP required (use the bundled one)"
    ],
    "presetEnv": [
      {
        "key": "SESSION_SECRET",
        "why": "signs cookies"
      },
      {
        "key": "OIDC_ISSUER_URL",
        "value": "http://authentik/…",
        "why": "the BUNDLED IdP — real staff accounts + roles, no cloud"
      }
    ],
    "recommend": [
      "Use the bundled IdP (Authentik) for staff accounts + roles",
      "Enable HTTPS if reachable beyond the LAN",
      "Set a strong SESSION_SECRET"
    ]
  },
  {
    "id": "self-hosted",
    "label": "Self-hosted / homelab",
    "order": 40,
    "audience": "Individual or small self-hoster on a private network.",
    "tls": "lan-ok",
    "demoAuthSeverity": "warn",
    "summary": "Minimal setup; HTTP-on-LAN and single-admin demo auth are accepted choices.",
    "relaxes": [
      "Plain HTTP on a LAN",
      "Single-admin demo auth (no SSO needed)"
    ],
    "presetEnv": [
      {
        "key": "SESSION_SECRET",
        "why": "signs cookies"
      }
    ],
    "recommend": [
      "Set a strong SESSION_SECRET",
      "Use the bundled IdP if more than one person needs access",
      "Put a TLS reverse proxy in front for remote access"
    ]
  }
];
