/* GENERATED by scripts/src/gen-fields.ts — do not edit.
   The superset = base fields (lib/backend-catalogue/assets/fields.json) UNION every backend's
   contributed fields[]; run `pnpm --filter @workspace/scripts run gen-fields` to regenerate. */
import type { FieldDescriptor } from "./field-vocabulary";

export const FIELDS_DATA: FieldDescriptor[] = [
  {
    "key": "title",
    "label": "Title",
    "type": "string",
    "core": true,
    "required": true,
    "group": "core"
  },
  {
    "key": "status",
    "label": "Status",
    "type": "enum",
    "core": true,
    "group": "core"
  },
  {
    "key": "description",
    "label": "Description",
    "type": "text",
    "group": "core"
  },
  {
    "key": "assignee",
    "label": "Assignee",
    "type": "user",
    "group": "people"
  },
  {
    "key": "reporter",
    "label": "Reporter",
    "type": "user",
    "group": "people"
  },
  {
    "key": "watchers",
    "label": "Watchers",
    "type": "labels",
    "group": "people"
  },
  {
    "key": "priority",
    "label": "Priority",
    "type": "enum",
    "group": "classification"
  },
  {
    "key": "labels",
    "label": "Labels",
    "type": "labels",
    "group": "classification"
  },
  {
    "key": "type",
    "label": "Work item type",
    "type": "enum",
    "group": "classification"
  },
  {
    "key": "component",
    "label": "Component",
    "type": "string",
    "group": "classification"
  },
  {
    "key": "resolution",
    "label": "Resolution",
    "type": "enum",
    "group": "classification"
  },
  {
    "key": "severity",
    "label": "Severity",
    "type": "enum",
    "group": "classification"
  },
  {
    "key": "fixVersion",
    "label": "Fix version",
    "type": "string",
    "group": "classification"
  },
  {
    "key": "environment",
    "label": "Environment",
    "type": "string",
    "group": "classification"
  },
  {
    "key": "startDate",
    "label": "Start date",
    "type": "date",
    "group": "schedule"
  },
  {
    "key": "dueDate",
    "label": "Due date",
    "type": "date",
    "group": "schedule"
  },
  {
    "key": "milestone",
    "label": "Milestone",
    "type": "enum",
    "group": "schedule"
  },
  {
    "key": "baselineStart",
    "label": "Baseline start",
    "type": "date",
    "group": "schedule"
  },
  {
    "key": "baselineFinish",
    "label": "Baseline finish",
    "type": "date",
    "group": "schedule"
  },
  {
    "key": "estimateHours",
    "label": "Estimate (h)",
    "type": "number",
    "group": "effort"
  },
  {
    "key": "loggedHours",
    "label": "Logged (h)",
    "type": "number",
    "group": "effort"
  },
  {
    "key": "remainingHours",
    "label": "Remaining (h)",
    "type": "number",
    "group": "effort"
  },
  {
    "key": "storyPoints",
    "label": "Story points",
    "type": "number",
    "group": "agile"
  },
  {
    "key": "sprint",
    "label": "Sprint",
    "type": "string",
    "group": "agile"
  },
  {
    "key": "epic",
    "label": "Epic",
    "type": "string",
    "group": "agile"
  },
  {
    "key": "rank",
    "label": "Rank",
    "type": "number",
    "group": "agile"
  },
  {
    "key": "actualStart",
    "label": "Actual start",
    "type": "date",
    "group": "schedule"
  },
  {
    "key": "actualFinish",
    "label": "Actual finish",
    "type": "date",
    "group": "schedule"
  },
  {
    "key": "totalFloat",
    "label": "Total float",
    "type": "duration",
    "group": "schedule"
  },
  {
    "key": "criticalPath",
    "label": "On critical path",
    "type": "boolean",
    "group": "schedule"
  },
  {
    "key": "constraintType",
    "label": "Constraint type",
    "type": "enum",
    "group": "schedule"
  },
  {
    "key": "slaDueAt",
    "label": "SLA due at",
    "type": "date",
    "group": "service"
  },
  {
    "key": "originalEstimateHours",
    "label": "Original estimate (h)",
    "type": "number",
    "group": "effort"
  },
  {
    "key": "percentWorkComplete",
    "label": "% work complete",
    "type": "percent",
    "group": "effort"
  },
  {
    "key": "acceptanceCriteria",
    "label": "Acceptance criteria",
    "type": "text",
    "group": "agile"
  },
  {
    "key": "businessValue",
    "label": "Business value",
    "type": "number",
    "group": "agile"
  },
  {
    "key": "riceScore",
    "label": "RICE score",
    "type": "number",
    "group": "agile"
  },
  {
    "key": "wsjf",
    "label": "WSJF",
    "type": "number",
    "group": "agile"
  },
  {
    "key": "moscow",
    "label": "MoSCoW",
    "type": "enum",
    "group": "agile"
  },
  {
    "key": "confidence",
    "label": "Confidence",
    "type": "percent",
    "group": "agile"
  },
  {
    "key": "budget",
    "label": "Budget",
    "type": "number",
    "group": "financial"
  },
  {
    "key": "plannedCost",
    "label": "Planned cost",
    "type": "number",
    "group": "financial"
  },
  {
    "key": "actualCost",
    "label": "Actual cost",
    "type": "number",
    "group": "financial"
  },
  {
    "key": "currency",
    "label": "Currency",
    "type": "string",
    "group": "financial"
  },
  {
    "key": "billable",
    "label": "Billable",
    "type": "enum",
    "group": "financial"
  },
  {
    "key": "costCenter",
    "label": "Cost centre",
    "type": "string",
    "group": "financial"
  },
  {
    "key": "plannedValue",
    "label": "Planned value (PV)",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "earnedValue",
    "label": "Earned value (EV)",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "budgetAtCompletion",
    "label": "Budget at completion (BAC)",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "estimateAtCompletion",
    "label": "Estimate at completion (EAC)",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "estimateToComplete",
    "label": "Estimate to complete (ETC)",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "costVariance",
    "label": "Cost variance (CV)",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "scheduleVariance",
    "label": "Schedule variance (SV)",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "costPerformanceIndex",
    "label": "CPI",
    "type": "number",
    "group": "financial"
  },
  {
    "key": "schedulePerformanceIndex",
    "label": "SPI",
    "type": "number",
    "group": "financial"
  },
  {
    "key": "billRate",
    "label": "Bill rate",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "costRate",
    "label": "Cost rate",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "committedCost",
    "label": "Committed cost (PO)",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "purchaseOrder",
    "label": "Purchase order",
    "type": "string",
    "group": "financial"
  },
  {
    "key": "revenue",
    "label": "Revenue",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "invoicedAmount",
    "label": "Invoiced",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "margin",
    "label": "Margin",
    "type": "percent",
    "group": "financial"
  },
  {
    "key": "capitalised",
    "label": "Capitalised (capex)",
    "type": "boolean",
    "group": "financial"
  },
  {
    "key": "wbsCode",
    "label": "WBS code",
    "type": "string",
    "group": "financial"
  },
  {
    "key": "healthStatus",
    "label": "Health (RAG)",
    "type": "enum",
    "group": "quality"
  },
  {
    "key": "riskLevel",
    "label": "Risk level",
    "type": "enum",
    "group": "quality"
  },
  {
    "key": "impact",
    "label": "Impact",
    "type": "enum",
    "group": "quality"
  },
  {
    "key": "urgency",
    "label": "Urgency",
    "type": "enum",
    "group": "quality"
  },
  {
    "key": "blocked",
    "label": "Blocked",
    "type": "boolean",
    "group": "quality"
  },
  {
    "key": "blockedReason",
    "label": "Blocked reason",
    "type": "string",
    "group": "quality"
  },
  {
    "key": "mitigation",
    "label": "Mitigation",
    "type": "text",
    "group": "quality"
  },
  {
    "key": "defectCount",
    "label": "Defect count",
    "type": "number",
    "group": "quality"
  },
  {
    "key": "dealValue",
    "label": "Deal value",
    "type": "currency",
    "group": "crm"
  },
  {
    "key": "dealProbability",
    "label": "Win probability",
    "type": "percent",
    "group": "crm"
  },
  {
    "key": "forecastProbability",
    "label": "Forecast probability",
    "type": "percent",
    "group": "crm"
  },
  {
    "key": "forecastCategory",
    "label": "Forecast category",
    "type": "enum",
    "group": "crm"
  },
  {
    "key": "dealStatus",
    "label": "Deal status",
    "type": "enum",
    "group": "crm"
  },
  {
    "key": "dealStage",
    "label": "Deal stage",
    "type": "reference",
    "references": "pipeline",
    "group": "crm"
  },
  {
    "key": "pipeline",
    "label": "Pipeline",
    "type": "reference",
    "references": "pipeline",
    "group": "crm"
  },
  {
    "key": "dealOwner",
    "label": "Deal owner",
    "type": "user",
    "group": "crm"
  },
  {
    "key": "account",
    "label": "Account",
    "type": "reference",
    "references": "account",
    "group": "crm"
  },
  {
    "key": "contact",
    "label": "Contact",
    "type": "reference",
    "references": "contact",
    "group": "crm"
  },
  {
    "key": "leadSource",
    "label": "Lead source",
    "type": "enum",
    "group": "crm"
  },
  {
    "key": "nextStep",
    "label": "Next step",
    "type": "string",
    "group": "crm"
  },
  {
    "key": "expectedCloseDate",
    "label": "Expected close date",
    "type": "date",
    "group": "crm"
  },
  {
    "key": "slaBreached",
    "label": "SLA breached",
    "type": "boolean",
    "group": "service"
  },
  {
    "key": "firstResponseAt",
    "label": "First response at",
    "type": "date",
    "group": "service"
  },
  {
    "key": "resolvedAt",
    "label": "Resolved at",
    "type": "date",
    "group": "service"
  },
  {
    "key": "reopenCount",
    "label": "Reopen count",
    "type": "number",
    "group": "service"
  },
  {
    "key": "csatScore",
    "label": "CSAT score",
    "type": "number",
    "group": "service"
  },
  {
    "key": "csatComment",
    "label": "CSAT comment",
    "type": "text",
    "group": "service"
  },
  {
    "key": "sentiment",
    "label": "Sentiment",
    "type": "enum",
    "group": "service"
  },
  {
    "key": "channel",
    "label": "Channel",
    "type": "enum",
    "group": "service"
  },
  {
    "key": "requester",
    "label": "Requester",
    "type": "user",
    "group": "service"
  },
  {
    "key": "affectedService",
    "label": "Affected service",
    "type": "reference",
    "references": "service",
    "group": "service"
  },
  {
    "key": "changeType",
    "label": "Change type",
    "type": "enum",
    "group": "service"
  },
  {
    "key": "strategicGoals",
    "label": "Strategic goals",
    "type": "labels",
    "group": "strategy"
  },
  {
    "key": "kpis",
    "label": "KPIs",
    "type": "labels",
    "group": "strategy"
  },
  {
    "key": "objectives",
    "label": "Objectives / OKRs",
    "type": "labels",
    "group": "strategy"
  },
  {
    "key": "strategicTheme",
    "label": "Strategic theme",
    "type": "enum",
    "group": "strategy"
  },
  {
    "key": "valueStream",
    "label": "Value stream",
    "type": "string",
    "group": "strategy"
  },
  {
    "key": "strategicContribution",
    "label": "Strategic contribution",
    "type": "percent",
    "group": "strategy"
  },
  {
    "key": "expectedBenefit",
    "label": "Expected benefit",
    "type": "text",
    "group": "strategy"
  },
  {
    "key": "benefitRealised",
    "label": "Benefit realised",
    "type": "percent",
    "group": "strategy"
  },
  {
    "key": "programmeId",
    "label": "Programme",
    "type": "reference",
    "references": "programme",
    "group": "relationship"
  },
  {
    "key": "parentTask",
    "label": "Parent",
    "type": "reference",
    "references": "task",
    "group": "relationship"
  },
  {
    "key": "dependsOn",
    "label": "Depends on",
    "type": "reference",
    "references": "task",
    "group": "relationship"
  },
  {
    "key": "blocks",
    "label": "Blocks",
    "type": "reference",
    "references": "task",
    "group": "relationship"
  },
  {
    "key": "relatesTo",
    "label": "Relates to",
    "type": "reference",
    "references": "task",
    "group": "relationship"
  },
  {
    "key": "duplicateOf",
    "label": "Duplicate of",
    "type": "reference",
    "references": "task",
    "group": "relationship"
  },
  {
    "key": "completionPct",
    "label": "Completion %",
    "type": "number",
    "group": "derived"
  },
  {
    "key": "weightedValue",
    "label": "Weighted value",
    "type": "currency",
    "group": "derived"
  },
  {
    "key": "forecastAmount",
    "label": "Forecast amount",
    "type": "currency",
    "group": "derived"
  },
  {
    "key": "expectedRevenue",
    "label": "Expected revenue",
    "type": "currency",
    "group": "derived"
  },
  {
    "key": "benefitType",
    "label": "Benefit type",
    "type": "enum",
    "group": "benefits"
  },
  {
    "key": "benefitOwner",
    "label": "Benefit owner",
    "type": "user",
    "group": "benefits"
  },
  {
    "key": "plannedBenefitValue",
    "label": "Planned benefit value",
    "type": "currency",
    "group": "benefits"
  },
  {
    "key": "actualBenefitValue",
    "label": "Actual benefit value",
    "type": "currency",
    "group": "benefits"
  },
  {
    "key": "benefitMeasure",
    "label": "Benefit measure",
    "type": "string",
    "group": "benefits"
  },
  {
    "key": "benefitBaseline",
    "label": "Benefit baseline",
    "type": "number",
    "group": "benefits"
  },
  {
    "key": "benefitTarget",
    "label": "Benefit target",
    "type": "number",
    "group": "benefits"
  },
  {
    "key": "benefitStartDate",
    "label": "Benefit start date",
    "type": "date",
    "group": "benefits"
  },
  {
    "key": "benefitDueDate",
    "label": "Benefit due date",
    "type": "date",
    "group": "benefits"
  },
  {
    "key": "benefitStatus",
    "label": "Benefit status",
    "type": "enum",
    "group": "benefits"
  },
  {
    "key": "benefitConfidence",
    "label": "Benefit confidence",
    "type": "percent",
    "group": "benefits"
  },
  {
    "key": "expenditureType",
    "label": "Expenditure type (CapEx/OpEx)",
    "type": "enum",
    "group": "financial"
  },
  {
    "key": "capexAmount",
    "label": "Capital expenditure",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "opexAmount",
    "label": "Operating expenditure",
    "type": "currency",
    "group": "financial"
  },
  {
    "key": "costCategory",
    "label": "Cost category",
    "type": "string",
    "group": "financial"
  },
  {
    "key": "depreciationMonths",
    "label": "Depreciation period (months)",
    "type": "number",
    "group": "financial"
  },
  {
    "key": "stakeholderName",
    "label": "Stakeholder",
    "type": "string",
    "group": "stakeholder",
    "entity": "stakeholder",
    "required": true
  },
  {
    "key": "stakeholderRole",
    "label": "Role",
    "type": "string",
    "group": "stakeholder",
    "entity": "stakeholder"
  },
  {
    "key": "influence",
    "label": "Influence",
    "type": "enum",
    "group": "stakeholder",
    "entity": "stakeholder"
  },
  {
    "key": "interest",
    "label": "Interest",
    "type": "enum",
    "group": "stakeholder",
    "entity": "stakeholder"
  },
  {
    "key": "engagementLevel",
    "label": "Engagement",
    "type": "enum",
    "group": "stakeholder",
    "entity": "stakeholder"
  },
  {
    "key": "commsCadence",
    "label": "Comms cadence",
    "type": "enum",
    "group": "stakeholder",
    "entity": "stakeholder"
  },
  {
    "key": "engagementStrategy",
    "label": "Engagement strategy",
    "type": "text",
    "group": "stakeholder",
    "entity": "stakeholder"
  },
  {
    "key": "deliverable",
    "label": "Deliverable",
    "type": "string",
    "group": "raci",
    "entity": "raci",
    "required": true
  },
  {
    "key": "raciResponsible",
    "label": "Responsible (R)",
    "type": "labels",
    "group": "raci",
    "entity": "raci"
  },
  {
    "key": "raciAccountable",
    "label": "Accountable (A)",
    "type": "user",
    "group": "raci",
    "entity": "raci"
  },
  {
    "key": "raciConsulted",
    "label": "Consulted (C)",
    "type": "labels",
    "group": "raci",
    "entity": "raci"
  },
  {
    "key": "raciInformed",
    "label": "Informed (I)",
    "type": "labels",
    "group": "raci",
    "entity": "raci"
  },
  {
    "key": "probability",
    "label": "Probability",
    "type": "enum",
    "group": "risk",
    "entity": "raid"
  },
  {
    "key": "riskExposure",
    "label": "Risk exposure (P×I)",
    "type": "number",
    "group": "risk",
    "entity": "raid"
  },
  {
    "key": "responseStrategy",
    "label": "Response strategy",
    "type": "enum",
    "group": "risk",
    "entity": "raid"
  }
];
