/* GENERATED by scripts/src/gen-forms.ts — do not edit.
   Forms are authored as JSON under lib/backend-catalogue/assets/forms/;
   run `pnpm --filter @workspace/scripts run gen-forms` to regenerate. */
import type { FormDefinition } from "./form-catalogue";

export const FORMS_DATA: FormDefinition[] = [
  {
    "id": "change-request",
    "label": "Change request",
    "description": "Request a change to an in-flight project (governance intake).",
    "submitLabel": "Raise change",
    "methodologies": [
      "prince2",
      "waterfall",
      "governance"
    ],
    "fields": [
      {
        "key": "summary",
        "label": "Change summary",
        "type": "text",
        "mapTo": "title",
        "required": true,
        "maxLength": 200
      },
      {
        "key": "rationale",
        "label": "Rationale / business case",
        "type": "textarea",
        "mapTo": "description",
        "required": true,
        "maxLength": 4000
      },
      {
        "key": "impact",
        "label": "Impact",
        "type": "select",
        "mapTo": "impact",
        "options": [
          "low",
          "medium",
          "high"
        ],
        "required": true
      },
      {
        "key": "urgency",
        "label": "Urgency",
        "type": "select",
        "mapTo": "urgency",
        "options": [
          "low",
          "medium",
          "high"
        ],
        "required": true
      }
    ],
    "target": {
      "kind": "issue",
      "status": "triage",
      "labels": [
        "change-request"
      ]
    }
  },
  {
    "id": "intake-request",
    "label": "Work request",
    "description": "Submit a new piece of work for triage.",
    "submitLabel": "Submit request",
    "methodologies": [
      "*"
    ],
    "fields": [
      {
        "key": "summary",
        "label": "Summary",
        "type": "text",
        "mapTo": "title",
        "required": true,
        "placeholder": "Short title for the request",
        "maxLength": 200
      },
      {
        "key": "details",
        "label": "What do you need?",
        "type": "textarea",
        "mapTo": "description",
        "required": true,
        "maxLength": 4000
      },
      {
        "key": "priority",
        "label": "Priority",
        "type": "select",
        "mapTo": "priority",
        "options": [
          "low",
          "medium",
          "high",
          "urgent"
        ],
        "required": true
      },
      {
        "key": "neededBy",
        "label": "Needed by",
        "type": "date",
        "mapTo": "dueDate"
      },
      {
        "key": "requestedBy",
        "label": "Requested by",
        "type": "text",
        "mapTo": "description",
        "maxLength": 120
      }
    ],
    "target": {
      "kind": "issue",
      "status": "triage",
      "labels": [
        "intake"
      ]
    }
  }
];
