/* GENERATED by scripts/src/gen-impact-vocabulary.ts — do not edit.
   Source: lib/backend-catalogue/assets/impact-vocabulary.json;
   run `pnpm --filter @workspace/scripts run gen-impact-vocabulary` to regenerate. */
import type { ImpactVocabEntry } from "./impact-vocabulary";

export const IMPACT_VOCABULARY_DATA: ImpactVocabEntry[] = [
  {
    "id": "low",
    "label": "Low",
    "order": 0,
    "level": 1,
    "color": "#22c55e"
  },
  {
    "id": "medium",
    "label": "Medium",
    "order": 1,
    "level": 2,
    "color": "#f59e0b"
  },
  {
    "id": "high",
    "label": "High",
    "order": 2,
    "level": 3,
    "color": "#ef4444"
  }
];
