/* GENERATED by scripts/src/gen-likelihood-vocabulary.ts — do not edit.
   Source: lib/backend-catalogue/assets/likelihood-vocabulary.json;
   run `pnpm --filter @workspace/scripts run gen-likelihood-vocabulary` to regenerate. */
import type { LikelihoodVocabEntry } from "./likelihood-vocabulary";

export const LIKELIHOOD_VOCABULARY_DATA: LikelihoodVocabEntry[] = [
  {
    "id": "low",
    "label": "Low",
    "order": 0,
    "level": 1,
    "color": "#22c55e"
  },
  {
    "id": "medium",
    "label": "Medium",
    "order": 1,
    "level": 2,
    "color": "#f59e0b"
  },
  {
    "id": "high",
    "label": "High",
    "order": 2,
    "level": 3,
    "color": "#ef4444"
  }
];
