/* GENERATED by scripts/src/gen-methodology-rulesets.ts — do not edit.
   Reference rulesets are authored as JSON under lib/backend-catalogue/assets/methodology-rulesets/;
   run `pnpm --filter @workspace/scripts run gen-methodology-rulesets` to regenerate. */
import type { ReferenceRulesetData } from "./methodology-rulesets";

export const REFERENCE_RULESETS_DATA: ReferenceRulesetData[] = [
  {
    "id": "gtd",
    "label": "GTD next-action baseline",
    "rationale": "GTD keeps work trustworthy: every actionable item is a concrete next action, so capture is fast but nothing stalls. Schedule sanity stays hard; estimation is never imposed. (The cross-entity invariant 'every active project must have a next action' is enforced by the engine, not a field rule.)",
    "modes": {
      "due-after-start": "hard"
    },
    "fieldRules": [
      {
        "id": "gtd-waiting-on",
        "action": "any-write",
        "field": "waitingOn",
        "whenPresent": "waiting",
        "mode": "warn",
        "message": "A waiting item should record who/what it is waiting on (GTD)."
      }
    ]
  },
  {
    "id": "kanban",
    "label": "Kanban flow baseline",
    "rationale": "Pulled work should be owned, and a blocked card must say why so the flow is visible. No estimation is imposed.",
    "modes": {
      "due-after-start": "hard",
      "require-assignee": "warn"
    },
    "fieldRules": [
      {
        "id": "kanban-blocked-reason",
        "action": "any-write",
        "field": "blockedReason",
        "whenPresent": "blocked",
        "mode": "warn",
        "message": "A blocked card must record why it is blocked (Kanban flow)."
      }
    ]
  },
  {
    "id": "prince2",
    "label": "PRINCE2 management-products baseline",
    "rationale": "Process-driven control: tasks are described and dated, and identified risks carry a mitigation.",
    "modes": {
      "due-after-start": "hard",
      "require-description": "hard"
    },
    "fieldRules": [
      {
        "id": "prince2-start",
        "action": "create_issue",
        "field": "startDate",
        "mode": "warn",
        "message": "Set a start date for stage planning (PRINCE2)."
      },
      {
        "id": "prince2-due",
        "action": "create_issue",
        "field": "dueDate",
        "mode": "warn",
        "message": "Set a target finish for stage planning (PRINCE2)."
      },
      {
        "id": "prince2-risk-mitigation",
        "action": "any-write",
        "field": "mitigation",
        "whenPresent": "riskLevel",
        "mode": "warn",
        "message": "A rated risk should record its mitigation (PRINCE2 risk management)."
      }
    ]
  },
  {
    "id": "safe",
    "label": "SAFe scaled-agile baseline",
    "rationale": "Backlog items are owned and estimated for PI planning, and blocked work is made explicit across teams.",
    "modes": {
      "due-after-start": "hard",
      "require-assignee": "warn"
    },
    "fieldRules": [
      {
        "id": "safe-estimate",
        "action": "create_issue",
        "field": "storyPoints",
        "mode": "warn",
        "message": "Backlog items should be estimated for PI planning (SAFe)."
      },
      {
        "id": "safe-blocked-reason",
        "action": "any-write",
        "field": "blockedReason",
        "whenPresent": "blocked",
        "mode": "warn",
        "message": "Blocked work must be explicit across the ART (SAFe)."
      }
    ]
  },
  {
    "id": "scrum",
    "label": "Scrum compliance baseline",
    "rationale": "Stories should be owned and estimated so the sprint is plannable; schedule sanity stays hard.",
    "modes": {
      "due-after-start": "hard",
      "require-assignee": "warn",
      "require-description": "warn"
    },
    "fieldRules": [
      {
        "id": "scrum-estimate",
        "action": "create_issue",
        "field": "storyPoints",
        "mode": "warn",
        "message": "Stories should carry a story-point estimate (Scrum)."
      }
    ]
  },
  {
    "id": "scrumban",
    "label": "Scrumban baseline",
    "rationale": "Scrum's estimation discipline plus Kanban's blocked-work visibility.",
    "modes": {
      "due-after-start": "hard",
      "require-assignee": "warn"
    },
    "fieldRules": [
      {
        "id": "scrumban-estimate",
        "action": "create_issue",
        "field": "storyPoints",
        "mode": "warn",
        "message": "Stories should carry a story-point estimate (Scrumban)."
      },
      {
        "id": "scrumban-blocked-reason",
        "action": "any-write",
        "field": "blockedReason",
        "whenPresent": "blocked",
        "mode": "warn",
        "message": "A blocked card must record why it is blocked (Scrumban)."
      }
    ]
  },
  {
    "id": "waterfall",
    "label": "Waterfall plan-completeness baseline",
    "rationale": "Plan-driven work needs dated, estimated, described tasks to baseline and track a critical path.",
    "modes": {
      "due-after-start": "hard",
      "require-description": "warn"
    },
    "fieldRules": [
      {
        "id": "waterfall-start",
        "action": "create_issue",
        "field": "startDate",
        "mode": "hard",
        "message": "A start date is required to baseline a plan-driven task (Waterfall)."
      },
      {
        "id": "waterfall-due",
        "action": "create_issue",
        "field": "dueDate",
        "mode": "hard",
        "message": "A finish date is required to baseline a plan-driven task (Waterfall)."
      },
      {
        "id": "waterfall-estimate",
        "action": "create_issue",
        "field": "estimateHours",
        "mode": "warn",
        "message": "An effort estimate (hours) should be set for resource planning (Waterfall)."
      }
    ]
  }
];
