/* GENERATED by scripts/src/gen-methodologies.ts — do not edit.
   Methodologies are authored as JSON under lib/backend-catalogue/assets/methodologies/;
   run `pnpm --filter @workspace/scripts run gen-methodologies` to regenerate. */
import type { MethodologyDefinition } from "./methodology-catalogue";

export const METHODOLOGIES_DATA: MethodologyDefinition[] = [
  {
    "id": "fundraising-pipeline",
    "label": "Fundraising pipeline",
    "docsUrl": "https://www.institute-of-fundraising.org.uk/",
    "kind": "agile",
    "capabilities": {
      "iterations": false,
      "board": true,
      "wipLimits": false,
      "phases": false,
      "baseline": false,
      "estimation": "none"
    },
    "tools": {
      "states": [
        "lead",
        "qualified",
        "cultivating",
        "ask-made",
        "pledged",
        "received",
        "stewarding",
        "lapsed"
      ],
      "ceremonies": [
        "pipeline-review"
      ]
    },
    "alsoProvides": [
      {
        "plane": "screens",
        "note": "donor pipeline board"
      },
      {
        "plane": "reports",
        "note": "pipeline value / conversion / forecast"
      }
    ],
    "notes": "Charity/SME starter template: a donor/fundraising pipeline (CRM-style stages) from lead to received and stewarding, with pipeline-value reporting.",
    "order": 72
  },
  {
    "id": "grant-tracking",
    "label": "Grant tracking",
    "docsUrl": "https://www.charityexcellence.co.uk/grant-management/",
    "kind": "traditional",
    "capabilities": {
      "iterations": false,
      "board": true,
      "wipLimits": false,
      "phases": true,
      "baseline": true,
      "estimation": "none"
    },
    "tools": {
      "states": [
        "prospect",
        "drafting",
        "submitted",
        "under-review",
        "awarded",
        "declined",
        "delivering",
        "reporting",
        "closed"
      ],
      "ceremonies": [
        "funder-report",
        "milestone-review"
      ]
    },
    "alsoProvides": [
      {
        "plane": "screens",
        "note": "grant lifecycle board"
      },
      {
        "plane": "reports",
        "note": "pipeline value / spend vs award"
      }
    ],
    "notes": "Charity/SME starter template: a funder-grant lifecycle from prospect to close, with delivery phases, baselined timelines and funder reporting.",
    "order": 70
  },
  {
    "id": "gtd",
    "label": "Getting Things Done (GTD)",
    "docsUrl": "https://gettingthingsdone.com/",
    "kind": "agile",
    "capabilities": {
      "iterations": false,
      "board": true,
      "wipLimits": false,
      "phases": false,
      "baseline": false,
      "estimation": "none"
    },
    "tools": {
      "states": [
        "inbox",
        "next",
        "waiting",
        "scheduled",
        "someday",
        "done"
      ],
      "ceremonies": [
        "capture",
        "clarify",
        "organise",
        "weekly-review",
        "engage"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "weekly review (stalled projects, waiting-for follow-ups)"
      },
      {
        "plane": "screens",
        "note": "next actions by context; weekly review"
      }
    ],
    "invariants": [
      {
        "id": "gtd-next-action",
        "kind": "every-active-project-has-next-action",
        "message": "Every active project must have a defined next action (GTD).",
        "severity": "warn"
      }
    ],
    "notes": "Personal-productivity flow: capture to an inbox, clarify to a single next action per project, organise by context/energy, reflect in a weekly review, engage. Core business rule: every ACTIVE project must have a defined next action.",
    "order": 5
  },
  {
    "id": "kanban",
    "label": "Kanban",
    "docsUrl": "https://kanban.university/kanban-guide/",
    "kind": "agile",
    "capabilities": {
      "iterations": false,
      "board": true,
      "wipLimits": true,
      "phases": false,
      "baseline": false,
      "estimation": "none"
    },
    "tools": {
      "states": [
        "backlog",
        "todo",
        "in_progress",
        "done"
      ],
      "ceremonies": [
        "replenishment",
        "cadence-review"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "cumulative flow"
      },
      {
        "plane": "screens",
        "note": "WIP-limited board"
      }
    ],
    "notes": "Continuous flow, explicit WIP limits, no fixed iterations.",
    "order": 20
  },
  {
    "id": "prince2",
    "label": "PRINCE2",
    "docsUrl": "https://www.prince2.com/uk/prince2-methodology",
    "kind": "traditional",
    "capabilities": {
      "iterations": false,
      "board": false,
      "wipLimits": false,
      "phases": true,
      "baseline": true,
      "estimation": "hours"
    },
    "tools": {
      "states": [
        "starting-up",
        "initiating",
        "delivering",
        "closing"
      ],
      "ceremonies": [
        "stage-boundary",
        "exception-report"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "highlight / exception reports"
      }
    ],
    "notes": "Process-driven stage management with management products.",
    "order": 50
  },
  {
    "id": "safe",
    "label": "SAFe",
    "docsUrl": "https://scaledagileframework.com/",
    "kind": "hybrid",
    "capabilities": {
      "iterations": true,
      "board": true,
      "wipLimits": true,
      "phases": false,
      "baseline": false,
      "estimation": "story-points"
    },
    "tools": {
      "states": [
        "funnel",
        "backlog",
        "in_progress",
        "review",
        "done"
      ],
      "ceremonies": [
        "pi-planning",
        "sprint-planning",
        "system-demo",
        "inspect-and-adapt"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "PI burnup / portfolio"
      },
      {
        "plane": "screens",
        "note": "programme board"
      }
    ],
    "notes": "Scaled agile across teams (ARTs, PIs); the enterprise-agile option.",
    "order": 60
  },
  {
    "id": "scrum",
    "label": "Scrum",
    "docsUrl": "https://scrumguides.org/",
    "kind": "agile",
    "capabilities": {
      "iterations": true,
      "board": true,
      "wipLimits": false,
      "phases": false,
      "baseline": false,
      "estimation": "story-points"
    },
    "tools": {
      "states": [
        "backlog",
        "todo",
        "in_progress",
        "review",
        "done"
      ],
      "ceremonies": [
        "sprint-planning",
        "daily-standup",
        "review",
        "retrospective"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "burndown / velocity"
      },
      {
        "plane": "screens",
        "note": "sprint board"
      }
    ],
    "settings": {
      "priorityWeights": {
        "rice": 20,
        "wsjf": 40,
        "moscow": 10,
        "strategic": 20,
        "benefit": 10
      }
    },
    "notes": "Time-boxed sprints, story points, the four ceremonies.",
    "order": 10
  },
  {
    "id": "scrumban",
    "label": "Scrumban",
    "docsUrl": "https://www.atlassian.com/agile/project-management/scrumban",
    "kind": "hybrid",
    "capabilities": {
      "iterations": true,
      "board": true,
      "wipLimits": true,
      "phases": false,
      "baseline": false,
      "estimation": "story-points"
    },
    "tools": {
      "states": [
        "backlog",
        "todo",
        "in_progress",
        "review",
        "done"
      ],
      "ceremonies": [
        "planning",
        "daily-standup"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "cumulative flow + velocity"
      }
    ],
    "notes": "Scrum cadence with Kanban WIP limits.",
    "order": 30
  },
  {
    "id": "volunteer-roster",
    "label": "Volunteer roster",
    "docsUrl": "https://www.ncvo.org.uk/help-and-guidance/involving-volunteers/",
    "kind": "agile",
    "capabilities": {
      "iterations": false,
      "board": true,
      "wipLimits": true,
      "phases": false,
      "baseline": false,
      "estimation": "none"
    },
    "tools": {
      "states": [
        "available",
        "assigned",
        "scheduled",
        "checked-in",
        "completed",
        "no-show"
      ],
      "ceremonies": [
        "weekly-rota",
        "shift-debrief"
      ]
    },
    "alsoProvides": [
      {
        "plane": "screens",
        "note": "roster / shift board"
      }
    ],
    "notes": "Charity/SME starter template: coordinate volunteers across shifts as a WIP-limited board — available → assigned → scheduled → checked-in → completed.",
    "order": 71
  },
  {
    "id": "waterfall",
    "label": "Waterfall",
    "docsUrl": "https://en.wikipedia.org/wiki/Waterfall_model",
    "kind": "traditional",
    "capabilities": {
      "iterations": false,
      "board": false,
      "wipLimits": false,
      "phases": true,
      "baseline": true,
      "estimation": "hours"
    },
    "tools": {
      "states": [
        "initiation",
        "planning",
        "execution",
        "monitoring",
        "closure"
      ],
      "ceremonies": [
        "stage-gate-review"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "Gantt + EVM"
      },
      {
        "plane": "screens",
        "note": "schedule / Gantt"
      }
    ],
    "settings": {
      "fxRatePolicy": "periodClose",
      "priorityWeights": {
        "rice": 15,
        "wsjf": 10,
        "moscow": 20,
        "strategic": 40,
        "benefit": 15
      }
    },
    "notes": "Sequential phases, baselines, critical path.",
    "order": 40
  }
];
