/* GENERATED by scripts/src/gen-methodologies.ts — do not edit.
   Methodologies are authored as JSON under lib/backend-catalogue/assets/methodologies/;
   run `pnpm --filter @workspace/scripts run gen-methodologies` to regenerate. */
import type { MethodologyDefinition } from "./methodology-catalogue";

export const METHODOLOGIES_DATA: MethodologyDefinition[] = [
  {
    "id": "kanban",
    "label": "Kanban",
    "docsUrl": "https://kanban.university/kanban-guide/",
    "kind": "agile",
    "capabilities": {
      "iterations": false,
      "board": true,
      "wipLimits": true,
      "phases": false,
      "baseline": false,
      "estimation": "none"
    },
    "tools": {
      "states": [
        "backlog",
        "todo",
        "in_progress",
        "done"
      ],
      "ceremonies": [
        "replenishment",
        "cadence-review"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "cumulative flow"
      },
      {
        "plane": "screens",
        "note": "WIP-limited board"
      }
    ],
    "notes": "Continuous flow, explicit WIP limits, no fixed iterations.",
    "order": 20
  },
  {
    "id": "prince2",
    "label": "PRINCE2",
    "docsUrl": "https://www.prince2.com/uk/prince2-methodology",
    "kind": "traditional",
    "capabilities": {
      "iterations": false,
      "board": false,
      "wipLimits": false,
      "phases": true,
      "baseline": true,
      "estimation": "hours"
    },
    "tools": {
      "states": [
        "starting-up",
        "initiating",
        "delivering",
        "closing"
      ],
      "ceremonies": [
        "stage-boundary",
        "exception-report"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "highlight / exception reports"
      }
    ],
    "notes": "Process-driven stage management with management products.",
    "order": 50
  },
  {
    "id": "safe",
    "label": "SAFe",
    "docsUrl": "https://scaledagileframework.com/",
    "kind": "hybrid",
    "capabilities": {
      "iterations": true,
      "board": true,
      "wipLimits": true,
      "phases": false,
      "baseline": false,
      "estimation": "story-points"
    },
    "tools": {
      "states": [
        "funnel",
        "backlog",
        "in_progress",
        "review",
        "done"
      ],
      "ceremonies": [
        "pi-planning",
        "sprint-planning",
        "system-demo",
        "inspect-and-adapt"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "PI burnup / portfolio"
      },
      {
        "plane": "screens",
        "note": "programme board"
      }
    ],
    "notes": "Scaled agile across teams (ARTs, PIs); the enterprise-agile option.",
    "order": 60
  },
  {
    "id": "scrum",
    "label": "Scrum",
    "docsUrl": "https://scrumguides.org/",
    "kind": "agile",
    "capabilities": {
      "iterations": true,
      "board": true,
      "wipLimits": false,
      "phases": false,
      "baseline": false,
      "estimation": "story-points"
    },
    "tools": {
      "states": [
        "backlog",
        "todo",
        "in_progress",
        "review",
        "done"
      ],
      "ceremonies": [
        "sprint-planning",
        "daily-standup",
        "review",
        "retrospective"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "burndown / velocity"
      },
      {
        "plane": "screens",
        "note": "sprint board"
      }
    ],
    "notes": "Time-boxed sprints, story points, the four ceremonies.",
    "order": 10
  },
  {
    "id": "scrumban",
    "label": "Scrumban",
    "docsUrl": "https://www.atlassian.com/agile/project-management/scrumban",
    "kind": "hybrid",
    "capabilities": {
      "iterations": true,
      "board": true,
      "wipLimits": true,
      "phases": false,
      "baseline": false,
      "estimation": "story-points"
    },
    "tools": {
      "states": [
        "backlog",
        "todo",
        "in_progress",
        "review",
        "done"
      ],
      "ceremonies": [
        "planning",
        "daily-standup"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "cumulative flow + velocity"
      }
    ],
    "notes": "Scrum cadence with Kanban WIP limits.",
    "order": 30
  },
  {
    "id": "waterfall",
    "label": "Waterfall",
    "docsUrl": "https://en.wikipedia.org/wiki/Waterfall_model",
    "kind": "traditional",
    "capabilities": {
      "iterations": false,
      "board": false,
      "wipLimits": false,
      "phases": true,
      "baseline": true,
      "estimation": "hours"
    },
    "tools": {
      "states": [
        "initiation",
        "planning",
        "execution",
        "monitoring",
        "closure"
      ],
      "ceremonies": [
        "stage-gate-review"
      ]
    },
    "alsoProvides": [
      {
        "plane": "reports",
        "note": "Gantt + EVM"
      },
      {
        "plane": "screens",
        "note": "schedule / Gantt"
      }
    ],
    "notes": "Sequential phases, baselines, critical path.",
    "order": 40
  }
];
