/* GENERATED by scripts/src/gen-notification-routes.ts — do not edit.
   Routes are authored as JSON under lib/backend-catalogue/assets/notification-routes/;
   run `pnpm --filter @workspace/scripts run gen-notification-routes` to regenerate. */
import type { NotificationRoute } from "./notification-routing";

export const ROUTES_DATA: NotificationRoute[] = [
  {
    "id": "assignments",
    "label": "Work assignments",
    "description": "When work is assigned, notify the assignee by email and team chat.",
    "match": {
      "kinds": [
        "assignment",
        "mention"
      ]
    },
    "channels": [
      "email",
      "slack",
      "teams"
    ],
    "methodologies": [
      "*"
    ],
    "order": 20
  },
  {
    "id": "critical-incidents",
    "label": "Critical incidents",
    "description": "Blockers and incidents page the on-call (PagerDuty/Opsgenie) and post to the team chat so managers see them immediately.",
    "match": {
      "kinds": [
        "incident",
        "blocker"
      ]
    },
    "channels": [
      "pagerduty",
      "opsgenie",
      "slack"
    ],
    "audience": {
      "role": "manager"
    },
    "methodologies": [
      "*"
    ],
    "order": 10
  },
  {
    "id": "deadlines",
    "label": "Approaching deadlines",
    "description": "Due-soon and overdue reminders go out over email so nothing slips quietly.",
    "match": {
      "kinds": [
        "due_soon",
        "overdue"
      ]
    },
    "channels": [
      "email"
    ],
    "methodologies": [
      "*"
    ],
    "order": 30
  }
];
