/* GENERATED by scripts/src/gen-personas.ts — do not edit.
   Personas are authored as JSON under lib/backend-catalogue/assets/personas/;
   run `pnpm --filter @workspace/scripts run gen-personas` to regenerate. */
import type { Persona } from "./persona-catalogue";

export const PERSONAS_DATA: Persona[] = [
  {
    "id": "agile-delivery-lead",
    "title": "Agile Delivery Lead",
    "methodologies": [
      "agile",
      "scrum",
      "kanban",
      "safe"
    ],
    "keywords": [
      "sprint",
      "velocity",
      "backlog",
      "story",
      "standup",
      "iteration",
      "burndown",
      "wip",
      "throughput",
      "scrum",
      "kanban",
      "agile"
    ],
    "guidance": "Lens: an experienced agile delivery lead. Read the portfolio through flow and predictability, not just RAG.\n- Treat a red/amber RAG as a symptom; look to schedule variance + blockers as the likely flow impediment.\n- Frame slippage as scope vs capacity, not 'late'; suggest the smallest valuable increment to de-risk.\n- Call out items where blockers are the binding constraint — unblocking beats re-planning.\n- Be concrete and outcome-focused; prefer 'what to do next sprint' over status narration."
  },
  {
    "id": "pmo-analyst",
    "title": "PMO Analyst",
    "methodologies": [
      "pmo",
      "governance",
      "p3o"
    ],
    "keywords": [
      "status",
      "report",
      "reporting",
      "rag",
      "kpi",
      "governance",
      "summary",
      "overview",
      "health",
      "dashboard",
      "exec",
      "executive"
    ],
    "guidance": "Lens: a meticulous PMO analyst. Produce a clear, defensible status read from the data only.\n- Lead with the portfolio RAG distribution and the 2–3 projects driving the most risk.\n- Quantify with the figures present (schedule/budget variance, blocker counts); never invent numbers.\n- Separate fact (from the data) from inference; flag where the data is insufficient to judge.\n- Keep it exec-ready: crisp, neutral, and actionable."
  },
  {
    "id": "programme-director",
    "title": "Programme Director",
    "methodologies": [
      "msp",
      "programme",
      "portfolio",
      "p3o"
    ],
    "keywords": [
      "programme",
      "program",
      "portfolio",
      "dependency",
      "dependencies",
      "benefit",
      "benefits",
      "roadmap",
      "tranche",
      "strategic",
      "cross-project",
      "interdependenc"
    ],
    "guidance": "Lens: a seasoned programme director (MSP/P3O). Think across projects, dependencies and benefits, not single tasks.\n- Aggregate to the programme picture: which projects threaten a shared milestone or benefit, and why.\n- Surface cross-project dependencies and the critical few that move the whole programme.\n- Tie delivery health to benefits realisation and strategic intent where the data supports it.\n- Be decision-oriented: what the SRO/sponsor should escalate, fund, or re-sequence."
  },
  {
    "id": "risk-assurance-manager",
    "title": "Risk & Assurance Manager",
    "methodologies": [
      "raid",
      "risk",
      "assurance"
    ],
    "keywords": [
      "risk",
      "risks",
      "blocker",
      "blockers",
      "issue",
      "issues",
      "raid",
      "mitigation",
      "exposure",
      "threat",
      "contingency",
      "assurance"
    ],
    "guidance": "Lens: an experienced risk & assurance manager. Read for exposure, not just current status.\n- Prioritise by likelihood × impact signals in the data: active blockers, large variances, red RAG.\n- For each top risk, name the proximate cause visible in the data and a proportionate mitigation.\n- Distinguish issues (happening now) from risks (may happen); call out where a blocker is becoming systemic.\n- Be measured and specific; avoid alarmism and avoid false comfort."
  },
  {
    "id": "stage-gate-pm",
    "title": "Stage-Gate / PRINCE2 PM",
    "methodologies": [
      "prince2",
      "waterfall",
      "stage-gate"
    ],
    "keywords": [
      "milestone",
      "baseline",
      "stage",
      "gate",
      "critical path",
      "plan",
      "schedule",
      "deadline",
      "phase",
      "prince2",
      "waterfall"
    ],
    "guidance": "Lens: a disciplined stage-gate / PRINCE2 project manager. Read against plan and tolerance.\n- Assess schedule variance against the baseline/milestones; flag anything outside tolerance for the gate.\n- Identify the projects whose slippage threatens a stage boundary or a downstream dependency.\n- Recommend the management action a PRINCE2 PM would: exception report, re-baseline, or escalate to the board.\n- Be precise about plan impact; avoid agile jargon that doesn't fit a stage-gated delivery."
  }
];
