/* GENERATED by scripts/src/gen-presets.ts — do not edit.
   Presets are authored as JSON under lib/backend-catalogue/assets/presets/;
   run `pnpm --filter @workspace/scripts run gen-presets` to regenerate. */
import type { Preset } from "./preset-catalogue";

export const PRESETS_DATA: Preset[] = [
  {
    "id": "enterprise-scrum",
    "label": "Enterprise Scrum",
    "description": "Scrum for a governed, at-scale org: the enterprise-PMO posture (governance, currency, priority model) plus the Scrum methodology curated in, its reference ruleset applied, a starter sprint project, and an executive delivery dashboard — so a new enterprise team lands on a governed, working Scrum setup in one step.",
    "methodology": "scrum",
    "settingsPreset": "enterprise-pmo",
    "referenceRuleset": "scrum",
    "projectTemplate": "scrum-starter",
    "dashboardPreset": "head-of-projects-today",
    "tags": [
      "agile",
      "scrum",
      "enterprise"
    ],
    "order": 20
  },
  {
    "id": "scrum-team",
    "label": "Scrum team",
    "description": "A sprint-ready Scrum setup: the Scrum methodology curated in, its reference ruleset applied, and a starter sprint project seeded with the ceremonies as work items — so a new team lands on a working board, backlog, burndown and velocity in one step.",
    "methodology": "scrum",
    "settingsPreset": "growth-business",
    "referenceRuleset": "scrum",
    "projectTemplate": "scrum-starter",
    "dashboardPreset": "project-manager-today",
    "tags": [
      "agile",
      "scrum"
    ],
    "order": 10
  },
  {
    "id": "self-hosted-scrum",
    "label": "Self-hosted Scrum",
    "description": "Scrum on your own infrastructure with OmniProject's built-in database as the system of record — no external backend to connect and no external database. Minimal egress, on-device speech, AI off. The Scrum methodology is curated in with its reference ruleset, a starter sprint project and a delivery dashboard. Pair with the self-hosted deployment preset (BUILTIN_BROKER) so the built-in store is the SoR.",
    "methodology": "scrum",
    "settingsPreset": "regulated-selfhost",
    "referenceRuleset": "scrum",
    "projectTemplate": "scrum-starter",
    "dashboardPreset": "project-manager-today",
    "tags": [
      "agile",
      "scrum",
      "self-hosted"
    ],
    "order": 30
  },
  {
    "id": "simple-tasks",
    "label": "Simple task manager",
    "description": "The smallest way to start: a Kanban task board with a few example cards, nothing else. No sprints, no ceremonies, no governance — just a to-do board you can start using immediately, and grow into more later.",
    "methodology": "kanban",
    "referenceRuleset": "kanban",
    "projectTemplate": "kanban-starter",
    "dashboardPreset": "project-manager-today",
    "tags": [
      "kanban",
      "starter",
      "simple"
    ],
    "order": 1
  }
];
