/* GENERATED by scripts/src/gen-presets.ts — do not edit.
   Presets are authored as JSON under lib/backend-catalogue/assets/presets/;
   run `pnpm --filter @workspace/scripts run gen-presets` to regenerate. */
import type { Preset } from "./preset-catalogue";

export const PRESETS_DATA: Preset[] = [
  {
    "id": "scrum-team",
    "label": "Scrum team",
    "description": "A sprint-ready Scrum setup: the Scrum methodology curated in, its reference ruleset applied, and a starter sprint project seeded with the ceremonies as work items — so a new team lands on a working board, backlog, burndown and velocity in one step.",
    "methodology": "scrum",
    "settingsPreset": "growth-business",
    "referenceRuleset": "scrum",
    "projectTemplate": "scrum-starter",
    "dashboardPreset": "project-manager-today",
    "tags": [
      "agile",
      "scrum"
    ],
    "order": 10
  }
];
