/* GENERATED by scripts/src/gen-reports.ts — do not edit.
   Reports are authored as JSON under lib/backend-catalogue/assets/reports/;
   run `pnpm --filter @workspace/scripts run gen-reports` to regenerate. */
import type { ReportDefinition } from "./report-catalogue";

export const REPORTS_DATA: ReportDefinition[] = [
  {
    "id": "burndown",
    "label": "Sprint burndown",
    "docsUrl": "",
    "kind": "progress",
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "remainingWork",
      "idealLine",
      "scopeChange"
    ],
    "notes": "Remaining work vs the ideal line over a sprint.",
    "order": 20,
    "methodologies": [
      "scrum",
      "scrumban",
      "safe"
    ]
  },
  {
    "id": "burnup",
    "label": "Burnup",
    "docsUrl": "",
    "kind": "progress",
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "completed",
      "scope"
    ],
    "notes": "Completed vs total scope (shows scope creep).",
    "order": 30,
    "methodologies": [
      "scrum",
      "safe"
    ]
  },
  {
    "id": "cumulative-flow",
    "label": "Cumulative flow",
    "docsUrl": "",
    "kind": "progress",
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "wipByState",
      "throughput",
      "cycleTime"
    ],
    "notes": "WIP per state over time (Kanban).",
    "order": 40,
    "methodologies": [
      "kanban",
      "scrumban"
    ]
  },
  {
    "id": "evm",
    "label": "Earned Value (EVM)",
    "docsUrl": "",
    "kind": "financial",
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "PV",
      "EV",
      "AC",
      "CPI",
      "SPI",
      "EAC",
      "ETC",
      "BAC"
    ],
    "notes": "Cost/schedule performance — needs financials + baseline.",
    "order": 60,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "financial-summary",
    "label": "Financial summary",
    "docsUrl": "",
    "kind": "financial",
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "budget",
      "actualCost",
      "committed",
      "variance",
      "margin"
    ],
    "notes": "Budget vs actual vs committed.",
    "order": 70
  },
  {
    "id": "gantt",
    "label": "Gantt chart",
    "docsUrl": "",
    "kind": "schedule",
    "capabilities": {
      "requiresCapability": "scheduling",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "startDate",
      "dueDate",
      "dependencies",
      "criticalPath",
      "baseline"
    ],
    "notes": "Schedule with dependencies + critical path.",
    "order": 10,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "portfolio-rag",
    "label": "Portfolio RAG",
    "docsUrl": "",
    "kind": "portfolio",
    "capabilities": {
      "requiresCapability": "portfolio",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "ragStatus",
      "scheduleVariance",
      "costVariance",
      "health"
    ],
    "notes": "Red/amber/green health across the portfolio.",
    "order": 90
  },
  {
    "id": "raid-register",
    "label": "RAID register",
    "docsUrl": "",
    "kind": "quality",
    "capabilities": {
      "requiresCapability": "raid",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "risks",
      "assumptions",
      "issues",
      "dependencies"
    ],
    "notes": "Risks, assumptions, issues, dependencies.",
    "order": 100
  },
  {
    "id": "resource-histogram",
    "label": "Resource histogram",
    "docsUrl": "",
    "kind": "resource",
    "capabilities": {
      "requiresCapability": "resources",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "allocated",
      "available",
      "overAllocation"
    ],
    "notes": "Allocation vs capacity per resource.",
    "order": 80
  },
  {
    "id": "velocity",
    "label": "Velocity",
    "docsUrl": "",
    "kind": "progress",
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "pointsPerSprint",
      "rollingAverage"
    ],
    "notes": "Story points completed per sprint.",
    "order": 50,
    "methodologies": [
      "scrum",
      "scrumban",
      "safe"
    ]
  }
];
