/* GENERATED by scripts/src/gen-reports.ts — do not edit.
   Reports are authored as JSON under lib/backend-catalogue/assets/reports/;
   run `pnpm --filter @workspace/scripts run gen-reports` to regenerate. */
import type { ReportDefinition } from "./report-catalogue";

export const REPORTS_DATA: ReportDefinition[] = [
  {
    "id": "benefits-realisation",
    "label": "Benefits Realisation",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "BenefitsRealisation"
    },
    "capabilities": {
      "requiresCapability": null,
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "benefitPlanned",
      "benefitActual",
      "realisation"
    ],
    "notes": "Planned-vs-realised benefits roll-up from benefit* fields. Stateless.",
    "order": 101,
    "methodologies": [
      "prince2"
    ]
  },
  {
    "id": "benefits-realisation-rollup",
    "label": "Portfolio Benefits Realisation",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "BenefitsRealisationRollup"
    },
    "capabilities": {
      "requiresCapability": null,
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "benefitPlanned",
      "benefitActual",
      "realisation"
    ],
    "notes": "Portfolio realisation lens over planned-vs-realised benefits. Stateless.",
    "order": 102
  },
  {
    "id": "burndown",
    "label": "Sprint burndown",
    "docsUrl": "",
    "kind": "progress",
    "renderer": {
      "engine": "builtin",
      "component": "Burndown"
    },
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "remainingWork",
      "idealLine",
      "scopeChange"
    ],
    "notes": "Remaining work vs the ideal line over a sprint.",
    "order": 20,
    "refresh": 120,
    "methodologies": [
      "scrum",
      "scrumban",
      "safe"
    ]
  },
  {
    "id": "burnup",
    "label": "Burnup",
    "docsUrl": "",
    "kind": "progress",
    "renderer": {
      "engine": "builtin",
      "component": "Burnup"
    },
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "completed",
      "scope"
    ],
    "notes": "Completed vs total scope (shows scope creep).",
    "order": 30,
    "methodologies": [
      "scrum",
      "safe"
    ]
  },
  {
    "id": "capacity-rollup",
    "label": "Capacity Roll-up",
    "docsUrl": "",
    "kind": "resource",
    "renderer": {
      "engine": "builtin",
      "component": "CapacityRollup"
    },
    "capabilities": {
      "requiresCapability": "resources",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "assignedHours",
      "availableHours",
      "utilisation",
      "overAllocation"
    ],
    "notes": "Programme and portfolio resource utilisation, aggregated across each project's capacity. For programme managers (their programmes) and the PMO (the whole portfolio).",
    "order": 35
  },
  {
    "id": "capex-opex",
    "label": "CapEx / OpEx",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "CapexOpex"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "capex",
      "opex",
      "split"
    ],
    "notes": "Splits project spend into capital vs operating. Stateless.",
    "order": 76
  },
  {
    "id": "critical-path",
    "label": "Critical Path (CPM)",
    "docsUrl": "",
    "kind": "schedule",
    "renderer": {
      "engine": "builtin",
      "component": "CriticalPath"
    },
    "capabilities": {
      "requiresCapability": "scheduling",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "dependsOn",
      "criticalPath",
      "slack"
    ],
    "notes": "CPM critical path, derived live from dependencies and dates. Stateless.",
    "order": 12,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "cross-programme-dependencies",
    "label": "Cross-programme Dependencies",
    "docsUrl": "",
    "kind": "schedule",
    "renderer": {
      "engine": "builtin",
      "component": "CrossProgrammeDependencies"
    },
    "capabilities": {
      "requiresCapability": "scheduling",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "dependsOn",
      "parentTask",
      "programmeId",
      "criticalPath",
      "crossProgrammeEdges"
    ],
    "notes": "Cross-programme dependency graph + critical path, derived live from depends-on links and dates. Stateless.",
    "order": 15,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "cumulative-flow",
    "label": "Cumulative flow",
    "docsUrl": "",
    "kind": "progress",
    "renderer": {
      "engine": "builtin",
      "component": "CumulativeFlow"
    },
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "wipByState",
      "throughput",
      "cycleTime"
    ],
    "notes": "WIP per state over time (Kanban).",
    "order": 40,
    "methodologies": [
      "kanban",
      "scrumban"
    ]
  },
  {
    "id": "demand-intake",
    "label": "Demand Intake",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "DemandIntake"
    },
    "capabilities": {
      "requiresCapability": "portfolio",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "status",
      "requester",
      "riceScore",
      "wsjf",
      "moscow",
      "strategicContribution"
    ],
    "notes": "Demand / intake funnel with prioritisation: treats every work item as a unit of demand and flows it through the intake funnel derived from status (backlog / idea → triaged → approved → in delivery → done), then ranks the top live requests by RICE / WSJF / MoSCoW with requester + strategic contribution — answering what is asking for the portfolio's capacity, where it sits in the pipeline, and what to pull next. Portfolio demand roll-up, derived live.",
    "order": 73
  },
  {
    "id": "dependency-links",
    "label": "Dependency Links",
    "docsUrl": "",
    "kind": "schedule",
    "renderer": {
      "engine": "builtin",
      "component": "DependencyLinks"
    },
    "capabilities": {
      "requiresCapability": "scheduling",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "dependsOn",
      "crossSystem"
    ],
    "notes": "Cross-system dependency links by opaque hash. Stateless.",
    "order": 16,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "evm",
    "label": "Earned Value (EVM)",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "FinancialEvmChart"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "PV",
      "EV",
      "AC",
      "CPI",
      "SPI",
      "EAC",
      "ETC",
      "BAC"
    ],
    "notes": "Cost/schedule performance — needs financials + baseline.",
    "order": 60,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "exec-board-pack",
    "label": "Executive Board Pack",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "ExecBoardPack"
    },
    "capabilities": {
      "requiresCapability": null,
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "health",
      "financials",
      "risk",
      "milestones"
    ],
    "notes": "Consolidated board-ready portfolio view. Stateless.",
    "order": 5
  },
  {
    "id": "federated-portfolio",
    "label": "Federated Portfolio (cross-instance)",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "FederatedPortfolio"
    },
    "capabilities": {
      "requiresCapability": "portfolio",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "localSummary",
      "peerSummaries",
      "peerStatus"
    ],
    "notes": "Consolidated global view across every OmniProject instance configured as a federated peer (backlog #135) — typically one per region/subsidiary under per-country data residency. Merges THIS instance's own portfolio-total aggregate with each peer's, fetched live, clearly labeled by peer/region and never blended into one number. Only pre-aggregated totals ever cross an instance boundary; an unreachable/misconfigured peer shows as unavailable rather than failing the whole view. See docs/DATA-RESIDENCY.md.",
    "order": 91
  },
  {
    "id": "financial-summary",
    "label": "Financial summary",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "FinancialSummary"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "budget",
      "actualCost",
      "committed",
      "variance",
      "margin"
    ],
    "notes": "Budget vs actual vs committed.",
    "order": 70
  },
  {
    "id": "forecast-windows",
    "label": "Forecast Windows",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "ForecastWindows"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "budget",
      "forecast",
      "sCurve"
    ],
    "notes": "Time-phased budget S-curve for forecasting. Stateless.",
    "order": 77
  },
  {
    "id": "gantt",
    "label": "Gantt chart",
    "docsUrl": "",
    "kind": "schedule",
    "renderer": {
      "engine": "builtin",
      "surfacedVia": "view",
      "reason": "rendered as the Gantt board view, not a Reports-page card"
    },
    "capabilities": {
      "requiresCapability": "scheduling",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "startDate",
      "dueDate",
      "dependencies",
      "criticalPath",
      "baseline"
    ],
    "notes": "Schedule with dependencies + critical path.",
    "order": 10,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "income-invoicing",
    "label": "Income & Invoicing",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "IncomeInvoicing"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "revenue",
      "invoicedAmount",
      "purchaseOrder",
      "unbilled"
    ],
    "notes": "Projected income (revenue) vs actually invoiced (invoicedAmount) per work item, with the unbilled gap and purchase-order references. Stateless, derived from the financial field group.",
    "order": 74
  },
  {
    "id": "monte-carlo-risk",
    "label": "Monte Carlo Risk",
    "docsUrl": "",
    "kind": "quality",
    "renderer": {
      "engine": "builtin",
      "component": "MonteCarloRisk"
    },
    "capabilities": {
      "requiresCapability": null,
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "p50",
      "p80",
      "confidence"
    ],
    "notes": "Monte Carlo schedule/effort risk simulation. Stateless.",
    "order": 105
  },
  {
    "id": "portfolio-benefits",
    "label": "Portfolio Benefits",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioBenefits"
    },
    "capabilities": {
      "requiresCapability": "benefits",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "plannedBenefitValue",
      "actualBenefitValue",
      "benefitConfidence",
      "fxRates"
    ],
    "notes": "Planned vs realised benefit value across every project, consolidated into one reporting currency and grouped by programme (worst realisation first). Portfolio benefits roll-up.",
    "order": 36
  },
  {
    "id": "portfolio-financials",
    "label": "Portfolio Financials (consolidated)",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioFinancials"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "budget",
      "actualCost",
      "forecastCostAtCompletion",
      "variance",
      "cpi",
      "fxRates"
    ],
    "notes": "Budget vs actual vs forecast across the whole portfolio, every project's local currency consolidated into one reporting currency via the broker FX table, rolled up by programme. For the PMO / head of projects at multi-country scale.",
    "order": 72
  },
  {
    "id": "portfolio-income",
    "label": "Portfolio Income",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioIncome"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "revenue",
      "invoicedAmount",
      "unbilled",
      "fxRates"
    ],
    "notes": "Projected income vs invoiced across every project, consolidated into one reporting currency and grouped by programme. Portfolio billing view for the PMO / head of projects.",
    "order": 73
  },
  {
    "id": "portfolio-prioritisation",
    "label": "Portfolio Prioritisation & Funding Funnel",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioPrioritisation"
    },
    "capabilities": {
      "requiresCapability": "portfolio",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "riceScore",
      "wsjf",
      "moscow",
      "strategicContribution",
      "plannedBenefitValue",
      "benefitConfidence",
      "budgetAllocated",
      "assignedHours"
    ],
    "notes": "Ranks every project on a weighted composite of RICE, WSJF, MoSCoW, strategic-goal contribution and risk-adjusted benefit value, shown against cost + capacity, with a fund/defer/cut what-if scenario (budget/capacity/benefit impact). Weights are PMO-configurable; the score is always computed live, never stored.",
    "order": 73
  },
  {
    "id": "portfolio-rag",
    "label": "Portfolio RAG",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioKpi"
    },
    "capabilities": {
      "requiresCapability": "portfolio",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "ragStatus",
      "scheduleVariance",
      "costVariance",
      "health"
    ],
    "notes": "Red/amber/green health across the portfolio.",
    "order": 90
  },
  {
    "id": "portfolio-roadmap",
    "label": "Portfolio Roadmap",
    "docsUrl": "",
    "kind": "schedule",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioRoadmap"
    },
    "capabilities": {
      "requiresCapability": "scheduling",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "start",
      "end",
      "progress"
    ],
    "notes": "Project bars on a timeline, derived from work-item dates. Stateless.",
    "order": 11,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "portfolio-trends",
    "label": "Portfolio Trends",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioTrends"
    },
    "capabilities": {
      "requiresCapability": null,
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "history",
      "trend"
    ],
    "notes": "Portfolio trends from point-in-time snapshots. Stateless.",
    "order": 111
  },
  {
    "id": "project-health",
    "label": "Project Health",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "ProjectHealth"
    },
    "capabilities": {
      "requiresCapability": "portfolio",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "status",
      "dueDate",
      "healthStatus",
      "riskLevel",
      "blocked",
      "blockedReason",
      "budget",
      "actualCost",
      "benefitConfidence"
    ],
    "notes": "Predictive project-health / risk scoring: derives a composite 0-100 health score and RAG band per project from the delivery-risk signals its work items carry — RAG health status, risk level, blocked flags, schedule slip (overdue open items), budget burn running ahead of delivery, benefit confidence and the open-vs-done ratio. Shows a RAG heatmap distribution, an at-risk ranking (worst first, with the driving factors) and portfolio red/amber/green + mean-health StatCards. Portfolio risk roll-up, derived live; nothing is stored.",
    "order": 72
  },
  {
    "id": "project-trend",
    "label": "Project Trend",
    "docsUrl": "",
    "kind": "progress",
    "renderer": {
      "engine": "builtin",
      "component": "ProjectTrend"
    },
    "capabilities": {
      "requiresCapability": null,
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "history",
      "trend"
    ],
    "notes": "Point-in-time history trend for a project. Stateless.",
    "order": 55
  },
  {
    "id": "raid-register",
    "label": "RAID register",
    "docsUrl": "",
    "kind": "quality",
    "renderer": {
      "engine": "builtin",
      "component": "RaidRegister"
    },
    "capabilities": {
      "requiresCapability": "raid",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "risks",
      "assumptions",
      "issues",
      "dependencies"
    ],
    "notes": "Risks, assumptions, issues, dependencies.",
    "order": 100
  },
  {
    "id": "resource-histogram",
    "label": "Resource histogram",
    "docsUrl": "",
    "kind": "resource",
    "renderer": {
      "engine": "builtin",
      "component": "ResourceHeatmap"
    },
    "capabilities": {
      "requiresCapability": "resources",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "allocated",
      "available",
      "overAllocation"
    ],
    "notes": "Allocation vs capacity per resource.",
    "order": 80
  },
  {
    "id": "resource-levelling",
    "label": "Cross-programme Resource Levelling",
    "docsUrl": "",
    "kind": "resource",
    "renderer": {
      "engine": "builtin",
      "component": "ResourceLevelling"
    },
    "capabilities": {
      "requiresCapability": "resources",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "totalAllocationPercentage",
      "crossProgramme",
      "crossCountry",
      "skillsSupplyDemand",
      "simulateMove",
      "residencyGate"
    ],
    "notes": "Portfolio-level resource levelling on top of the capacity roll-up: over/under-allocated people across programme AND country boundaries, skills supply-vs-demand, and a what-if move action with before/after over/under-allocation deltas. Cross-border moves are gated by the same data-residency policy the broker/egress hop enforces.",
    "order": 37
  },
  {
    "id": "scenario-sandbox",
    "label": "Scenario What-if",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "ScenarioSandbox"
    },
    "capabilities": {
      "requiresCapability": null,
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "include",
      "budgetCap",
      "priority"
    ],
    "notes": "Model include/exclude project sets under a constraint. Forked local state, nothing written back.",
    "order": 110
  },
  {
    "id": "schedule-sandbox",
    "label": "Schedule What-if",
    "docsUrl": "",
    "kind": "schedule",
    "renderer": {
      "engine": "builtin",
      "component": "ScheduleSandbox"
    },
    "capabilities": {
      "requiresCapability": "scheduling",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "shift",
      "dependsOn",
      "slack"
    ],
    "notes": "Drag a work package and watch downstream dates shift. Forked local state, nothing written back.",
    "order": 13,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "staff-cost",
    "label": "Staff Time & Cost",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "StaffTimeCost"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "loggedHours",
      "rateCard",
      "trueCost",
      "chargeToCustomer",
      "margin",
      "overhead"
    ],
    "notes": "Server-side staff time-and-cost roll-up (PMO-gated). Rates resolve in-memory from the hashed rate card and never reach the client; returns aggregated true cost, cost-to-customer and gross margin.",
    "order": 75
  },
  {
    "id": "strategy-alignment",
    "label": "Strategy Alignment",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "StrategyAlignment"
    },
    "capabilities": {
      "requiresCapability": "portfolio",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "strategicTheme",
      "strategicGoals",
      "strategicContribution",
      "objectives",
      "kpis",
      "plannedBenefitValue",
      "actualBenefitValue",
      "benefitStatus",
      "healthStatus"
    ],
    "notes": "Strategy-to-execution / OKR alignment roll-up: groups every work item by its strategic theme (or strategic goal), and shows per theme the average strategic contribution, planned vs realised benefit value, and a RAG health rollup — answering which strategic objectives the portfolio is investing in and how they are tracking. Portfolio strategy roll-up, derived live.",
    "order": 71
  },
  {
    "id": "utilisation",
    "label": "Utilisation",
    "docsUrl": "",
    "kind": "resource",
    "renderer": {
      "engine": "builtin",
      "component": "Utilisation"
    },
    "capabilities": {
      "requiresCapability": "resources",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "assignee",
      "loggedHours",
      "estimateHours",
      "remainingHours",
      "billable"
    ],
    "notes": "Per-assignee utilisation from timesheets: rolls work items up by assignee and shows logged vs estimate vs remaining effort, a billable/non-billable split, and a utilisation % (logged vs a nominal period capacity) with overload / under-utilised flags. Resource utilisation roll-up, derived live.",
    "order": 74
  },
  {
    "id": "value-stream",
    "label": "Value Stream Flow",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "ValueStreamFlow"
    },
    "capabilities": {
      "requiresCapability": "portfolio",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "valueStream",
      "status",
      "labels",
      "startDate",
      "dueDate",
      "createdAt",
      "updatedAt",
      "storyPoints"
    ],
    "notes": "Value-stream / flow-metrics roll-up: groups every work item by its value stream (or first label), and shows per stream the WIP (in-progress count), flow load (story points in flight), aging of in-progress work, throughput (items finished in the recent window) and mean cycle time — answering where work is piling up, how old the in-flight work is, and how fast each value stream is finishing. Portfolio flow roll-up, derived live.",
    "order": 75
  },
  {
    "id": "velocity",
    "label": "Velocity",
    "docsUrl": "",
    "kind": "progress",
    "renderer": {
      "engine": "builtin",
      "component": "Velocity"
    },
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "pointsPerSprint",
      "rollingAverage"
    ],
    "notes": "Story points completed per sprint.",
    "order": 50,
    "methodologies": [
      "scrum",
      "scrumban",
      "safe"
    ]
  }
];
