/* GENERATED by scripts/src/gen-reports.ts — do not edit.
   Reports are authored as JSON under lib/backend-catalogue/assets/reports/;
   run `pnpm --filter @workspace/scripts run gen-reports` to regenerate. */
import type { ReportDefinition } from "./report-catalogue";

export const REPORTS_DATA: ReportDefinition[] = [
  {
    "id": "burndown",
    "label": "Sprint burndown",
    "docsUrl": "",
    "kind": "progress",
    "renderer": {
      "engine": "builtin",
      "component": "Burndown"
    },
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "remainingWork",
      "idealLine",
      "scopeChange"
    ],
    "notes": "Remaining work vs the ideal line over a sprint.",
    "order": 20,
    "methodologies": [
      "scrum",
      "scrumban",
      "safe"
    ]
  },
  {
    "id": "burnup",
    "label": "Burnup",
    "docsUrl": "",
    "kind": "progress",
    "renderer": {
      "engine": "builtin",
      "component": "Burnup"
    },
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "completed",
      "scope"
    ],
    "notes": "Completed vs total scope (shows scope creep).",
    "order": 30,
    "methodologies": [
      "scrum",
      "safe"
    ]
  },
  {
    "id": "capacity-rollup",
    "label": "Capacity Roll-up",
    "docsUrl": "",
    "kind": "resource",
    "renderer": {
      "engine": "builtin",
      "component": "CapacityRollup"
    },
    "capabilities": {
      "requiresCapability": "resources",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "assignedHours",
      "availableHours",
      "utilisation",
      "overAllocation"
    ],
    "notes": "Programme and portfolio resource utilisation, aggregated across each project's capacity. For programme managers (their programmes) and the PMO (the whole portfolio).",
    "order": 35
  },
  {
    "id": "cross-programme-dependencies",
    "label": "Cross-programme Dependencies",
    "docsUrl": "",
    "kind": "schedule",
    "renderer": {
      "engine": "builtin",
      "component": "CrossProgrammeDependencies"
    },
    "capabilities": {
      "requiresCapability": "scheduling",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "dependsOn",
      "parentTask",
      "programmeId",
      "criticalPath",
      "crossProgrammeEdges"
    ],
    "notes": "Cross-programme dependency graph + critical path, derived live from depends-on links and dates. Stateless.",
    "order": 15,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "cumulative-flow",
    "label": "Cumulative flow",
    "docsUrl": "",
    "kind": "progress",
    "renderer": {
      "engine": "builtin",
      "component": "CumulativeFlow"
    },
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "wipByState",
      "throughput",
      "cycleTime"
    ],
    "notes": "WIP per state over time (Kanban).",
    "order": 40,
    "methodologies": [
      "kanban",
      "scrumban"
    ]
  },
  {
    "id": "evm",
    "label": "Earned Value (EVM)",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "FinancialEvmChart"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "PV",
      "EV",
      "AC",
      "CPI",
      "SPI",
      "EAC",
      "ETC",
      "BAC"
    ],
    "notes": "Cost/schedule performance — needs financials + baseline.",
    "order": 60,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "financial-summary",
    "label": "Financial summary",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "FinancialSummary"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "budget",
      "actualCost",
      "committed",
      "variance",
      "margin"
    ],
    "notes": "Budget vs actual vs committed.",
    "order": 70
  },
  {
    "id": "gantt",
    "label": "Gantt chart",
    "docsUrl": "",
    "kind": "schedule",
    "renderer": {
      "engine": "builtin",
      "surfacedVia": "view",
      "reason": "rendered as the Gantt board view, not a Reports-page card"
    },
    "capabilities": {
      "requiresCapability": "scheduling",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "startDate",
      "dueDate",
      "dependencies",
      "criticalPath",
      "baseline"
    ],
    "notes": "Schedule with dependencies + critical path.",
    "order": 10,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "income-invoicing",
    "label": "Income & Invoicing",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "IncomeInvoicing"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "revenue",
      "invoicedAmount",
      "purchaseOrder",
      "unbilled"
    ],
    "notes": "Projected income (revenue) vs actually invoiced (invoicedAmount) per work item, with the unbilled gap and purchase-order references. Stateless, derived from the financial field group.",
    "order": 74
  },
  {
    "id": "portfolio-benefits",
    "label": "Portfolio Benefits",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioBenefits"
    },
    "capabilities": {
      "requiresCapability": "benefits",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "plannedBenefitValue",
      "actualBenefitValue",
      "benefitConfidence",
      "fxRates"
    ],
    "notes": "Planned vs realised benefit value across every project, consolidated into one reporting currency and grouped by programme (worst realisation first). Portfolio benefits roll-up.",
    "order": 36
  },
  {
    "id": "portfolio-financials",
    "label": "Portfolio Financials (consolidated)",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioFinancials"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "budget",
      "actualCost",
      "forecastCostAtCompletion",
      "variance",
      "cpi",
      "fxRates"
    ],
    "notes": "Budget vs actual vs forecast across the whole portfolio, every project's local currency consolidated into one reporting currency via the broker FX table, rolled up by programme. For the PMO / head of projects at multi-country scale.",
    "order": 72
  },
  {
    "id": "portfolio-income",
    "label": "Portfolio Income",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioIncome"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "revenue",
      "invoicedAmount",
      "unbilled",
      "fxRates"
    ],
    "notes": "Projected income vs invoiced across every project, consolidated into one reporting currency and grouped by programme. Portfolio billing view for the PMO / head of projects.",
    "order": 73
  },
  {
    "id": "portfolio-prioritisation",
    "label": "Portfolio Prioritisation & Funding Funnel",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioPrioritisation"
    },
    "capabilities": {
      "requiresCapability": "portfolio",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "riceScore",
      "wsjf",
      "moscow",
      "strategicContribution",
      "plannedBenefitValue",
      "benefitConfidence",
      "budgetAllocated",
      "assignedHours"
    ],
    "notes": "Ranks every project on a weighted composite of RICE, WSJF, MoSCoW, strategic-goal contribution and risk-adjusted benefit value, shown against cost + capacity, with a fund/defer/cut what-if scenario (budget/capacity/benefit impact). Weights are PMO-configurable; the score is always computed live, never stored.",
    "order": 73
  },
  {
    "id": "portfolio-rag",
    "label": "Portfolio RAG",
    "docsUrl": "",
    "kind": "portfolio",
    "renderer": {
      "engine": "builtin",
      "component": "PortfolioKpi"
    },
    "capabilities": {
      "requiresCapability": "portfolio",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "ragStatus",
      "scheduleVariance",
      "costVariance",
      "health"
    ],
    "notes": "Red/amber/green health across the portfolio.",
    "order": 90
  },
  {
    "id": "raid-register",
    "label": "RAID register",
    "docsUrl": "",
    "kind": "quality",
    "renderer": {
      "engine": "builtin",
      "component": "RaidRegister"
    },
    "capabilities": {
      "requiresCapability": "raid",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "risks",
      "assumptions",
      "issues",
      "dependencies"
    ],
    "notes": "Risks, assumptions, issues, dependencies.",
    "order": 100
  },
  {
    "id": "resource-histogram",
    "label": "Resource histogram",
    "docsUrl": "",
    "kind": "resource",
    "renderer": {
      "engine": "builtin",
      "component": "ResourceHeatmap"
    },
    "capabilities": {
      "requiresCapability": "resources",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "allocated",
      "available",
      "overAllocation"
    ],
    "notes": "Allocation vs capacity per resource.",
    "order": 80
  },
  {
    "id": "resource-levelling",
    "label": "Cross-programme Resource Levelling",
    "docsUrl": "",
    "kind": "resource",
    "renderer": {
      "engine": "builtin",
      "component": "ResourceLevelling"
    },
    "capabilities": {
      "requiresCapability": "resources",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "totalAllocationPercentage",
      "crossProgramme",
      "crossCountry",
      "skillsSupplyDemand",
      "simulateMove",
      "residencyGate"
    ],
    "notes": "Portfolio-level resource levelling on top of the capacity roll-up: over/under-allocated people across programme AND country boundaries, skills supply-vs-demand, and a what-if move action with before/after over/under-allocation deltas. Cross-border moves are gated by the same data-residency policy the broker/egress hop enforces.",
    "order": 37
  },
  {
    "id": "staff-cost",
    "label": "Staff Time & Cost",
    "docsUrl": "",
    "kind": "financial",
    "renderer": {
      "engine": "builtin",
      "component": "StaffTimeCost"
    },
    "capabilities": {
      "requiresCapability": "financials",
      "timeSeries": false,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "loggedHours",
      "rateCard",
      "trueCost",
      "chargeToCustomer",
      "margin",
      "overhead"
    ],
    "notes": "Server-side staff time-and-cost roll-up (PMO-gated). Rates resolve in-memory from the hashed rate card and never reach the client; returns aggregated true cost, cost-to-customer and gross margin.",
    "order": 75
  },
  {
    "id": "velocity",
    "label": "Velocity",
    "docsUrl": "",
    "kind": "progress",
    "renderer": {
      "engine": "builtin",
      "component": "Velocity"
    },
    "capabilities": {
      "requiresCapability": "history",
      "timeSeries": true,
      "exports": [
        "csv",
        "pdf",
        "png"
      ]
    },
    "tools": [
      "pointsPerSprint",
      "rollingAverage"
    ],
    "notes": "Story points completed per sprint.",
    "order": 50,
    "methodologies": [
      "scrum",
      "scrumban",
      "safe"
    ]
  }
];
