/* GENERATED by scripts/src/gen-screens.ts — do not edit.
   Screens are authored as JSON under lib/backend-catalogue/assets/screens/;
   run `pnpm --filter @workspace/scripts run gen-screens` to regenerate. */
import type { ScreenDefinition } from "./screen-catalogue";

export const SCREENS_DATA: ScreenDefinition[] = [
  {
    "id": "gantt",
    "label": "Gantt / schedule",
    "route": "/projects/:id/gantt",
    "kind": "planning",
    "capabilities": {
      "requiresRole": "contributor",
      "requiresCapability": "scheduling",
      "dataLineage": true,
      "exportable": true
    },
    "tools": [
      "gantt-bars",
      "drag-reschedule",
      "dependencies",
      "what-if"
    ],
    "notes": "Schedule + drag-to-reschedule (write-through).",
    "order": 50,
    "methodologies": [
      "waterfall",
      "prince2"
    ]
  },
  {
    "id": "home",
    "label": "Home",
    "route": "/",
    "kind": "dashboard",
    "capabilities": {
      "requiresRole": "viewer",
      "requiresCapability": null,
      "dataLineage": true,
      "exportable": true
    },
    "tools": [
      "activity-feed",
      "my-work",
      "portfolio-summary"
    ],
    "notes": "Landing dashboard.",
    "order": 10
  },
  {
    "id": "programme-detail",
    "label": "Programme detail",
    "route": "/programmes/:id",
    "kind": "detail",
    "capabilities": {
      "requiresRole": "viewer",
      "requiresCapability": "portfolio",
      "dataLineage": true,
      "exportable": true
    },
    "tools": [
      "project-list",
      "rollup",
      "financials"
    ],
    "notes": "A single programme.",
    "order": 30
  },
  {
    "id": "programmes",
    "label": "Programmes",
    "route": "/programmes",
    "kind": "dashboard",
    "capabilities": {
      "requiresRole": "viewer",
      "requiresCapability": "portfolio",
      "dataLineage": true,
      "exportable": true
    },
    "tools": [
      "programme-grid",
      "rag-rollup",
      "financial-rollup"
    ],
    "notes": "Programme-level portfolio.",
    "order": 20
  },
  {
    "id": "project-detail",
    "label": "Project detail",
    "route": "/projects/:id",
    "kind": "detail",
    "capabilities": {
      "requiresRole": "viewer",
      "requiresCapability": null,
      "dataLineage": true,
      "exportable": true
    },
    "tools": [
      "task-board",
      "summary",
      "members",
      "financials",
      "raid"
    ],
    "notes": "A single project + its work items.",
    "order": 40
  },
  {
    "id": "reports",
    "label": "Reports",
    "route": "/reports",
    "kind": "report",
    "capabilities": {
      "requiresRole": "viewer",
      "requiresCapability": null,
      "dataLineage": true,
      "exportable": true
    },
    "tools": [
      "report-picker",
      "evm",
      "portfolio-rag",
      "burndown"
    ],
    "notes": "Renders the REPORTS plane (capability-gated).",
    "order": 70
  },
  {
    "id": "resource-planning",
    "label": "Resource planning",
    "route": "/resources",
    "kind": "planning",
    "capabilities": {
      "requiresRole": "manager",
      "requiresCapability": "resources",
      "dataLineage": true,
      "exportable": true
    },
    "tools": [
      "capacity-grid",
      "what-if-allocation",
      "over-capacity"
    ],
    "notes": "Capacity vs allocation, what-if modelling.",
    "order": 60
  },
  {
    "id": "settings",
    "label": "Settings",
    "route": "/settings",
    "kind": "admin",
    "capabilities": {
      "requiresRole": "admin",
      "requiresCapability": null,
      "dataLineage": false,
      "exportable": false
    },
    "tools": [
      "broker-config",
      "translation-editor",
      "broker-log",
      "ruleset"
    ],
    "notes": "Admin configuration.",
    "order": 80
  }
];
