/* GENERATED by scripts/src/gen-settings-presets.ts — do not edit.
   Settings presets are authored as JSON under lib/backend-catalogue/assets/settings-presets/;
   run `pnpm --filter @workspace/scripts run gen-settings-presets` to regenerate. */
import type { SettingsPreset } from "./settings-preset-catalogue";

export const SETTINGS_PRESETS_DATA: SettingsPreset[] = [
  {
    "id": "agency-services",
    "label": "Agency / Professional Services",
    "audience": "Agencies and consultancies running client-billable delivery",
    "description": "Client-billable delivery: budget-rate FX so margin isn't polluted by day-to-day drift, a value/benefit-weighted backlog, and the comments + grid collaboration modules to the fore.",
    "order": 40,
    "settings": {
      "deploymentProfile": "business",
      "reportingCurrency": "USD",
      "fxRatePolicy": "budgetRate",
      "aiProvider": "none",
      "sttProvider": "browser",
      "priorityWeights": {
        "rice": 20,
        "wsjf": 20,
        "moscow": 10,
        "strategic": 20,
        "benefit": 30
      }
    }
  },
  {
    "id": "demo-trial",
    "label": "Demo / Trial",
    "audience": "Evaluators exploring the product with the built-in demo data",
    "description": "Everything on for exploration: demo profile, default prioritisation, on-device speech. No reporting currency so FX stays out of the way until you're ready.",
    "order": 60,
    "settings": {
      "deploymentProfile": "demo",
      "reportingCurrency": null,
      "fxRatePolicy": "spot",
      "aiProvider": "none",
      "sttProvider": "browser"
    }
  },
  {
    "id": "enterprise-pmo",
    "label": "Enterprise PMO",
    "audience": "Large enterprises with a formal PMO and portfolio governance",
    "description": "Portfolio-grade rigour: enterprise profile, period-close FX for clean board-pack variance, and a strategy-weighted prioritisation. Governance controls are ready to layer on; AI stays off until you connect a provider.",
    "order": 10,
    "settings": {
      "deploymentProfile": "enterprise",
      "reportingCurrency": "USD",
      "fxRatePolicy": "periodClose",
      "aiProvider": "none",
      "sttProvider": "browser",
      "priorityWeights": {
        "rice": 15,
        "wsjf": 15,
        "moscow": 15,
        "strategic": 35,
        "benefit": 20
      }
    }
  },
  {
    "id": "growth-business",
    "label": "Growth Business",
    "audience": "Scaling companies delivering with agile squads",
    "description": "Velocity-first: business profile, live spot FX, and a RICE/WSJF-weighted backlog. Lean governance, all modules on so teams can adopt dashboards and integrations as they grow.",
    "order": 20,
    "settings": {
      "deploymentProfile": "business",
      "reportingCurrency": "USD",
      "fxRatePolicy": "spot",
      "aiProvider": "none",
      "sttProvider": "browser",
      "priorityWeights": {
        "rice": 35,
        "wsjf": 30,
        "moscow": 15,
        "strategic": 10,
        "benefit": 10
      }
    }
  },
  {
    "id": "nonprofit",
    "label": "Nonprofit / NGO",
    "audience": "Charities and NGOs focused on outcomes over throughput",
    "description": "Impact-led and lean: nonprofit profile, benefit/strategy-weighted prioritisation, and the heavier OData + external-integration modules switched off to keep the surface small. Turn them back on any time.",
    "order": 30,
    "settings": {
      "deploymentProfile": "nonprofit",
      "reportingCurrency": "USD",
      "fxRatePolicy": "spot",
      "aiProvider": "none",
      "sttProvider": "browser",
      "priorityWeights": {
        "rice": 15,
        "wsjf": 10,
        "moscow": 15,
        "strategic": 25,
        "benefit": 35
      },
      "disabledFeatures": [
        "odata",
        "integrations"
      ]
    }
  },
  {
    "id": "regulated-selfhost",
    "label": "Regulated / Self-hosted",
    "audience": "Regulated or air-gap-leaning orgs that self-host and minimise egress",
    "description": "Minimal external surface: self-hosted profile, on-device speech only, no external integrations, and period-close FX. AI stays off; enable a LOCAL provider (Ollama) if you want it without egress.",
    "order": 50,
    "settings": {
      "deploymentProfile": "self-hosted",
      "reportingCurrency": "USD",
      "fxRatePolicy": "periodClose",
      "aiProvider": "none",
      "sttProvider": "browser",
      "priorityWeights": {
        "rice": 20,
        "wsjf": 20,
        "moscow": 20,
        "strategic": 25,
        "benefit": 15
      },
      "disabledFeatures": [
        "integrations"
      ]
    }
  }
];
