/* GENERATED by scripts/src/gen-severity-vocabulary.ts — do not edit.
   Source: lib/backend-catalogue/assets/severity-vocabulary.json;
   run `pnpm --filter @workspace/scripts run gen-severity-vocabulary` to regenerate. */
import type { SeverityVocabEntry } from "./severity-vocabulary";

export const SEVERITY_VOCABULARY_DATA: SeverityVocabEntry[] = [
  {
    "id": "low",
    "label": "Low",
    "order": 0,
    "level": 1,
    "color": "#22c55e"
  },
  {
    "id": "medium",
    "label": "Medium",
    "order": 1,
    "level": 2,
    "color": "#f59e0b"
  },
  {
    "id": "high",
    "label": "High",
    "order": 2,
    "level": 3,
    "color": "#ef4444"
  },
  {
    "id": "critical",
    "label": "Critical",
    "order": 3,
    "level": 4,
    "color": "#b91c1c"
  }
];
