/* GENERATED by scripts/src/gen-task-vocabulary.ts — do not edit.
   Source: lib/backend-catalogue/assets/task-vocabulary.json;
   run `pnpm --filter @workspace/scripts run gen-task-vocabulary` to regenerate. */
import type { TaskVocabEntry } from "./task-vocabulary";

export const TASK_VOCABULARY_DATA: TaskVocabEntry[] = [
  {
    "id": "next",
    "label": "Next",
    "order": 0,
    "class": "actionable",
    "color": "#3b82f6"
  },
  {
    "id": "waiting",
    "label": "Waiting",
    "order": 1,
    "class": "waiting",
    "color": "#f59e0b"
  },
  {
    "id": "scheduled",
    "label": "Scheduled",
    "order": 2,
    "class": "deferred",
    "color": "#a855f7"
  },
  {
    "id": "someday",
    "label": "Someday",
    "order": 3,
    "class": "deferred",
    "color": "#71717a"
  },
  {
    "id": "done",
    "label": "Done",
    "order": 4,
    "class": "done",
    "color": "#22c55e"
  },
  {
    "id": "dropped",
    "label": "Dropped",
    "order": 5,
    "class": "dropped",
    "color": "#ef4444"
  }
];
