/* GENERATED by scripts/src/gen-templates.ts — do not edit.
   Project templates are authored as JSON under lib/backend-catalogue/assets/templates/;
   run `pnpm --filter @workspace/scripts run gen-templates` to regenerate. */
import type { ProjectTemplate } from "./template-catalogue";

export const PROJECT_TEMPLATES_DATA: ProjectTemplate[] = [
  {
    "id": "kanban-starter",
    "label": "Task board",
    "description": "A ready-to-use task board with a few example cards — the simplest way to start tracking work.",
    "methodology": "kanban",
    "methodologies": [
      "kanban",
      "agile"
    ],
    "project": {
      "description": "A simple task board created from a template."
    },
    "seedIssues": [
      {
        "title": "Add your first task",
        "status": "todo",
        "priority": "medium"
      },
      {
        "title": "Drag a card to In Progress",
        "status": "todo",
        "priority": "low",
        "labels": [
          "example"
        ]
      },
      {
        "title": "This one's in progress",
        "status": "in_progress",
        "priority": "low",
        "labels": [
          "example"
        ]
      },
      {
        "title": "And this one's done",
        "status": "done",
        "priority": "low",
        "labels": [
          "example"
        ]
      }
    ]
  },
  {
    "id": "prince2-starter",
    "label": "PRINCE2 project",
    "description": "A stage-gated project shell with the PRINCE2 management products as work items.",
    "methodology": "prince2",
    "methodologies": [
      "prince2",
      "governance"
    ],
    "project": {
      "description": "PRINCE2 project created from a template."
    },
    "seedIssues": [
      {
        "title": "Project Brief",
        "status": "todo",
        "priority": "high",
        "labels": [
          "initiation"
        ]
      },
      {
        "title": "Business Case",
        "status": "todo",
        "priority": "high",
        "labels": [
          "initiation"
        ]
      },
      {
        "title": "Stage 1 plan",
        "status": "todo",
        "priority": "medium"
      },
      {
        "title": "Risk register set-up",
        "status": "todo",
        "priority": "medium",
        "labels": [
          "raid"
        ]
      }
    ]
  },
  {
    "id": "scrum-starter",
    "label": "Scrum project",
    "description": "A sprint-ready backlog with the usual ceremonies as work items.",
    "methodology": "scrum",
    "methodologies": [
      "scrum",
      "agile"
    ],
    "project": {
      "description": "Scrum project created from a template."
    },
    "seedIssues": [
      {
        "title": "Sprint 0: set up the board & backlog",
        "status": "todo",
        "priority": "high",
        "labels": [
          "setup"
        ]
      },
      {
        "title": "Define the Definition of Done",
        "status": "todo",
        "priority": "medium"
      },
      {
        "title": "First sprint planning",
        "status": "todo",
        "priority": "medium"
      },
      {
        "title": "Backlog: sample user story",
        "status": "backlog",
        "priority": "low",
        "labels": [
          "story"
        ]
      }
    ]
  }
];
