/* GENERATED by scripts/src/gen-vendors.ts — do not edit.
   The per-plane vendor JSON Schemas, embedded for runtime validation. */
import type { JsonSchema } from "./vendor-schema";

export const VENDOR_SCHEMAS: Record<string, JsonSchema> = {
  "backends": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://omniproject.dev/vendors/backend.schema.json",
    "title": "OmniProject backend vendor",
    "description": "A system-of-record backend: the neutral manifest plus its n8n binding. One file per vendor under vendors/backends/<id>.json.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "label",
      "docsUrl",
      "primaryRecord",
      "verification",
      "via",
      "requiredEnv",
      "capabilities",
      "authHeader",
      "actions"
    ],
    "properties": {
      "id": {
        "type": "string",
        "pattern": "^[a-z0-9-]+$"
      },
      "label": {
        "type": "string"
      },
      "docsUrl": {
        "type": "string"
      },
      "primaryRecord": {
        "enum": [
          "issue",
          "invoice",
          "client",
          "product",
          "payment",
          "credit_note",
          "quote",
          "tax_rate",
          "vendor",
          "expense",
          "bill",
          "purchase_order",
          "gl_account",
          "journal_entry",
          "bank_account",
          "bank_transaction",
          "fx_rate",
          "fiscal_period",
          "dimension",
          "rev_rec_schedule",
          "goods_receipt",
          "fixed_asset",
          "dependency"
        ],
        "description": "The primary record this backend is a system of record for. Decides the required contract read verbs and which field superset applies — a backend need not be a project tool, but it must own a record type. \"issue\": PM/CRM/ITSM/ERP tools (normalised to the issue/project contract). \"invoice\": a billing system of record (Invoice Ninja, Dolibarr, …). \"client\": a customer master whose primary record is the bill-to party. \"product\": an item catalogue whose primary record is the priced line item. \"payment\": an AR-receipt system whose primary record is a settlement applied to invoices. \"credit_note\" / \"quote\": AR documents (a credit against an account, an estimate that precedes an invoice). \"tax_rate\": a jurisdiction's tax-rate table."
      },
      "verification": {
        "enum": [
          "verified",
          "catalogued",
          "experimental"
        ],
        "description": "How confident we are this manifest matches the vendor's real, live API. \"catalogued\": built from public docs, not yet run against a live instance. \"verified\": exercised end-to-end against a live instance. \"experimental\": speculative/partial, or a generic placeholder."
      },
      "via": {
        "type": "string",
        "description": "How this backend authenticates / is wired (human-readable, for the wizard)."
      },
      "requiredEnv": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "capabilities": {
        "type": "object",
        "additionalProperties": {
          "type": "boolean"
        }
      },
      "kind": {
        "enum": [
          "live",
          "import",
          "database"
        ]
      },
      "adminOnly": {
        "type": "boolean"
      },
      "notes": {
        "type": "string"
      },
      "credentialType": {
        "type": "string"
      },
      "keyFormat": {
        "type": "object",
        "additionalProperties": false,
        "description": "The shape of the key required to reach this vendor (used to hard-reject keyless access and to scaffold credentials).",
        "required": [
          "scheme"
        ],
        "properties": {
          "scheme": {
            "enum": [
              "psk",
              "bearer",
              "apiKey",
              "basic",
              "oauth2",
              "per-user",
              "none"
            ]
          },
          "env": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "header": {
            "type": "string"
          },
          "pattern": {
            "type": "string"
          }
        }
      },
      "nomenclature": {
        "type": "object",
        "description": "Canonical label-catalogue key → this vendor's preferred word (a one-click nomenclature preset).",
        "additionalProperties": {
          "type": "string"
        }
      },
      "fields": {
        "type": "array",
        "description": "Canonical fields this backend CONTRIBUTES to the superset (each validated against assets/schema/field.schema.json by gen-fields and merged in, dedup by key). Use when a backend exposes a field not yet in the registry.",
        "items": {
          "type": "object"
        }
      },
      "fieldKeys": {
        "type": "array",
        "description": "Canonical field keys this backend exposes/maps. MUST be a strict subset of the superset — enforced by the guard-superset CI check (a backend can only reference fields that exist).",
        "items": {
          "type": "string"
        }
      },
      "statusVocabulary": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "toCanonical"
        ],
        "description": "This vendor's native status dialect mapped to canonical statuses (data, below the seam).",
        "properties": {
          "toCanonical": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "fromCanonical": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      },
      "authHeader": {
        "type": "string",
        "description": "n8n expression for the per-user Authorization header value."
      },
      "actions": {
        "type": "object",
        "additionalProperties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "kind": {
              "enum": [
                "http",
                "n8nNode"
              ]
            },
            "method": {
              "enum": [
                "GET",
                "POST",
                "PATCH",
                "PUT",
                "DELETE"
              ]
            },
            "url": {
              "type": "string"
            },
            "body": {
              "type": "string"
            },
            "credentialType": {
              "type": "string"
            },
            "node": {
              "type": "string"
            },
            "typeVersion": {
              "type": "number"
            },
            "parameters": {
              "type": "object"
            },
            "note": {
              "type": "string"
            }
          }
        }
      },
      "invoiceSync": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "correlation",
          "env",
          "outbound",
          "inbound",
          "webhook"
        ],
        "description": "Advertised invoice-sync mapping applied by the gateway's generic projector (broker/backends/invoice-mapping) — maps OmniProject's agnostic invoice surface to/from this backend's billing API, both ways, as data. Only needed by a backend that reconciles an external settlement onto the local sealed invoice.",
        "properties": {
          "correlation": {
            "type": "object"
          },
          "env": {
            "type": "object"
          },
          "outbound": {
            "type": "object"
          },
          "inbound": {
            "type": "object"
          },
          "webhook": {
            "type": "object"
          }
        }
      }
    }
  },
  "brokers": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://omniproject.dev/vendors/broker.schema.json",
    "title": "OmniProject broker vendor",
    "description": "An automation/translation platform that drives a backend binding. One file per vendor under vendors/brokers/<id>.json.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "label",
      "docsUrl",
      "kind",
      "hosted",
      "capabilities",
      "transports",
      "build"
    ],
    "properties": {
      "id": {
        "type": "string",
        "pattern": "^[a-z0-9-]+$"
      },
      "label": {
        "type": "string"
      },
      "docsUrl": {
        "type": "string"
      },
      "kind": {
        "enum": [
          "low-code",
          "code-first",
          "serverless",
          "self-hosted-service"
        ]
      },
      "hosted": {
        "type": "boolean"
      },
      "capabilities": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "synchronous",
          "selfHostable",
          "managedAuth",
          "eventsInbound",
          "eventsOutbound"
        ],
        "properties": {
          "synchronous": {
            "type": "boolean",
            "enum": [
              true
            ],
            "description": "Brokers ARE the synchronous data-hop plane — every broker can answer the binding's request in the SAME HTTP call. Async-only platforms (Airflow/Zapier) belong in the outputs/notifications planes, not here."
          },
          "selfHostable": {
            "type": "boolean"
          },
          "managedAuth": {
            "type": "boolean"
          },
          "eventsInbound": {
            "type": "boolean"
          },
          "eventsOutbound": {
            "type": "boolean"
          }
        }
      },
      "transports": {
        "type": "array",
        "items": {
          "enum": [
            "http",
            "native-node"
          ]
        }
      },
      "build": {
        "enum": [
          "workflow-generator",
          "scenario-template",
          "component-template",
          "flow-template",
          "function-template",
          "implement-blueprint"
        ]
      },
      "notes": {
        "type": "string"
      },
      "reference": {
        "type": "boolean",
        "description": "The pre-selected, shipped-as-default broker in the picker UI (at most one vendor file should set this)."
      },
      "keyFormat": {
        "type": "object",
        "additionalProperties": false,
        "description": "The shape of the key required to reach this broker (used to hard-reject keyless access and to scaffold credentials).",
        "required": [
          "scheme"
        ],
        "properties": {
          "scheme": {
            "enum": [
              "psk",
              "bearer",
              "apiKey",
              "basic",
              "oauth2",
              "per-user",
              "none"
            ]
          },
          "env": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "Operator-side env var(s) the key lives in."
          },
          "header": {
            "type": "string",
            "description": "HTTP header the key is presented in, if any."
          },
          "pattern": {
            "type": "string",
            "description": "Optional regex the key value must match (its format)."
          }
        }
      },
      "alsoProvides": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "plane"
          ],
          "properties": {
            "plane": {
              "type": "string"
            },
            "note": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "notifications": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://omniproject.dev/vendors/notification.schema.json",
    "title": "OmniProject notification vendor",
    "description": "A channel alerts/events are delivered TO. One file per vendor under vendors/notifications/<id>.json.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "label",
      "docsUrl",
      "kind",
      "capabilities",
      "tools"
    ],
    "properties": {
      "id": {
        "type": "string",
        "pattern": "^[a-z0-9-]+$"
      },
      "label": {
        "type": "string"
      },
      "docsUrl": {
        "type": "string"
      },
      "kind": {
        "enum": [
          "chat",
          "email",
          "incident",
          "sms",
          "webhook",
          "iot",
          "agent"
        ]
      },
      "capabilities": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "channels",
          "directMessage",
          "richFormatting",
          "threads",
          "inboundReply",
          "delivery"
        ],
        "properties": {
          "channels": {
            "type": "boolean"
          },
          "directMessage": {
            "type": "boolean"
          },
          "richFormatting": {
            "type": "boolean"
          },
          "threads": {
            "type": "boolean"
          },
          "inboundReply": {
            "type": "boolean"
          },
          "delivery": {
            "enum": [
              "incoming-webhook",
              "oauth-app",
              "api-key",
              "smtp",
              "hmac-webhook",
              "mqtt",
              "mcp"
            ]
          }
        }
      },
      "tools": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "notes": {
        "type": "string"
      }
    }
  },
  "outputs": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://omniproject.dev/vendors/output.schema.json",
    "title": "OmniProject output vendor",
    "description": "An outward interface that exposes portfolio data/events. One file per vendor under vendors/outputs/<id>.json.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "label",
      "route",
      "kind",
      "capabilities",
      "tools"
    ],
    "properties": {
      "id": {
        "type": "string",
        "pattern": "^[a-z0-9-]+$"
      },
      "label": {
        "type": "string"
      },
      "route": {
        "type": "string"
      },
      "kind": {
        "enum": [
          "read-api",
          "bi-feed",
          "agent-api",
          "export",
          "metrics",
          "events-out",
          "events-in",
          "batch-egress",
          "calendar"
        ]
      },
      "capabilities": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "readOnly",
          "streaming",
          "auth"
        ],
        "properties": {
          "readOnly": {
            "type": "boolean"
          },
          "streaming": {
            "type": "boolean"
          },
          "auth": {
            "enum": [
              "session",
              "api-token",
              "session-or-token",
              "hmac",
              "user-action",
              "oauth2"
            ]
          }
        }
      },
      "transports": {
        "type": "array",
        "description": "Which connection methods OmniProject offers for this output (e.g. a calendar reachable via its REST API or an MCP server). Omitted when the output has a single implicit transport (its route).",
        "items": {
          "enum": [
            "api",
            "mcp",
            "ical-feed"
          ]
        }
      },
      "tools": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "methodologies": {
        "type": "array",
        "description": "Methodology TAGS this output belongs to (\"*\" or omitted = neutral / all). Admin/PMO-editable.",
        "items": {
          "type": "string"
        }
      },
      "notes": {
        "type": "string"
      }
    }
  }
};
