/* GENERATED by scripts/src/gen-vendors.ts — do not edit.
   The per-plane vendor JSON Schemas, embedded for runtime validation. */
import type { JsonSchema } from "./vendor-schema";

export const VENDOR_SCHEMAS: Record<string, JsonSchema> = {
  "backends": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://omniproject.dev/vendors/backend.schema.json",
    "title": "OmniProject backend vendor",
    "description": "A system-of-record backend: the neutral manifest plus its n8n binding. One file per vendor under vendors/backends/<id>.json.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "label",
      "docsUrl",
      "via",
      "requiredEnv",
      "capabilities",
      "authHeader",
      "actions"
    ],
    "properties": {
      "id": {
        "type": "string",
        "pattern": "^[a-z0-9-]+$"
      },
      "label": {
        "type": "string"
      },
      "docsUrl": {
        "type": "string"
      },
      "via": {
        "type": "string",
        "description": "How this backend authenticates / is wired (human-readable, for the wizard)."
      },
      "requiredEnv": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "capabilities": {
        "type": "object",
        "additionalProperties": {
          "type": "boolean"
        }
      },
      "kind": {
        "enum": [
          "live",
          "import",
          "database"
        ]
      },
      "adminOnly": {
        "type": "boolean"
      },
      "notes": {
        "type": "string"
      },
      "credentialType": {
        "type": "string"
      },
      "nomenclature": {
        "type": "object",
        "description": "Canonical label-catalogue key → this vendor's preferred word (a one-click nomenclature preset).",
        "additionalProperties": {
          "type": "string"
        }
      },
      "statusVocabulary": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "toCanonical"
        ],
        "description": "This vendor's native status dialect mapped to canonical statuses (data, below the seam).",
        "properties": {
          "toCanonical": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          },
          "fromCanonical": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            }
          }
        }
      },
      "authHeader": {
        "type": "string",
        "description": "n8n expression for the per-user Authorization header value."
      },
      "actions": {
        "type": "object",
        "additionalProperties": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "kind": {
              "enum": [
                "http",
                "n8nNode"
              ]
            },
            "method": {
              "enum": [
                "GET",
                "POST",
                "PATCH",
                "PUT",
                "DELETE"
              ]
            },
            "url": {
              "type": "string"
            },
            "body": {
              "type": "string"
            },
            "credentialType": {
              "type": "string"
            },
            "node": {
              "type": "string"
            },
            "typeVersion": {
              "type": "number"
            },
            "parameters": {
              "type": "object"
            },
            "note": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "brokers": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://omniproject.dev/vendors/broker.schema.json",
    "title": "OmniProject broker vendor",
    "description": "An automation/translation platform that drives a backend binding. One file per vendor under vendors/brokers/<id>.json.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "label",
      "docsUrl",
      "kind",
      "hosted",
      "capabilities",
      "transports",
      "build"
    ],
    "properties": {
      "id": {
        "type": "string",
        "pattern": "^[a-z0-9-]+$"
      },
      "label": {
        "type": "string"
      },
      "docsUrl": {
        "type": "string"
      },
      "kind": {
        "enum": [
          "low-code",
          "code-first",
          "serverless",
          "self-hosted-service"
        ]
      },
      "hosted": {
        "type": "boolean"
      },
      "capabilities": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "synchronous",
          "selfHostable",
          "managedAuth",
          "eventsInbound",
          "eventsOutbound"
        ],
        "properties": {
          "synchronous": {
            "type": "boolean"
          },
          "selfHostable": {
            "type": "boolean"
          },
          "managedAuth": {
            "type": "boolean"
          },
          "eventsInbound": {
            "type": "boolean"
          },
          "eventsOutbound": {
            "type": "boolean"
          }
        }
      },
      "transports": {
        "type": "array",
        "items": {
          "enum": [
            "http",
            "native-node"
          ]
        }
      },
      "build": {
        "enum": [
          "workflow-generator",
          "scenario-template",
          "component-template",
          "flow-template",
          "dag-template",
          "function-template",
          "implement-blueprint"
        ]
      },
      "notes": {
        "type": "string"
      },
      "alsoProvides": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "plane"
          ],
          "properties": {
            "plane": {
              "type": "string"
            },
            "note": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "notifications": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://omniproject.dev/vendors/notification.schema.json",
    "title": "OmniProject notification vendor",
    "description": "A channel alerts/events are delivered TO. One file per vendor under vendors/notifications/<id>.json.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "label",
      "docsUrl",
      "kind",
      "capabilities",
      "tools"
    ],
    "properties": {
      "id": {
        "type": "string",
        "pattern": "^[a-z0-9-]+$"
      },
      "label": {
        "type": "string"
      },
      "docsUrl": {
        "type": "string"
      },
      "kind": {
        "enum": [
          "chat",
          "email",
          "incident",
          "sms",
          "webhook",
          "iot",
          "agent"
        ]
      },
      "capabilities": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "channels",
          "directMessage",
          "richFormatting",
          "threads",
          "inboundReply",
          "delivery"
        ],
        "properties": {
          "channels": {
            "type": "boolean"
          },
          "directMessage": {
            "type": "boolean"
          },
          "richFormatting": {
            "type": "boolean"
          },
          "threads": {
            "type": "boolean"
          },
          "inboundReply": {
            "type": "boolean"
          },
          "delivery": {
            "enum": [
              "incoming-webhook",
              "oauth-app",
              "api-key",
              "smtp",
              "hmac-webhook",
              "mqtt",
              "mcp"
            ]
          }
        }
      },
      "tools": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "notes": {
        "type": "string"
      }
    }
  },
  "outputs": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://omniproject.dev/vendors/output.schema.json",
    "title": "OmniProject output vendor",
    "description": "An outward interface that exposes portfolio data/events. One file per vendor under vendors/outputs/<id>.json.",
    "type": "object",
    "additionalProperties": false,
    "required": [
      "id",
      "label",
      "route",
      "kind",
      "capabilities",
      "tools"
    ],
    "properties": {
      "id": {
        "type": "string",
        "pattern": "^[a-z0-9-]+$"
      },
      "label": {
        "type": "string"
      },
      "route": {
        "type": "string"
      },
      "kind": {
        "enum": [
          "read-api",
          "bi-feed",
          "agent-api",
          "export",
          "metrics",
          "events-out",
          "events-in"
        ]
      },
      "capabilities": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "readOnly",
          "streaming",
          "auth"
        ],
        "properties": {
          "readOnly": {
            "type": "boolean"
          },
          "streaming": {
            "type": "boolean"
          },
          "auth": {
            "enum": [
              "session",
              "api-token",
              "session-or-token",
              "hmac",
              "user-action"
            ]
          }
        }
      },
      "tools": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "notes": {
        "type": "string"
      }
    }
  }
};
