/* GENERATED by scripts/src/gen-views.ts — do not edit.
   Views are authored as JSON under lib/backend-catalogue/assets/views/;
   run `pnpm --filter @workspace/scripts run gen-views` to regenerate. */
import type { ViewDefinition } from "./view-catalogue";

export const VIEWS_DATA: ViewDefinition[] = [
  {
    "description": "Time-phased schedule from start / due dates.",
    "group": "Traditional",
    "id": "gantt",
    "kind": "timeline",
    "label": "Gantt Timeline",
    "methodologies": [
      "waterfall"
    ],
    "methodology": "Waterfall / Critical Path",
    "needs": "scheduling",
    "order": 3,
    "short": "Gantt"
  },
  {
    "description": "Status columns with WIP limits; drag to move.",
    "group": "Agile",
    "id": "kanban",
    "kind": "board",
    "label": "Kanban Board",
    "methodologies": [
      "kanban"
    ],
    "methodology": "Kanban / Lean",
    "order": 1,
    "short": "Kanban"
  },
  {
    "description": "Sortable table of all work items.",
    "group": "General",
    "id": "list",
    "kind": "table",
    "label": "List / Table",
    "methodologies": [
      "*"
    ],
    "methodology": "Methodology-neutral",
    "order": 6,
    "short": "List"
  },
  {
    "description": "Management stages, product status and a highlight report.",
    "group": "Traditional",
    "id": "prince2",
    "kind": "stages",
    "label": "PRINCE2 Stages",
    "methodologies": [
      "prince2"
    ],
    "methodology": "PRINCE2",
    "order": 4,
    "short": "PRINCE2"
  },
  {
    "description": "Risks, Assumptions, Issues and Dependencies register.",
    "group": "Governance",
    "id": "raid",
    "kind": "register",
    "label": "RAID Log",
    "methodologies": [
      "governance"
    ],
    "methodology": "Risk & governance",
    "needs": "raid",
    "order": 5,
    "short": "RAID"
  },
  {
    "description": "Active sprint board, backlog, burndown and velocity.",
    "group": "Agile",
    "id": "scrum",
    "kind": "board",
    "label": "Scrum Sprint",
    "methodologies": [
      "scrum"
    ],
    "methodology": "Scrum",
    "order": 2,
    "short": "Scrum"
  }
];
