/* GENERATED by scripts/src/gen-widgets.ts — do not edit.
   Widgets are authored as JSON under lib/backend-catalogue/assets/widgets/;
   run `pnpm --filter @workspace/scripts run gen-widgets` to regenerate. */
import type { WidgetDefinition } from "./widget-catalogue";

export const WIDGETS_DATA: WidgetDefinition[] = [
  {
    "type": "capacityActuals",
    "label": "Capacity actuals vs plan",
    "description": "Logged-time actuals compared against each resource's plan, surfacing over- and under-delivery.",
    "defaultSpan": 2,
    "requiresEntity": "member",
    "order": 70
  },
  {
    "type": "portfolioHealth",
    "label": "Portfolio health",
    "description": "RAG health cards across the portfolio.",
    "defaultSpan": 3,
    "order": 10,
    "refresh": 60
  },
  {
    "type": "portfolioTrends",
    "label": "Portfolio trends",
    "description": "Aggregate progress and budget trend over time.",
    "defaultSpan": 2,
    "order": 20
  },
  {
    "type": "programmeCount",
    "label": "Programme count",
    "description": "Total number of programmes.",
    "defaultSpan": 1,
    "requiresEntity": "programme",
    "order": 50
  },
  {
    "type": "projectCount",
    "label": "Project count",
    "description": "Total number of projects.",
    "defaultSpan": 1,
    "order": 40
  },
  {
    "type": "recentActivity",
    "label": "Recent activity",
    "description": "The latest activity across projects.",
    "defaultSpan": 1,
    "order": 30
  },
  {
    "type": "statusBreakdown",
    "label": "Status breakdown",
    "description": "Projects grouped by status.",
    "defaultSpan": 1,
    "order": 60
  }
];
