/**
 * View catalogue generator.
 *
 * Views are authored as one JSON file per view under
 * lib/backend-catalogue/assets/views/<id>.json. This validates each against
 * assets/schema/view.schema.json and embeds the result into the portable,
 * type-checked lib/backend-catalogue/src/views.generated.ts the catalogue imports
 * — the same generate-and-drift-guard pattern as gen-vendors, so the views stay
 * data (no TypeScript to add one) while the SPA + gateway consume typed objects.
 *
 * Run: pnpm --filter @workspace/scripts run gen-views
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { validate, type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/views.generated.ts");

const schema = JSON.parse(fs.readFileSync(path.join(ASSETS, "schema/view.schema.json"), "utf8")) as JsonSchema;
const dir = path.join(ASSETS, "views");

const rows: Array<{ id: string }> = [];
const seen = new Set<string>();
for (const file of fs.readdirSync(dir).filter((f) => f.endsWith(".json")).sort()) {
  const data = JSON.parse(fs.readFileSync(path.join(dir, file), "utf8")) as { id?: string };
  const errs = validate(schema, data);
  if (errs.length) throw new Error(`views/${file} fails view.schema.json:\n  - ${errs.join("\n  - ")}`);
  if (data.id !== file.replace(/\.json$/, "")) throw new Error(`views/${file}: filename must equal id "${data.id}"`);
  if (seen.has(data.id)) throw new Error(`views: duplicate id "${data.id}"`);
  seen.add(data.id);
  rows.push(data as { id: string });
}
rows.sort((a, b) => a.id.localeCompare(b.id));

const out = [
  "/* GENERATED by scripts/src/gen-views.ts — do not edit.",
  "   Views are authored as JSON under lib/backend-catalogue/assets/views/;",
  "   run `pnpm --filter @workspace/scripts run gen-views` to regenerate. */",
  'import type { ViewDefinition } from "./view-catalogue";',
  "",
  `export const VIEWS_DATA: ViewDefinition[] = ${JSON.stringify(rows, null, 2)};`,
  "",
].join("\n");
fs.writeFileSync(OUT_TS, out);

console.log(`views: ${rows.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
