/**
 * Canonical RAG/health band vocabulary generator.
 *
 * The RAG/health bands are authored as a single JSON ARRAY (lib/backend-catalogue/assets/
 * rag-vocabulary.json) — a flat vocabulary, so one array reads better than a file per token. This
 * validates every entry against assets/schema/rag-vocabulary.schema.json and emits the portable
 * lib/backend-catalogue/src/rag-vocabulary.generated.ts via the shared gen-registry engine (its
 * array-source variant) — the same generate-and-drift-guard pattern as gen-severity-vocabulary.
 *
 * Run: pnpm --filter @workspace/scripts run gen-rag-vocabulary
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { runArrayAssetGenerator } from "./lib/gen-registry";

runArrayAssetGenerator({
  label: "rag-vocabulary",
  schemaFile: "rag-vocabulary.schema.json",
  constName: "RAG_VOCABULARY_DATA",
  typeName: "RagVocabEntry",
  typeModule: "./rag-vocabulary",
  headerLines: [
    "/* GENERATED by scripts/src/gen-rag-vocabulary.ts — do not edit.",
    "   Source: lib/backend-catalogue/assets/rag-vocabulary.json;",
    "   run `pnpm --filter @workspace/scripts run gen-rag-vocabulary` to regenerate. */",
  ],
  loadRows: (root) =>
    JSON.parse(
      fs.readFileSync(path.join(root, "lib/backend-catalogue/assets/rag-vocabulary.json"), "utf8"),
    ) as Array<Record<string, unknown>>,
});
