/**
 * Canonical GTD task-context vocabulary generator.
 *
 * The GTD @contexts are authored as a single JSON ARRAY (lib/backend-catalogue/assets/
 * task-context-vocabulary.json) — a FLAT vocabulary (a set with a display order, no internal ordinal
 * level), so one array reads better than a file per token. This validates every entry against
 * assets/schema/task-context-vocabulary.schema.json and emits the portable
 * lib/backend-catalogue/src/task-context-vocabulary.generated.ts via the shared gen-registry engine (its
 * array-source variant) — the same generate-and-drift-guard pattern as gen-energy-vocabulary.
 *
 * Run: pnpm --filter @workspace/scripts run gen-task-context-vocabulary
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { runArrayAssetGenerator } from "./lib/gen-registry";

runArrayAssetGenerator({
  label: "task-context-vocabulary",
  schemaFile: "task-context-vocabulary.schema.json",
  constName: "TASK_CONTEXT_VOCABULARY_DATA",
  typeName: "TaskContextVocabEntry",
  typeModule: "./task-context-vocabulary",
  headerLines: [
    "/* GENERATED by scripts/src/gen-task-context-vocabulary.ts — do not edit.",
    "   Source: lib/backend-catalogue/assets/task-context-vocabulary.json;",
    "   run `pnpm --filter @workspace/scripts run gen-task-context-vocabulary` to regenerate. */",
  ],
  loadRows: (root) =>
    JSON.parse(
      fs.readFileSync(path.join(root, "lib/backend-catalogue/assets/task-context-vocabulary.json"), "utf8"),
    ) as Array<Record<string, unknown>>,
});
