/**
 * Canonical field-vocabulary generator.
 *
 * The base fields are authored as a single JSON ARRAY (lib/backend-catalogue/assets/
 * fields.json) — a flat vocabulary, so one array reads better than 114 tiny files. A backend
 * descriptor may also CONTRIBUTE fields (its optional `fields[]`), so the registry grows as
 * vendors are added; `loadSuperset` computes the base ∪ vendor union (dedup by key; a
 * conflicting type/group redefinition is an error). This validates every field in that union
 * against assets/schema/field.schema.json and emits the portable
 * lib/backend-catalogue/src/fields.generated.ts via the shared gen-registry engine (its
 * array-source variant) — the same generate-and-drift-guard pattern as the per-file catalogues.
 *
 * Run: pnpm --filter @workspace/scripts run gen-fields
 */
import { runArrayAssetGenerator } from "./lib/gen-registry";
import { loadSuperset } from "./lib/superset";

runArrayAssetGenerator({
  label: "fields",
  schemaFile: "field.schema.json",
  constName: "FIELDS_DATA",
  typeName: "FieldDescriptor",
  typeModule: "./field-vocabulary",
  idField: "key",
  headerLines: [
    "/* GENERATED by scripts/src/gen-fields.ts — do not edit.",
    "   The superset = base fields (lib/backend-catalogue/assets/fields.json) UNION every backend's",
    "   contributed fields[]; run `pnpm --filter @workspace/scripts run gen-fields` to regenerate. */",
  ],
  // Base fields ∪ every backend's contributed fields[] (dedup + conflict-checked in loadSuperset).
  loadRows: (root) => loadSuperset(root).fields as unknown as Array<Record<string, unknown>>,
});
