/**
 * Canonical work-item vocabulary generator.
 *
 * The statuses + priorities are authored as a single JSON ARRAY (lib/backend-catalogue/assets/
 * work-vocabulary.json) — a flat vocabulary, so one array reads better than a file per token. This
 * validates every entry against assets/schema/work-vocabulary.schema.json and emits the portable
 * lib/backend-catalogue/src/work-vocabulary.generated.ts via the shared gen-registry engine (its
 * array-source variant) — the same generate-and-drift-guard pattern as fields.
 *
 * Run: pnpm --filter @workspace/scripts run gen-work-vocabulary
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { runArrayAssetGenerator } from "./lib/gen-registry";

runArrayAssetGenerator({
  label: "work-vocabulary",
  schemaFile: "work-vocabulary.schema.json",
  constName: "WORK_VOCABULARY_DATA",
  typeName: "WorkVocabEntry",
  typeModule: "./work-vocabulary",
  headerLines: [
    "/* GENERATED by scripts/src/gen-work-vocabulary.ts — do not edit.",
    "   Source: lib/backend-catalogue/assets/work-vocabulary.json;",
    "   run `pnpm --filter @workspace/scripts run gen-work-vocabulary` to regenerate. */",
  ],
  loadRows: (root) =>
    JSON.parse(
      fs.readFileSync(path.join(root, "lib/backend-catalogue/assets/work-vocabulary.json"), "utf8"),
    ) as Array<Record<string, unknown>>,
});
