/**
 * Copilot persona catalogue generator.
 *
 * Personas are authored as one JSON file per persona under
 * lib/backend-catalogue/assets/personas/<id>.json. Validates each against
 * assets/schema/persona.schema.json (via the shared gen-registry engine) and emits
 * lib/backend-catalogue/src/personas.generated.ts — the same generate-and-drift-guard
 * pattern as gen-methodologies. Making personas data is what lets a persona PACK ship as
 * an importable JSON bundle (and keeps the gateway's single-file build clean).
 *
 * Run: pnpm --filter @workspace/scripts run gen-personas
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";
import { loadGroup, emitRegistry, type AssetGroup } from "./lib/gen-registry";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/personas.generated.ts");

const group: AssetGroup = {
  dir: path.join(ASSETS, "personas"),
  schema: JSON.parse(fs.readFileSync(path.join(ASSETS, "schema/persona.schema.json"), "utf8")) as JsonSchema,
  label: "personas",
  constName: "PERSONAS_DATA",
  typeName: "Persona",
  typeModule: "./persona-catalogue",
};

const rows = loadGroup(group);
emitRegistry(OUT_TS, [
  "/* GENERATED by scripts/src/gen-personas.ts — do not edit.",
  "   Personas are authored as JSON under lib/backend-catalogue/assets/personas/;",
  "   run `pnpm --filter @workspace/scripts run gen-personas` to regenerate. */",
], [{ group, rows }]);

console.log(`personas: ${rows.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
