/**
 * Dashboard-preset catalogue generator.
 *
 * Role-tailored "what needs me today" dashboards are authored as one JSON file per preset under
 * lib/backend-catalogue/assets/dashboard-presets/<id>.json. Validates each against
 * assets/schema/dashboard-preset.schema.json (via the shared gen-registry engine) and emits
 * lib/backend-catalogue/src/dashboard-presets.generated.ts — the same generate-and-drift-guard
 * pattern as gen-widgets / gen-personas. Making presets data is what lets a preset PACK ship as an
 * importable JSON bundle and keeps the single-file build clean.
 *
 * Run: pnpm --filter @workspace/scripts run gen-dashboard-presets
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";
import { loadGroup, emitRegistry, type AssetGroup } from "./lib/gen-registry";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/dashboard-presets.generated.ts");

const group: AssetGroup = {
  dir: path.join(ASSETS, "dashboard-presets"),
  schema: JSON.parse(fs.readFileSync(path.join(ASSETS, "schema/dashboard-preset.schema.json"), "utf8")) as JsonSchema,
  label: "dashboard-presets",
  constName: "DASHBOARD_PRESETS_DATA",
  typeName: "DashboardPreset",
  typeModule: "./dashboard-preset-catalogue",
};

const rows = loadGroup(group);
emitRegistry(OUT_TS, [
  "/* GENERATED by scripts/src/gen-dashboard-presets.ts — do not edit.",
  "   Presets are authored as JSON under lib/backend-catalogue/assets/dashboard-presets/;",
  "   run `pnpm --filter @workspace/scripts run gen-dashboard-presets` to regenerate. */",
], [{ group, rows }]);

console.log(`dashboard-presets: ${rows.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
