/**
 * Canonical RAID/risk severity vocabulary generator.
 *
 * The severity grades are authored as a single JSON ARRAY (lib/backend-catalogue/assets/
 * severity-vocabulary.json) — a flat vocabulary, so one array reads better than a file per token. This
 * validates every entry against assets/schema/severity-vocabulary.schema.json and emits the portable
 * lib/backend-catalogue/src/severity-vocabulary.generated.ts via the shared gen-registry engine (its
 * array-source variant) — the same generate-and-drift-guard pattern as gen-energy-vocabulary.
 *
 * Run: pnpm --filter @workspace/scripts run gen-severity-vocabulary
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { runArrayAssetGenerator } from "./lib/gen-registry";

runArrayAssetGenerator({
  label: "severity-vocabulary",
  schemaFile: "severity-vocabulary.schema.json",
  constName: "SEVERITY_VOCABULARY_DATA",
  typeName: "SeverityVocabEntry",
  typeModule: "./severity-vocabulary",
  headerLines: [
    "/* GENERATED by scripts/src/gen-severity-vocabulary.ts — do not edit.",
    "   Source: lib/backend-catalogue/assets/severity-vocabulary.json;",
    "   run `pnpm --filter @workspace/scripts run gen-severity-vocabulary` to regenerate. */",
  ],
  loadRows: (root) =>
    JSON.parse(
      fs.readFileSync(path.join(root, "lib/backend-catalogue/assets/severity-vocabulary.json"), "utf8"),
    ) as Array<Record<string, unknown>>,
});
