/**
 * Canonical field-vocabulary generator.
 *
 * The fields are authored as a single JSON ARRAY (lib/backend-catalogue/assets/
 * fields.json) — a flat vocabulary, so one array reads better than 114 tiny files.
 * Validates each element against assets/schema/field.schema.json (the shared
 * validator), enforces unique keys, and emits the portable
 * lib/backend-catalogue/src/fields.generated.ts — same generate-and-drift-guard
 * pattern as gen-views, adapted for a single array file.
 *
 * Run: pnpm --filter @workspace/scripts run gen-fields
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { validate, type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const SRC = path.join(ROOT, "lib/backend-catalogue/assets/fields.json");
const SCHEMA = path.join(ASSETS, "schema/field.schema.json");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/fields.generated.ts");

const schema = JSON.parse(fs.readFileSync(SCHEMA, "utf8")) as JsonSchema;
const fields = JSON.parse(fs.readFileSync(SRC, "utf8")) as Array<{ key?: string }>;
if (!Array.isArray(fields)) throw new Error("fields.json must be a JSON array");

const seen = new Set<string>();
fields.forEach((f, i) => {
  const errs = validate(schema, f);
  if (errs.length) throw new Error(`fields[${i}] fails its schema:\n  - ${errs.join("\n  - ")}`);
  const key = f.key!;
  if (seen.has(key)) throw new Error(`duplicate field key "${key}"`);
  seen.add(key);
});

fs.writeFileSync(
  OUT_TS,
  [
    "/* GENERATED by scripts/src/gen-fields.ts — do not edit.",
    "   Fields are authored as a JSON array in lib/backend-catalogue/assets/fields.json;",
    "   run `pnpm --filter @workspace/scripts run gen-fields` to regenerate. */",
    'import type { FieldDescriptor } from "./field-vocabulary";',
    "",
    `export const FIELDS_DATA: FieldDescriptor[] = ${JSON.stringify(fields, null, 2)};`,
    "",
  ].join("\n"),
);

console.log(`fields: ${fields.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
