/**
 * Canonical GTD energy-level vocabulary generator.
 *
 * The GTD energy levels are authored as a single JSON ARRAY (lib/backend-catalogue/assets/
 * energy-vocabulary.json) — a flat vocabulary, so one array reads better than a file per token. This
 * validates every entry against assets/schema/energy-vocabulary.schema.json and emits the portable
 * lib/backend-catalogue/src/energy-vocabulary.generated.ts via the shared gen-registry engine (its
 * array-source variant) — the same generate-and-drift-guard pattern as gen-task-vocabulary.
 *
 * Run: pnpm --filter @workspace/scripts run gen-energy-vocabulary
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { runArrayAssetGenerator } from "./lib/gen-registry";

runArrayAssetGenerator({
  label: "energy-vocabulary",
  schemaFile: "energy-vocabulary.schema.json",
  constName: "ENERGY_VOCABULARY_DATA",
  typeName: "EnergyVocabEntry",
  typeModule: "./energy-vocabulary",
  headerLines: [
    "/* GENERATED by scripts/src/gen-energy-vocabulary.ts — do not edit.",
    "   Source: lib/backend-catalogue/assets/energy-vocabulary.json;",
    "   run `pnpm --filter @workspace/scripts run gen-energy-vocabulary` to regenerate. */",
  ],
  loadRows: (root) =>
    JSON.parse(
      fs.readFileSync(path.join(root, "lib/backend-catalogue/assets/energy-vocabulary.json"), "utf8"),
    ) as Array<Record<string, unknown>>,
});
