/**
 * gen-openapi-bundle — embed the consumer (northbound) OpenAPI spec into a TS
 * module the gateway can serve at runtime, with NO runtime YAML dependency and no
 * reliance on the docs/spec tree shipping in the container.
 *
 * Mirrors gen-contract: the generated file is committed and CI fails on drift, so
 * `GET /api/openapi.yaml` always matches `lib/api-spec/openapi.yaml`.
 *
 * Run: pnpm --filter @workspace/scripts run gen-openapi
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const SRC = path.join(ROOT, "lib/api-spec/openapi.yaml");
const OUT = path.join(ROOT, "artifacts/api-server/src/lib/openapi.generated.ts");

const yaml = fs.readFileSync(SRC, "utf8");

// Light extraction (no YAML parser): title/version are simple single lines under
// `info:`, and each path is a top-level key under `paths:`. We only need these for
// the discovery document — the full, authoritative spec is served verbatim.
const title = /^\s{2}title:\s*(.+)$/m.exec(yaml)?.[1]?.trim() ?? "OmniProject API";
const version = /^\s{2}version:\s*(.+)$/m.exec(yaml)?.[1]?.trim() ?? "0.0.0";

const paths: string[] = [];
const lines = yaml.split("\n");
let inPaths = false;
for (const line of lines) {
  if (/^paths:\s*$/.test(line)) { inPaths = true; continue; }
  if (inPaths) {
    if (/^\S/.test(line)) break; // dedented to a new top-level key → paths section ended
    const m = /^\s{2}(\/\S*):\s*$/.exec(line);
    if (m) paths.push(m[1]!);
  }
}

const body = [
  "/* GENERATED by scripts/src/gen-openapi-bundle.ts — do not edit.",
  "   Run `pnpm --filter @workspace/scripts run gen-openapi` to regenerate. */",
  "",
  "/** The full consumer (northbound) OpenAPI spec, verbatim. Broker-agnostic. */",
  `export const OPENAPI_YAML = ${JSON.stringify(yaml)};`,
  "",
  "/** Spec identity for the discovery document. */",
  `export const OPENAPI_INFO = { title: ${JSON.stringify(title)}, version: ${JSON.stringify(version)} } as const;`,
  "",
  "/** The operation paths (under the /api base), for discovery. */",
  `export const OPENAPI_PATHS: readonly string[] = ${JSON.stringify(paths)};`,
  "",
].join("\n");

fs.writeFileSync(OUT, body);
console.log(`Wrote ${path.relative(ROOT, OUT)} — ${paths.length} paths, version ${version}.`);
