/**
 * Canonical RAID/risk impact vocabulary generator.
 *
 * The impact grades are authored as a single JSON ARRAY (lib/backend-catalogue/assets/
 * impact-vocabulary.json) — a flat vocabulary, so one array reads better than a file per token. This
 * validates every entry against assets/schema/impact-vocabulary.schema.json and emits the portable
 * lib/backend-catalogue/src/impact-vocabulary.generated.ts via the shared gen-registry engine (its
 * array-source variant) — the same generate-and-drift-guard pattern as gen-severity-vocabulary.
 *
 * Run: pnpm --filter @workspace/scripts run gen-impact-vocabulary
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { runArrayAssetGenerator } from "./lib/gen-registry";

runArrayAssetGenerator({
  label: "impact-vocabulary",
  schemaFile: "impact-vocabulary.schema.json",
  constName: "IMPACT_VOCABULARY_DATA",
  typeName: "ImpactVocabEntry",
  typeModule: "./impact-vocabulary",
  headerLines: [
    "/* GENERATED by scripts/src/gen-impact-vocabulary.ts — do not edit.",
    "   Source: lib/backend-catalogue/assets/impact-vocabulary.json;",
    "   run `pnpm --filter @workspace/scripts run gen-impact-vocabulary` to regenerate. */",
  ],
  loadRows: (root) =>
    JSON.parse(
      fs.readFileSync(path.join(root, "lib/backend-catalogue/assets/impact-vocabulary.json"), "utf8"),
    ) as Array<Record<string, unknown>>,
});
