/**
 * Methodology reference-ruleset catalogue generator.
 *
 * Reference rulesets are authored as one JSON file per methodology under
 * lib/backend-catalogue/assets/methodology-rulesets/<id>.json (id = methodology id).
 * Validates each against assets/schema/methodology-ruleset.schema.json (via the shared
 * gen-registry engine) and emits lib/backend-catalogue/src/methodology-rulesets.generated.ts —
 * the same generate-and-drift-guard pattern as gen-methodologies. The bundles are restrict-only
 * data the business-ruleset engine consumes; being data lets them ship inside a methodology PACK.
 *
 * Run: pnpm --filter @workspace/scripts run gen-methodology-rulesets
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";
import { loadGroup, emitRegistry, type AssetGroup } from "./lib/gen-registry";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/methodology-rulesets.generated.ts");

const group: AssetGroup = {
  dir: path.join(ASSETS, "methodology-rulesets"),
  schema: JSON.parse(fs.readFileSync(path.join(ASSETS, "schema/methodology-ruleset.schema.json"), "utf8")) as JsonSchema,
  label: "methodology-rulesets",
  constName: "REFERENCE_RULESETS_DATA",
  typeName: "ReferenceRulesetData",
  typeModule: "./methodology-rulesets",
};

const rows = loadGroup(group);
emitRegistry(OUT_TS, [
  "/* GENERATED by scripts/src/gen-methodology-rulesets.ts — do not edit.",
  "   Reference rulesets are authored as JSON under lib/backend-catalogue/assets/methodology-rulesets/;",
  "   run `pnpm --filter @workspace/scripts run gen-methodology-rulesets` to regenerate. */",
], [{ group, rows }]);

console.log(`methodology-rulesets: ${rows.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
