/**
 * View catalogue generator.
 *
 * Views are authored as one JSON file per view under
 * lib/backend-catalogue/assets/views/<id>.json. Validates each against
 * assets/schema/view.schema.json (via the shared gen-registry engine) and emits
 * the portable, type-checked lib/backend-catalogue/src/views.generated.ts — the
 * same generate-and-drift-guard pattern as gen-vendors.
 *
 * Run: pnpm --filter @workspace/scripts run gen-views
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";
import { loadGroup, emitRegistry, type AssetGroup } from "./lib/gen-registry";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/views.generated.ts");

const group: AssetGroup = {
  dir: path.join(ASSETS, "views"),
  schema: JSON.parse(fs.readFileSync(path.join(ASSETS, "schema/view.schema.json"), "utf8")) as JsonSchema,
  label: "views",
  constName: "VIEWS_DATA",
  typeName: "ViewDefinition",
  typeModule: "./view-catalogue",
};

const rows = loadGroup(group);
emitRegistry(OUT_TS, [
  "/* GENERATED by scripts/src/gen-views.ts — do not edit.",
  "   Views are authored as JSON under lib/backend-catalogue/assets/views/;",
  "   run `pnpm --filter @workspace/scripts run gen-views` to regenerate. */",
], [{ group, rows }]);

console.log(`views: ${rows.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
