/**
 * Methodology catalogue generator.
 *
 * Methodologies are authored as one JSON file per methodology under
 * lib/backend-catalogue/assets/methodologies/<id>.json. Validates each against
 * assets/schema/methodology.schema.json (via the shared gen-registry engine) and
 * emits lib/backend-catalogue/src/methodologies.generated.ts — the same
 * generate-and-drift-guard pattern as gen-views. Making methodologies data is what
 * lets a methodology PACK ship as an importable JSON bundle.
 *
 * Run: pnpm --filter @workspace/scripts run gen-methodologies
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";
import { loadGroup, emitRegistry, type AssetGroup } from "./lib/gen-registry";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/methodologies.generated.ts");

const group: AssetGroup = {
  dir: path.join(ASSETS, "methodologies"),
  schema: JSON.parse(fs.readFileSync(path.join(ASSETS, "schema/methodology.schema.json"), "utf8")) as JsonSchema,
  label: "methodologies",
  constName: "METHODOLOGIES_DATA",
  typeName: "MethodologyDefinition",
  typeModule: "./methodology-catalogue",
};

const rows = loadGroup(group);
emitRegistry(OUT_TS, [
  "/* GENERATED by scripts/src/gen-methodologies.ts — do not edit.",
  "   Methodologies are authored as JSON under lib/backend-catalogue/assets/methodologies/;",
  "   run `pnpm --filter @workspace/scripts run gen-methodologies` to regenerate. */",
], [{ group, rows }]);

console.log(`methodologies: ${rows.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
