/**
 * Report catalogue generator.
 *
 * Reports are authored as one JSON file per report under
 * lib/backend-catalogue/assets/reports/<id>.json. Validates each against
 * assets/schema/report.schema.json (via the shared gen-registry engine) and emits
 * lib/backend-catalogue/src/reports.generated.ts — the same generate-and-drift-guard
 * pattern as gen-views.
 *
 * Run: pnpm --filter @workspace/scripts run gen-reports
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";
import { loadGroup, emitRegistry, type AssetGroup } from "./lib/gen-registry";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/reports.generated.ts");

const group: AssetGroup = {
  dir: path.join(ASSETS, "reports"),
  schema: JSON.parse(fs.readFileSync(path.join(ASSETS, "schema/report.schema.json"), "utf8")) as JsonSchema,
  label: "reports",
  constName: "REPORTS_DATA",
  typeName: "ReportDefinition",
  typeModule: "./report-catalogue",
};

const rows = loadGroup(group);
emitRegistry(OUT_TS, [
  "/* GENERATED by scripts/src/gen-reports.ts — do not edit.",
  "   Reports are authored as JSON under lib/backend-catalogue/assets/reports/;",
  "   run `pnpm --filter @workspace/scripts run gen-reports` to regenerate. */",
], [{ group, rows }]);

console.log(`reports: ${rows.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
