/**
 * Canonical field-vocabulary generator.
 *
 * The base fields are authored as a single JSON ARRAY (lib/backend-catalogue/assets/
 * fields.json) — a flat vocabulary, so one array reads better than 114 tiny files. A backend
 * descriptor may also CONTRIBUTE fields (its optional `fields[]`), so the registry grows as
 * vendors are added; `loadSuperset` computes the base ∪ vendor union (dedup by key; a
 * conflicting type/group redefinition is an error). This validates every field in that union
 * against assets/schema/field.schema.json and emits the portable
 * lib/backend-catalogue/src/fields.generated.ts — same generate-and-drift-guard pattern as
 * gen-views, adapted for a single array file.
 *
 * Run: pnpm --filter @workspace/scripts run gen-fields
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { validate, type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";
import { loadSuperset } from "./lib/superset";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const SCHEMA = path.join(ASSETS, "schema/field.schema.json");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/fields.generated.ts");

const schema = JSON.parse(fs.readFileSync(SCHEMA, "utf8")) as JsonSchema;
// Base fields ∪ every backend's contributed fields[] (dedup + conflict-checked in loadSuperset).
const { fields } = loadSuperset(ROOT);

fields.forEach((f, i) => {
  const errs = validate(schema, f);
  if (errs.length) throw new Error(`fields[${i}] (key "${f.key}") fails its schema:\n  - ${errs.join("\n  - ")}`);
});

fs.writeFileSync(
  OUT_TS,
  [
    "/* GENERATED by scripts/src/gen-fields.ts — do not edit.",
    "   The superset = base fields (lib/backend-catalogue/assets/fields.json) UNION every backend's",
    "   contributed fields[]; run `pnpm --filter @workspace/scripts run gen-fields` to regenerate. */",
    'import type { FieldDescriptor } from "./field-vocabulary";',
    "",
    `export const FIELDS_DATA: FieldDescriptor[] = ${JSON.stringify(fields, null, 2)};`,
    "",
  ].join("\n"),
);

console.log(`fields: ${fields.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
