/**
 * Screen catalogue generator.
 *
 * Screens are authored as one JSON file per screen under
 * lib/backend-catalogue/assets/screens/<id>.json. Validates each against
 * assets/schema/screen.schema.json (via the shared gen-registry engine) and emits
 * lib/backend-catalogue/src/screens.generated.ts — the same generate-and-drift-guard
 * pattern as gen-views.
 *
 * Run: pnpm --filter @workspace/scripts run gen-screens
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";
import { loadGroup, emitRegistry, type AssetGroup } from "./lib/gen-registry";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/screens.generated.ts");

const group: AssetGroup = {
  dir: path.join(ASSETS, "screens"),
  schema: JSON.parse(fs.readFileSync(path.join(ASSETS, "schema/screen.schema.json"), "utf8")) as JsonSchema,
  label: "screens",
  constName: "SCREENS_DATA",
  typeName: "ScreenDefinition",
  typeModule: "./screen-catalogue",
};

const rows = loadGroup(group);
emitRegistry(OUT_TS, [
  "/* GENERATED by scripts/src/gen-screens.ts — do not edit.",
  "   Screens are authored as JSON under lib/backend-catalogue/assets/screens/;",
  "   run `pnpm --filter @workspace/scripts run gen-screens` to regenerate. */",
], [{ group, rows }]);

console.log(`screens: ${rows.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
