/**
 * Vendor catalogue generator.
 *
 * Vendors are authored as one JSON file per vendor under
 * lib/backend-catalogue/vendors/<plane>/<id>.json — to add a vendor you design
 * the JSON against the plane's schema (vendors/schema/<plane>.schema.json) and
 * drop it in. This validates every vendor file (via the shared gen-registry
 * engine) and emits the embedded, type-checked TypeScript the catalogue imports
 * (lib/backend-catalogue/src/vendors.generated.ts) plus the embedded schemas the
 * runtime loader uses, with a CI drift guard keeping both in lock-step.
 *
 * Run: pnpm --filter @workspace/scripts run gen-vendors
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";
import { loadGroup, emitRegistry, type AssetGroup } from "./lib/gen-registry";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const VENDORS = path.join(ROOT, "lib/backend-catalogue/vendors");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/vendors.generated.ts");
const OUT_SCHEMAS = path.join(ROOT, "lib/backend-catalogue/src/vendor-schemas.generated.ts");

interface Plane { dir: string; schemaFile: string; constName: string; typeName: string; typeModule: string }
const PLANES: Plane[] = [
  { dir: "backends", schemaFile: "backend.schema.json", constName: "BACKENDS_DATA", typeName: "BackendDefinition", typeModule: "./backend-catalogue" },
  { dir: "brokers", schemaFile: "broker.schema.json", constName: "BROKERS_DATA", typeName: "BrokerDefinition", typeModule: "./broker-catalogue" },
  { dir: "notifications", schemaFile: "notification.schema.json", constName: "NOTIFICATIONS_DATA", typeName: "NotificationDefinition", typeModule: "./notification-catalogue" },
  { dir: "outputs", schemaFile: "output.schema.json", constName: "OUTPUTS_DATA", typeName: "OutputDefinition", typeModule: "./output-catalogue" },
];

const readSchema = (file: string): JsonSchema => JSON.parse(fs.readFileSync(path.join(VENDORS, "schema", file), "utf8")) as JsonSchema;

const groups: AssetGroup[] = PLANES.map((p) => ({
  dir: path.join(VENDORS, p.dir), schema: readSchema(p.schemaFile), label: p.dir,
  constName: p.constName, typeName: p.typeName, typeModule: p.typeModule,
}));

// ── Emit the typed vendor arrays ──────────────────────────────────────────────
const loaded = groups.map((group) => ({ group, rows: loadGroup(group) }));
emitRegistry(OUT_TS, [
  "/* GENERATED by scripts/src/gen-vendors.ts — do not edit.",
  "   Vendors are authored as JSON under lib/backend-catalogue/vendors/<plane>/;",
  "   run `pnpm --filter @workspace/scripts run gen-vendors` to regenerate. */",
], loaded);

// ── Emit the embedded schemas (keyed by plane) for the runtime loader ─────────
// So a deployment's own vendor JSON can be validated at boot with no fs/JSON
// shipped — the same schema the author designed against.
const schemas: Record<string, JsonSchema> = {};
for (const p of PLANES) schemas[p.dir] = readSchema(p.schemaFile);
fs.writeFileSync(OUT_SCHEMAS, [
  "/* GENERATED by scripts/src/gen-vendors.ts — do not edit.",
  "   The per-plane vendor JSON Schemas, embedded for runtime validation. */",
  'import type { JsonSchema } from "./vendor-schema";',
  "",
  `export const VENDOR_SCHEMAS: Record<string, JsonSchema> = ${JSON.stringify(schemas, null, 2)};`,
  "",
].join("\n"));

// ── Report ────────────────────────────────────────────────────────────────────
for (const { group, rows } of loaded) console.log(`${group.label}: ${rows.length} vendors validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
console.log(`  → ${path.relative(ROOT, OUT_SCHEMAS)}`);
