/**
 * Notification-route catalogue generator.
 *
 * Routes are authored as one JSON file per route under
 * lib/backend-catalogue/assets/notification-routes/<id>.json. Validates each
 * against assets/schema/notification-route.schema.json (via the shared gen-registry
 * engine) and emits the portable lib/backend-catalogue/src/notification-routes.generated.ts
 * — the same generate-and-drift-guard pattern as gen-views.
 *
 * Run: pnpm --filter @workspace/scripts run gen-notification-routes
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";
import { loadGroup, emitRegistry, type AssetGroup } from "./lib/gen-registry";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/notification-routes.generated.ts");

const group: AssetGroup = {
  dir: path.join(ASSETS, "notification-routes"),
  schema: JSON.parse(fs.readFileSync(path.join(ASSETS, "schema/notification-route.schema.json"), "utf8")) as JsonSchema,
  label: "notification-routes",
  constName: "ROUTES_DATA",
  typeName: "NotificationRoute",
  typeModule: "./notification-routing",
};

const rows = loadGroup(group);
emitRegistry(OUT_TS, [
  "/* GENERATED by scripts/src/gen-notification-routes.ts — do not edit.",
  "   Routes are authored as JSON under lib/backend-catalogue/assets/notification-routes/;",
  "   run `pnpm --filter @workspace/scripts run gen-notification-routes` to regenerate. */",
], [{ group, rows }]);

console.log(`notification-routes: ${rows.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
