/**
 * Widget catalogue generator.
 *
 * Dashboard widgets are authored as one JSON file per widget under
 * lib/backend-catalogue/assets/widgets/<type>.json. Validates each against
 * assets/schema/widget.schema.json (via the shared gen-registry engine) and emits
 * lib/backend-catalogue/src/widgets.generated.ts — the same generate-and-drift-guard
 * pattern as gen-reports / gen-views.
 *
 * Run: pnpm --filter @workspace/scripts run gen-widgets
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type JsonSchema } from "../../lib/backend-catalogue/src/vendor-schema";
import { loadGroup, emitRegistry, type AssetGroup } from "./lib/gen-registry";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const ASSETS = path.join(ROOT, "lib/backend-catalogue/assets");
const OUT_TS = path.join(ROOT, "lib/backend-catalogue/src/widgets.generated.ts");

const group: AssetGroup = {
  dir: path.join(ASSETS, "widgets"),
  schema: JSON.parse(fs.readFileSync(path.join(ASSETS, "schema/widget.schema.json"), "utf8")) as JsonSchema,
  label: "widgets",
  constName: "WIDGETS_DATA",
  typeName: "WidgetDefinition",
  typeModule: "./widget-catalogue",
  idField: "type",
};

const rows = loadGroup(group);
emitRegistry(OUT_TS, [
  "/* GENERATED by scripts/src/gen-widgets.ts — do not edit.",
  "   Widgets are authored as JSON under lib/backend-catalogue/assets/widgets/;",
  "   run `pnpm --filter @workspace/scripts run gen-widgets` to regenerate. */",
], [{ group, rows }]);

console.log(`widgets: ${rows.length} validated`);
console.log(`  → ${path.relative(ROOT, OUT_TS)}`);
