import { securityFindings, type SecurityFinding } from "../../../artifacts/api-server/src/lib/security-check";

/**
 * Deployment config model + pure generators for the first-run setup wizard.
 *
 * This module is PURE and unit-tested: given an operator's choices it renders a
 * `.env` and a known-good `docker-compose.yml`. The interactive TUI (wizard.ts)
 * is a thin readline shell that builds a `DeployConfig` and calls these — exactly
 * the "pure formatter + thin shell" split used elsewhere (lib/metrics.ts).
 *
 * The generated compose mirrors the vetted reference files
 * (docker-compose.enterprise.yml / .standalone.yml) so the output is genuinely
 * deployable, not a sketch: same images, healthchecks, hardening
 * (no-new-privileges, read-only shell, loopback port binding).
 */

export type AiProvider = "none" | "openai" | "openrouter" | "anthropic" | "ollama";

export type IdpChoice =
  | { kind: "none" } // demo auth — everyone admin; dev/eval only
  | { kind: "oidc"; issuerUrl: string; clientId: string; clientSecret: string }
  | { kind: "authentik-bundled"; pgPassword: string; secretKey: string; clientId: string; clientSecret: string; issuerUrl: string };

export interface DeployConfig {
  /** External https origin the shell is served behind (OIDC redirect base). */
  publicUrl: string;
  port: number;
  sessionSecret: string;
  broker: {
    /** A catalogue id (jira, openproject, …) or "custom" — routing hint only. */
    backendId: string;
    /** Bundle a standalone n8n service, or point BROKER_URL at an external one. */
    bundleN8n: boolean;
    /** Used when bundleN8n is false. */
    brokerUrl: string;
    /** Optional app-layer broker encryption (fallback below TLS). */
    psk?: string;
  };
  idp: IdpChoice;
  ai: { provider: AiProvider; model?: string; apiKey?: string; ollamaUrl?: string };
  /** Optional time-travel/logging snapshot server (the one durable egress). */
  loggingSyncUrl?: string;
  /** Optional shared Redis for multi-replica fan-out. */
  redisUrl?: string;
  /** Bundle a Redis service (implies redisUrl=redis://redis:6379). */
  bundleRedis?: boolean;
}

const INTERNAL_N8N_URL = "http://n8n:5678/webhook/omniproject";
const INTERNAL_REDIS_URL = "redis://redis:6379";

/** The effective broker URL (internal n8n when bundled, else the external one). */
export function effectiveBrokerUrl(c: DeployConfig): string {
  return c.broker.bundleN8n ? INTERNAL_N8N_URL : c.broker.brokerUrl;
}

/** The effective Redis URL (internal when bundled, else the external one). */
export function effectiveRedisUrl(c: DeployConfig): string | undefined {
  return c.bundleRedis ? INTERNAL_REDIS_URL : c.redisUrl?.trim() || undefined;
}

// ── .env rendering ────────────────────────────────────────────────────────────

/** Build the env map the gateway will see (also what we validate). */
export function envMap(c: DeployConfig): Record<string, string> {
  const env: Record<string, string> = {
    NODE_ENV: "production",
    PORT: String(c.port),
    PUBLIC_URL: c.publicUrl,
    SESSION_SECRET: c.sessionSecret,
    BROKER_URL: effectiveBrokerUrl(c),
    BACKEND_SOURCE: c.broker.backendId,
  };
  if (c.broker.psk?.trim()) env["BROKER_PSK"] = c.broker.psk.trim();

  if (c.idp.kind === "oidc" || c.idp.kind === "authentik-bundled") {
    env["OIDC_ISSUER_URL"] = c.idp.issuerUrl;
    env["OIDC_CLIENT_ID"] = c.idp.clientId;
    env["OIDC_CLIENT_SECRET"] = c.idp.clientSecret;
  }
  if (c.idp.kind === "authentik-bundled") {
    env["AUTHENTIK_PG_PASSWORD"] = c.idp.pgPassword;
    env["AUTHENTIK_SECRET_KEY"] = c.idp.secretKey;
  }

  env["AI_PROVIDER"] = c.ai.provider;
  if (c.ai.provider !== "none") {
    if (c.ai.model) env["AI_MODEL"] = c.ai.model;
    if (c.ai.provider === "openai" && c.ai.apiKey) env["OPENAI_API_KEY"] = c.ai.apiKey;
    if (c.ai.provider === "openrouter" && c.ai.apiKey) env["OPENROUTER_API_KEY"] = c.ai.apiKey;
    if (c.ai.provider === "anthropic" && c.ai.apiKey) env["ANTHROPIC_API_KEY"] = c.ai.apiKey;
    if (c.ai.provider === "ollama" && c.ai.ollamaUrl) env["OLLAMA_URL"] = c.ai.ollamaUrl;
  }

  if (c.loggingSyncUrl?.trim()) env["LOGGING_SYNC_URL"] = c.loggingSyncUrl.trim();
  const redis = effectiveRedisUrl(c);
  if (redis) env["REDIS_URL"] = redis;
  return env;
}

/** Render the `.env` file (compose reads it for ${VAR} substitution). */
export function renderEnv(c: DeployConfig): string {
  const env = envMap(c);
  const lines = [
    "# Generated by the OmniProject setup wizard. Review before deploying.",
    "# Secrets are in plaintext here — keep this file out of version control.",
    "",
  ];
  for (const [k, v] of Object.entries(env)) lines.push(`${k}=${v}`);
  if (c.idp.kind === "none") {
    lines.push(
      "",
      "# WARNING: no IdP configured → DEMO AUTH (every user is admin).",
      "# Do NOT use this in production. Re-run the wizard and choose an IdP.",
    );
  }
  return lines.join("\n") + "\n";
}

// ── docker-compose rendering ────────────────────────────────────────────────────

function shellService(c: DeployConfig): string {
  const oidc = c.idp.kind !== "none";
  const redis = !!effectiveRedisUrl(c);
  const dependsOn: string[] = [];
  if (c.broker.bundleN8n) dependsOn.push("    depends_on:\n      n8n:\n        condition: service_healthy");
  const envLines = [
    "      NODE_ENV: production",
    `      PORT: ${c.port}`,
    "      PUBLIC_URL: ${PUBLIC_URL:?set PUBLIC_URL to the external https origin}",
    "      BROKER_URL: ${BROKER_URL}",
    "      BACKEND_SOURCE: ${BACKEND_SOURCE:-all}",
    ...(c.broker.psk ? ["      BROKER_PSK: ${BROKER_PSK:-}"] : []),
    "      SESSION_SECRET: ${SESSION_SECRET:?set SESSION_SECRET (long random string)}",
    ...(oidc
      ? [
          "      OIDC_ISSUER_URL: ${OIDC_ISSUER_URL:?set OIDC_ISSUER_URL (https) to your IdP}",
          "      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:?set OIDC_CLIENT_ID}",
          "      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET:?set OIDC_CLIENT_SECRET}",
        ]
      : []),
    "      AI_PROVIDER: ${AI_PROVIDER:-none}",
    ...(c.ai.provider !== "none" ? ["      AI_MODEL: ${AI_MODEL:-}"] : []),
    ...(c.ai.provider === "openai" ? ["      OPENAI_API_KEY: ${OPENAI_API_KEY:-}"] : []),
    ...(c.ai.provider === "openrouter" ? ["      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}"] : []),
    ...(c.ai.provider === "anthropic" ? ["      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}"] : []),
    ...(c.ai.provider === "ollama" ? ["      OLLAMA_URL: ${OLLAMA_URL:-}"] : []),
    ...(c.loggingSyncUrl ? ["      LOGGING_SYNC_URL: ${LOGGING_SYNC_URL:-}"] : []),
    ...(redis ? ["      REDIS_URL: ${REDIS_URL:-}"] : []),
  ];
  return [
    "  # ── OmniProject shell (SPA + gateway) ───────────────────────────────────────",
    "  omni-shell:",
    "    build:",
    "      context: .",
    "      dockerfile: Dockerfile",
    "    image: omniproject-shell:latest",
    "    container_name: omni-shell",
    "    ports:",
    `      - "127.0.0.1:${c.port}:${c.port}"`,
    "    security_opt:",
    "      - no-new-privileges:true",
    "    cap_drop:",
    "      - ALL",
    "    read_only: true",
    "    tmpfs:",
    "      - /tmp",
    "    environment:",
    ...envLines,
    ...dependsOn,
    "    healthcheck:",
    `      test: ["CMD", "node", "-e", "require('http').get('http://localhost:${c.port}/api/healthz',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"]`,
    "      interval: 10s",
    "      timeout: 3s",
    "      retries: 5",
    "      start_period: 20s",
    "    networks:",
    "      - omni-net",
    "    mem_limit: 512m",
    "    restart: unless-stopped",
  ].join("\n");
}

function n8nService(): string {
  return [
    "  # ── n8n (reference broker) ──────────────────────────────────────────────────",
    "  n8n:",
    "    image: n8nio/n8n:1.123.61",
    "    container_name: omni-n8n",
    "    ports:",
    '      - "127.0.0.1:5678:5678"',
    "    security_opt:",
    "      - no-new-privileges:true",
    "    environment:",
    "      N8N_PORT: 5678",
    "      GENERIC_TIMEZONE: UTC",
    "      DB_TYPE: sqlite",
    "      WEBHOOK_URL: ${N8N_PUBLIC_URL:-http://localhost:5678/}",
    "    volumes:",
    "      - n8n_data:/home/node/.n8n",
    "    healthcheck:",
    `      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5678/healthz',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"]`,
    "      interval: 10s",
    "      timeout: 3s",
    "      retries: 10",
    "      start_period: 20s",
    "    networks:",
    "      - omni-net",
    "    mem_limit: 1g",
    "    restart: unless-stopped",
  ].join("\n");
}

function redisService(): string {
  return [
    "  # ── Redis (multi-replica fan-out + shared rate limit) ───────────────────────",
    "  redis:",
    "    image: redis:7.4-alpine",
    "    container_name: omni-redis",
    "    security_opt:",
    "      - no-new-privileges:true",
    "    command: [\"redis-server\", \"--save\", \"\", \"--appendonly\", \"no\"]",
    "    healthcheck:",
    '      test: ["CMD", "redis-cli", "ping"]',
    "      interval: 10s",
    "      timeout: 3s",
    "      retries: 5",
    "    networks:",
    "      - omni-net",
    "    mem_limit: 256m",
    "    restart: unless-stopped",
  ].join("\n");
}

function authentikServices(): string {
  const pg =
    "      AUTHENTIK_POSTGRESQL__HOST: authentik-postgres\n" +
    "      AUTHENTIK_POSTGRESQL__USER: authentik\n" +
    "      AUTHENTIK_POSTGRESQL__PASSWORD: ${AUTHENTIK_PG_PASSWORD:?set AUTHENTIK_PG_PASSWORD}\n" +
    "      AUTHENTIK_POSTGRESQL__NAME: authentik\n" +
    "      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?set AUTHENTIK_SECRET_KEY (50+ random chars)}";
  return [
    "  # ── Authentik (bundled IdP) ─────────────────────────────────────────────────",
    "  authentik-postgres:",
    "    image: postgres:16.14-alpine",
    "    container_name: omni-authentik-pg",
    "    security_opt:",
    "      - no-new-privileges:true",
    "    environment:",
    "      POSTGRES_DB: authentik",
    "      POSTGRES_USER: authentik",
    "      POSTGRES_PASSWORD: ${AUTHENTIK_PG_PASSWORD:?set AUTHENTIK_PG_PASSWORD}",
    "    volumes:",
    "      - authentik_pg_data:/var/lib/postgresql/data",
    "    healthcheck:",
    '      test: ["CMD-SHELL", "pg_isready -U authentik -d authentik"]',
    "      interval: 10s",
    "      timeout: 3s",
    "      retries: 5",
    "      start_period: 10s",
    "    networks:",
    "      - omni-net",
    "    mem_limit: 512m",
    "    restart: unless-stopped",
    "",
    "  authentik-server:",
    "    image: ghcr.io/goauthentik/server:2026.5.3",
    "    container_name: omni-authentik-server",
    "    command: server",
    "    security_opt:",
    "      - no-new-privileges:true",
    "    environment:",
    pg,
    "      AUTHENTIK_ERROR_REPORTING__ENABLED: \"false\"",
    "    volumes:",
    "      - authentik_media:/media",
    "    depends_on:",
    "      authentik-postgres:",
    "        condition: service_healthy",
    "    healthcheck:",
    '      test: ["CMD", "ak", "healthcheck"]',
    "      interval: 15s",
    "      timeout: 5s",
    "      retries: 10",
    "      start_period: 90s",
    "    networks:",
    "      - omni-net",
    "    mem_limit: 1g",
    "    restart: unless-stopped",
    "",
    "  authentik-worker:",
    "    image: ghcr.io/goauthentik/server:2026.5.3",
    "    container_name: omni-authentik-worker",
    "    command: worker",
    "    security_opt:",
    "      - no-new-privileges:true",
    "    environment:",
    pg,
    "    volumes:",
    "      - authentik_media:/media",
    "    depends_on:",
    "      authentik-postgres:",
    "        condition: service_healthy",
    "    healthcheck:",
    '      test: ["CMD", "ak", "healthcheck"]',
    "      interval: 15s",
    "      timeout: 5s",
    "      retries: 10",
    "      start_period: 90s",
    "    networks:",
    "      - omni-net",
    "    mem_limit: 1g",
    "    restart: unless-stopped",
  ].join("\n");
}

/** Render the full known-good docker-compose.yml for these choices. */
export function renderCompose(c: DeployConfig): string {
  const services = [shellService(c)];
  if (c.broker.bundleN8n) services.push(n8nService());
  if (c.bundleRedis) services.push(redisService());
  if (c.idp.kind === "authentik-bundled") services.push(authentikServices());

  const volumes: string[] = [];
  if (c.broker.bundleN8n) volumes.push("  n8n_data:");
  if (c.idp.kind === "authentik-bundled") volumes.push("  authentik_pg_data:", "  authentik_media:");

  const out = [
    "name: omniproject",
    "",
    "# Generated by the OmniProject setup wizard — a known-good starting point.",
    "# Reads values from the sibling .env. This profile does NOT terminate TLS;",
    "# front it with your own reverse proxy / ingress and set PUBLIC_URL to the",
    "# https origin (the session cookie is Secure in production).",
    "",
    "networks:",
    "  omni-net:",
    "    driver: bridge",
    "",
  ];
  if (volumes.length) out.push("volumes:", ...volumes, "");
  out.push("services:", services.join("\n\n"));
  return out.join("\n") + "\n";
}

// ── Validation (the "guided correctness gate") ──────────────────────────────────

/** Run the gateway's own security self-check against the chosen config so the
 *  wizard can warn BEFORE writing files (e.g. demo-auth, plaintext broker). */
export function validateDeployConfig(c: DeployConfig): SecurityFinding[] {
  return securityFindings(envMap(c));
}
