/**
 * Config export for the Setup wizard.
 *
 * OmniProject stays stateless: the wizard never persists configuration itself.
 * Instead it renders the current (in-memory) settings as durable, copy-paste
 * config in the operator's preferred format, so the *environment* remains the
 * source of truth. Pure + side-effect free so it's unit-tested.
 */

export interface ConfigExportInput {
  n8nWebhookUrl?: string | null;
  backendSource?: string | null;
  aiProvider?: string | null;
  aiModel?: string | null;
  oidcIssuerUrl?: string | null;
  auditLevel?: string | null;
}

export type ExportFormat = "env" | "compose" | "k8s";

interface Entry {
  key: string;
  value: string;
  /** A secret the operator must fill in — rendered as a placeholder + note. */
  placeholder?: boolean;
  comment?: string;
}

/** Resolve the ordered env entries that reproduce the given configuration. */
export function configEntries(input: ConfigExportInput): Entry[] {
  const entries: Entry[] = [];

  entries.push({ key: "PORT", value: "3000", comment: "Port the single-container omni-shell listens on" });

  if (input.n8nWebhookUrl?.trim()) {
    entries.push({ key: "N8N_WEBHOOK_URL", value: input.n8nWebhookUrl.trim(), comment: "The webhook every data action is brokered through" });
  } else {
    entries.push({ key: "N8N_WEBHOOK_URL", value: "https://n8n.example.com/webhook/omniproject", placeholder: true, comment: "Unset = demo mode (sample data)" });
  }

  if (input.backendSource?.trim() && input.backendSource.trim() !== "all") {
    entries.push({ key: "BACKEND_SOURCE", value: input.backendSource.trim(), comment: "Routing hint sent to n8n (default: all)" });
  }

  if (input.aiProvider?.trim() && input.aiProvider.trim() !== "none") {
    entries.push({ key: "AI_PROVIDER", value: input.aiProvider.trim() });
    if (input.aiModel?.trim()) entries.push({ key: "AI_MODEL", value: input.aiModel.trim() });
    entries.push({ key: "AI_API_KEY", value: "", placeholder: true, comment: "API key for the provider (omit for local Ollama)" });
  }

  if (input.oidcIssuerUrl?.trim()) {
    entries.push({ key: "OIDC_ISSUER_URL", value: input.oidcIssuerUrl.trim(), comment: "Set all three OIDC_* to enforce SSO; unset = demo login" });
    entries.push({ key: "OIDC_CLIENT_ID", value: "", placeholder: true });
    entries.push({ key: "OIDC_CLIENT_SECRET", value: "", placeholder: true });
    entries.push({ key: "OIDC_ADMIN_ROLES", value: "", placeholder: true, comment: "Optional: IdP roles/groups mapped to the admin role (also *_MANAGER/_CONTRIBUTOR/_VIEWER)" });
  }

  entries.push({ key: "SESSION_SECRET", value: "", placeholder: true, comment: "Required in production: a long random string for cookie signing" });
  entries.push({ key: "NOTIFY_INGEST_SECRET", value: "", placeholder: true, comment: "Optional: enables real-time notifications — n8n/tools POST /api/notifications/ingest with this bearer" });
  entries.push({ key: "REDIS_URL", value: "", placeholder: true, comment: "Optional (multi-replica HA): Redis Pub/Sub fan-out for real-time notifications. Also install ioredis." });
  entries.push({ key: "AUDIT_LEVEL", value: input.auditLevel || "writes", comment: "Action audit scope: off | writes | all" });
  entries.push({ key: "AUDIT_HTTP_URL", value: "", placeholder: true, comment: "Optional: ship audit events (NDJSON) to a logging server — Loki / Splunk HEC / Elastic / syslog-over-HTTP (+ AUDIT_HTTP_TOKEN)" });

  return entries;
}

function renderEnv(entries: Entry[]): string {
  const lines: string[] = ["# OmniProject configuration — generated by the Setup wizard.", "# Fill in any <PLACEHOLDER> values before deploying.", ""];
  for (const e of entries) {
    if (e.comment) lines.push(`# ${e.comment}`);
    lines.push(`${e.key}=${e.placeholder ? `<${e.key}>` : e.value}`);
  }
  return lines.join("\n") + "\n";
}

function renderCompose(entries: Entry[]): string {
  const lines: string[] = [
    "# docker-compose.yml (excerpt) — OmniProject single-container shell.",
    "services:",
    "  omniproject:",
    "    image: omniproject:latest",
    "    ports:",
    '      - "3000:3000"',
    "    environment:",
  ];
  for (const e of entries) {
    if (e.comment) lines.push(`      # ${e.comment}`);
    lines.push(`      ${e.key}: "${e.placeholder ? `<${e.key}>` : e.value}"`);
  }
  return lines.join("\n") + "\n";
}

function renderK8s(entries: Entry[]): string {
  const lines: string[] = [
    "# Kubernetes ConfigMap — move OIDC_CLIENT_SECRET / SESSION_SECRET to a Secret.",
    "apiVersion: v1",
    "kind: ConfigMap",
    "metadata:",
    "  name: omniproject-config",
    "data:",
  ];
  for (const e of entries) {
    if (e.comment) lines.push(`  # ${e.comment}`);
    lines.push(`  ${e.key}: "${e.placeholder ? `<${e.key}>` : e.value}"`);
  }
  return lines.join("\n") + "\n";
}

export function buildConfigExport(input: ConfigExportInput, format: ExportFormat): string {
  const entries = configEntries(input);
  switch (format) {
    case "compose":
      return renderCompose(entries);
    case "k8s":
      return renderK8s(entries);
    case "env":
    default:
      return renderEnv(entries);
  }
}
