/* GENERATED by scripts/src/gen-contract.ts — do not edit. */
/* The published broker contract, embedded so GET /api/contract has no runtime
   dependency on the docs/ tree. Regenerated in lock-step with the JSON + MD. */
export const BROKER_CONTRACT_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://omniproject.dev/contract/broker.v1.schema.json",
  "title": "OmniProject Broker Contract",
  "description": "The published, versioned interface between OmniProject and any broker. Generated from artifacts/api-server/src/broker/{types,contract}.ts — do not edit by hand.",
  "x-contract-version": "v1",
  "$defs": {
    "ActorContext": {
      "type": "object",
      "properties": {
        "sub": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "role": {
          "type": "string"
        },
        "token": {
          "type": "string"
        },
        "authHeader": {
          "type": "string"
        },
        "sessionBind": {
          "$ref": "#/$defs/SessionBind",
          "description": "Binding material for the per-session broker signing key (lib/session-key). Present for authenticated calls; absent for system/unauthenticated ones (which fall back to the static broker key)."
        },
        "actorKind": {
          "$ref": "#/$defs/ActorKind",
          "description": "What kind of principal this is (default human). Autonomous actors carry their own keyed sessionBind + RBAC role, so they're keyed and provenance-bound too."
        },
        "scope": {
          "$ref": "#/$defs/Scope",
          "description": "The principal's forwarded DATA scope (user / programme / all) — the backend confirms it (it rides in the PSK-signed envelope) and enforces per-user/per-programme access."
        },
        "issuedAt": {
          "type": "number",
          "description": "For a minted autonomous principal: the invocation time it was minted for (epoch ms), so a consumer can prove it's fresh and not a replayed/cached context."
        },
        "expiresAt": {
          "type": "number",
          "description": "For a minted autonomous principal: its (short) expiry — autonomous sessions are deliberately brief since re-keying is free."
        }
      },
      "additionalProperties": false,
      "description": "Forwarded actor identity. A write is performed \"as\" this principal so the backend system of record authorises it under the real user (not a shared admin key). `authHeader` is the transport credential to forward; `token` is the same access token echoed in the per-user context. Demo brokers ignore both."
    },
    "ActorKind": {
      "enum": [
        "human",
        "automation",
        "agent"
      ],
      "description": "Who initiated an action. Autonomous actors (scheduled jobs, AI agents) are first-class principals — keyed, RBAC-roled and provenance-bound like a human."
    },
    "Annotation": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Stable id within the proof (for keys + comment-thread anchoring)."
        },
        "type": {
          "$ref": "#/$defs/AnnotationType"
        },
        "x": {
          "type": "number",
          "description": "Normalised top-left / point position on the deliverable (0..1)."
        },
        "y": {
          "type": "number"
        },
        "w": {
          "type": "number",
          "description": "Normalised region size — box / highlight (0..1)."
        },
        "h": {
          "type": "number"
        },
        "text": {
          "type": "string",
          "description": "The reviewer's note."
        },
        "page": {
          "type": "number",
          "description": "Which page of a multi-page deliverable (PDF) this pins to (1-based)."
        },
        "resolved": {
          "type": "boolean",
          "description": "Whether the raised point has been addressed."
        }
      },
      "required": [
        "id",
        "type",
        "x",
        "y"
      ],
      "additionalProperties": false,
      "description": "One annotation pinned onto a deliverable. Which optional fields apply depends on `type`: a `pin` uses just `x`/`y`; a `box`/`highlight` adds `w`/`h`. `text` is the reviewer's note; `resolved` marks a raised point as addressed. `page` targets a page of a multi-page PDF (1-based; defaults to 1). A generic overlay renderer switches on `type`. All coordinates are normalised (0..1)."
    },
    "AnnotationType": {
      "enum": [
        "pin",
        "box",
        "highlight"
      ],
      "description": "The supported annotation types. `pin` — a point marker at (x, y); `box` — a rectangular region (x, y + w, h); `highlight` — a rectangular emphasis region. Coordinates are NORMALISED to the deliverable (0..1 of its width/height), so an annotation survives any render scale."
    },
    "BackendFieldMap": {
      "type": "object",
      "properties": {
        "fields": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/FieldSupport"
          }
        },
        "entities": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/FieldSupport"
          }
        }
      },
      "required": [
        "fields",
        "entities"
      ],
      "additionalProperties": false,
      "description": "Per-field / per-entity support a backend declares. Finer-grained than the domain flags: e.g. a backend may surface `dueDate` read-only (surface without store), or have no `programmeId` field at all (programme entity unsupported)."
    },
    "Baseline": {
      "type": "object",
      "properties": {
        "projectId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "capturedAt": {
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "issueId": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "plannedStart": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "plannedFinish": {
                "type": [
                  "string",
                  "null"
                ]
              }
            },
            "required": [
              "issueId",
              "title",
              "plannedStart",
              "plannedFinish"
            ],
            "additionalProperties": false
          }
        },
        "provenance": {
          "enum": [
            "sourced",
            "derived",
            "sample"
          ]
        }
      },
      "required": [
        "projectId",
        "capturedAt",
        "items",
        "provenance"
      ],
      "additionalProperties": false
    },
    "BrokerEnvelope": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "data": {},
        "message": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "success"
      ],
      "additionalProperties": false,
      "description": "The wire envelope an HTTP-transport broker returns. The gateway unwraps it before anything above the seam sees data; a bare body (no `success` key) is treated as `{ success: true, data: <body> }`. In-process brokers (DemoBroker) return domain values directly and never construct an envelope — the envelope is the reference HTTP binding, not a domain concept."
    },
    "BrokerErrorCode": {
      "enum": [
        "conflict",
        "not_found",
        "unauthorized",
        "bad_request",
        "rate_limited",
        "unavailable"
      ],
      "description": "Normalised error taxonomy — no broker-specific status quirks leak upward."
    },
    "CalloutTone": {
      "enum": [
        "info",
        "warn",
        "success",
        "danger"
      ],
      "description": "The tones a `callout` block can carry."
    },
    "CanvasElement": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Stable id within the scene (for keys, connector binding, live-cursor anchoring)."
        },
        "type": {
          "$ref": "#/$defs/CanvasElementType"
        },
        "x": {
          "type": "number",
          "description": "Top-left position on the infinite canvas."
        },
        "y": {
          "type": "number"
        },
        "w": {
          "type": "number",
          "description": "Box size — sticky / shape / frame."
        },
        "h": {
          "type": "number"
        },
        "text": {
          "type": "string",
          "description": "Text — a sticky's note, a shape's label, a text element's body, a frame's label."
        },
        "color": {
          "$ref": "#/$defs/StickyColor",
          "description": "Sticky colour."
        },
        "shape": {
          "$ref": "#/$defs/ShapeKind",
          "description": "Shape kind."
        },
        "fontSize": {
          "type": "number",
          "description": "Text size for a `text` element."
        },
        "x2": {
          "type": "number",
          "description": "Connector end point (its start is `x`/`y`)."
        },
        "y2": {
          "type": "number"
        },
        "from": {
          "type": "string",
          "description": "Optional connector endpoints bound to element ids (so the line follows them)."
        },
        "to": {
          "type": "string"
        },
        "points": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "number"
            }
          },
          "description": "Freehand path points for a `draw` element — `[x, y]` pairs relative to `x`/`y` (the stroke origin)."
        },
        "strokeWidth": {
          "type": "number",
          "description": "Stroke width (draw) / border weight."
        },
        "link": {
          "type": "string",
          "description": "Optional external reference (safe scheme only) — the content lives elsewhere (zero-at-rest)."
        }
      },
      "required": [
        "id",
        "type",
        "x",
        "y"
      ],
      "additionalProperties": false,
      "description": "One element on a whiteboard. Which optional fields apply depends on `type`: `sticky` uses text+color+box; `shape` uses shape+box (+optional text label); `text` uses text+fontSize; `connector` uses the end point `x2/y2` (start is `x/y`) and may bind to element ids via `from`/`to`; `frame` uses text (its label)+box. A generic renderer switches on `type`. `link` (any type) is an OPTIONAL external reference — e.g. a sticky that links to a work item — restricted to safe schemes by the sanitiser (zero-at-rest, never inlined)."
    },
    "CanvasElementType": {
      "enum": [
        "sticky",
        "shape",
        "text",
        "connector",
        "frame",
        "draw"
      ],
      "description": "The supported canvas element types. `sticky` — a coloured sticky note (the staple); `shape` — a rectangle/ellipse/diamond (optionally labelled); `text` — free-standing text; `connector` — a line/arrow between two points or elements; `frame` — a labelled grouping container."
    },
    "CapabilityFlags": {
      "type": "object",
      "additionalProperties": {
        "type": "boolean"
      },
      "description": "Raw capability flags a backend can populate (domain → available)."
    },
    "ContractVersion": {
      "const": "v1"
    },
    "Deliverable": {
      "type": "object",
      "properties": {
        "kind": {
          "$ref": "#/$defs/DeliverableKind"
        },
        "url": {
          "type": "string",
          "description": "Safe-scheme URL of the media (validated by the sanitiser)."
        },
        "label": {
          "type": "string",
          "description": "Optional human label / filename."
        }
      },
      "required": [
        "kind",
        "url"
      ],
      "additionalProperties": false,
      "description": "A deliverable under review — a REFERENCE to media that lives elsewhere (never inlined; zero-at-rest)."
    },
    "DeliverableKind": {
      "enum": [
        "image",
        "pdf"
      ],
      "description": "The deliverable media kinds a proof can reference."
    },
    "DocBlock": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Stable id within the document (for keys, presence anchoring, comment threading)."
        },
        "type": {
          "$ref": "#/$defs/DocBlockType"
        },
        "text": {
          "type": "string",
          "description": "Free text for a text block (heading/paragraph/quote/callout/code)."
        },
        "level": {
          "type": "number",
          "description": "Heading level (1–3); defaulted to 2 when omitted."
        },
        "tone": {
          "$ref": "#/$defs/CalloutTone",
          "description": "Callout tone."
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DocListItem"
          },
          "description": "Items for a list block."
        },
        "rows": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "description": "Rows of cells for a `table` block."
        },
        "url": {
          "type": "string",
          "description": "External reference for an `embed` block (the content lives elsewhere — zero-at-rest)."
        },
        "caption": {
          "type": "string",
          "description": "Optional caption for an `embed`."
        }
      },
      "required": [
        "id",
        "type"
      ],
      "additionalProperties": false,
      "description": "One block in a document. Which optional fields apply depends on `type`: text blocks use `text`; `heading` adds `level`; `callout` adds `tone`; list blocks use `items`; `table` uses `rows`; `embed` uses `url` (+ optional `caption`). A generic renderer switches on `type`."
    },
    "DocBlockType": {
      "enum": [
        "heading",
        "paragraph",
        "quote",
        "callout",
        "code",
        "bullet-list",
        "numbered-list",
        "checklist",
        "divider",
        "table",
        "embed"
      ],
      "description": "The supported document block types. Text-bearing: `heading` (with a level), `paragraph`, `quote`, `callout` (with a tone), `code`. Lists: `bullet-list`, `numbered-list`, `checklist` (items may be checked). Structural: `divider`, `table` (a grid of cells), `embed` (a REFERENCE to external content by URL — zero-at-rest, never inlined bytes)."
    },
    "DocListItem": {
      "type": "object",
      "properties": {
        "text": {
          "type": "string"
        },
        "checked": {
          "type": "boolean"
        }
      },
      "required": [
        "text"
      ],
      "additionalProperties": false,
      "description": "One item in a list block. `checked` only applies to a `checklist`."
    },
    "EnumeratedField": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "surface": {
          "type": "boolean"
        },
        "store": {
          "type": "boolean"
        },
        "references": {
          "type": "string",
          "description": "If the backend's API schema says this field references another entity."
        },
        "sourceSystem": {
          "type": "string",
          "description": "The system of record this field is read from (e.g. \"jira\", \"openproject\"). Lets the UI show granular lineage: \"this canonical field ← that backend.\""
        },
        "sourceField": {
          "type": "string",
          "description": "The backend's NATIVE field name/id this canonical field maps from (e.g. \"duedate\", \"customfield_10016\") — supplied by the broker/workflow, so the overlay can say exactly which backend field a value came from."
        },
        "maxLength": {
          "type": "number",
          "description": "Max character length the backend accepts for this field."
        },
        "precision": {
          "type": "number",
          "description": "Decimal places for a numeric/currency/percent field."
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Allowed values for an enum field."
        },
        "pattern": {
          "type": "string",
          "description": "A regular expression the value must match (postcode/email/date shapes). ReDoS-guarded before use."
        },
        "nullable": {
          "type": "boolean",
          "description": "Whether the backend accepts an empty value (⇒ the UI field is optional)."
        }
      },
      "required": [
        "key"
      ],
      "additionalProperties": false,
      "description": "A field a backend reports it can expose, from API enumeration during wiring."
    },
    "FieldSupport": {
      "type": "object",
      "properties": {
        "surface": {
          "type": "boolean"
        },
        "store": {
          "type": "boolean"
        }
      },
      "required": [
        "surface",
        "store"
      ],
      "additionalProperties": false,
      "description": "Whether a field/entity can be surfaced (read) and stored (written)."
    },
    "FxRates": {
      "type": "object",
      "properties": {
        "base": {
          "type": "string"
        },
        "rates": {
          "type": "object",
          "additionalProperties": {
            "type": "number"
          }
        },
        "provenance": {
          "enum": [
            "sourced",
            "sample"
          ]
        },
        "asOf": {
          "type": "string"
        }
      },
      "required": [
        "base",
        "rates",
        "provenance",
        "asOf"
      ],
      "additionalProperties": false
    },
    "HistoryPoint": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string"
        },
        "completionRate": {
          "type": "number"
        },
        "totalIssues": {
          "type": "number"
        },
        "completedIssues": {
          "type": "number"
        },
        "openBlockers": {
          "type": [
            "number",
            "null"
          ]
        },
        "provenance": {
          "enum": [
            "sourced",
            "derived",
            "sample"
          ]
        }
      },
      "required": [
        "date",
        "completionRate",
        "totalIssues",
        "completedIssues",
        "openBlockers",
        "provenance"
      ],
      "additionalProperties": false
    },
    "HistoryState": {
      "type": "object",
      "properties": {
        "at": {
          "type": "string"
        },
        "completionPct": {
          "type": "number"
        },
        "openBlockers": {
          "type": [
            "number",
            "null"
          ]
        },
        "provenance": {
          "enum": [
            "replayed",
            "projected",
            "sourced",
            "derived",
            "sample"
          ]
        }
      },
      "required": [
        "at",
        "completionPct",
        "openBlockers",
        "provenance"
      ],
      "additionalProperties": false,
      "description": "A portfolio-level state at a point in time, served by the time-travel replay (read back from the operator's logging server). `replayed` = a real recorded state; `projected` = a model of the future (never fact); `sample` = demo."
    },
    "IngestedNotification": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "body": {
          "type": [
            "string",
            "null"
          ]
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ]
        },
        "issueId": {
          "type": [
            "string",
            "null"
          ]
        },
        "read": {
          "type": "boolean"
        },
        "timestamp": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "kind",
        "title",
        "body",
        "projectId",
        "issueId",
        "read",
        "timestamp"
      ],
      "additionalProperties": false,
      "description": "The normalised notification the gateway fans out after ingest."
    },
    "Issue": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "projectId": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "version": {
          "type": "number"
        },
        "budget": {
          "type": [
            "number",
            "null"
          ]
        },
        "actualCost": {
          "type": [
            "number",
            "null"
          ]
        },
        "billable": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "costCenter": {
          "type": [
            "string",
            "null"
          ]
        },
        "currency": {
          "type": [
            "string",
            "null"
          ]
        },
        "estimateHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "loggedHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "remainingHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "storyPoints": {
          "type": [
            "number",
            "null"
          ]
        },
        "healthStatus": {
          "type": [
            "string",
            "null"
          ]
        },
        "riskLevel": {
          "type": [
            "string",
            "null"
          ]
        },
        "impact": {
          "type": [
            "string",
            "null"
          ]
        },
        "urgency": {
          "type": [
            "string",
            "null"
          ]
        },
        "blocked": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "blockedReason": {
          "type": [
            "string",
            "null"
          ]
        },
        "mitigation": {
          "type": [
            "string",
            "null"
          ]
        },
        "defectCount": {
          "type": [
            "number",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "projectId",
        "title",
        "status"
      ],
      "additionalProperties": true,
      "description": "A normalised issue/work-item row. `version` is the concurrency token."
    },
    "IssueWrite": {
      "type": "object",
      "properties": {
        "projectId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": [
            "string",
            "null"
          ]
        },
        "status": {
          "type": "string"
        },
        "priority": {
          "type": "string"
        },
        "assignee": {
          "type": [
            "string",
            "null"
          ]
        },
        "labels": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "startDate": {
          "type": [
            "string",
            "null"
          ]
        },
        "dueDate": {
          "type": [
            "string",
            "null"
          ]
        },
        "budget": {
          "type": [
            "number",
            "null"
          ]
        },
        "actualCost": {
          "type": [
            "number",
            "null"
          ]
        },
        "billable": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "costCenter": {
          "type": [
            "string",
            "null"
          ]
        },
        "currency": {
          "type": [
            "string",
            "null"
          ]
        },
        "estimateHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "loggedHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "remainingHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "storyPoints": {
          "type": [
            "number",
            "null"
          ]
        },
        "healthStatus": {
          "type": [
            "string",
            "null"
          ]
        },
        "riskLevel": {
          "type": [
            "string",
            "null"
          ]
        },
        "impact": {
          "type": [
            "string",
            "null"
          ]
        },
        "urgency": {
          "type": [
            "string",
            "null"
          ]
        },
        "blocked": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "blockedReason": {
          "type": [
            "string",
            "null"
          ]
        },
        "mitigation": {
          "type": [
            "string",
            "null"
          ]
        },
        "defectCount": {
          "type": [
            "number",
            "null"
          ]
        },
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "projectId"
      ],
      "additionalProperties": false,
      "description": "A normalised issue mutation. `expectedVersion` drives optimistic concurrency."
    },
    "NativeContextRef": {
      "type": "object",
      "properties": {
        "projectId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "entity": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "description": "Anchor: WHAT OmniProject entity the native surface is bound to, so a reimport attaches back."
    },
    "NativeHandoff": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string"
        },
        "embedUrl": {
          "type": "string"
        },
        "handoffId": {
          "type": "string"
        }
      },
      "required": [
        "url",
        "handoffId"
      ],
      "additionalProperties": false,
      "description": "The vetted, connector-minted handoff. `url` is built by the connector against the vendor's REAL domain (host-allowlisted) — never from user input. `embedUrl` is the vendor's sandboxed Live-Embed, if any."
    },
    "NativeHandoffRequest": {
      "type": "object",
      "properties": {
        "kind": {
          "$ref": "#/$defs/NativeSurfaceKind"
        },
        "vendor": {
          "type": "string"
        },
        "action": {
          "enum": [
            "open",
            "create",
            "embed"
          ]
        },
        "contextRef": {
          "$ref": "#/$defs/NativeContextRef"
        },
        "externalRef": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "vendor",
        "action"
      ],
      "additionalProperties": false
    },
    "NativeImportRequest": {
      "type": "object",
      "properties": {
        "kind": {
          "$ref": "#/$defs/NativeSurfaceKind"
        },
        "vendor": {
          "type": "string"
        },
        "handoffId": {
          "type": "string"
        },
        "externalRef": {
          "type": "string"
        },
        "target": {
          "type": "object",
          "properties": {
            "projectId": {
              "type": "string"
            },
            "issueId": {
              "type": "string"
            }
          },
          "required": [
            "projectId"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "kind",
        "vendor",
        "target"
      ],
      "additionalProperties": false
    },
    "NativeSurface": {
      "type": "object",
      "properties": {
        "kind": {
          "$ref": "#/$defs/NativeSurfaceKind"
        },
        "vendor": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "actions": {
          "type": "array",
          "items": {
            "enum": [
              "open",
              "create",
              "embed"
            ]
          }
        },
        "importMode": {
          "enum": [
            "reference",
            "content",
            "screenshot"
          ],
          "description": "How the artifact comes back: \"reference\" (a bare link; always available, zero-at-rest), \"content\" (pull data via the vendor API), or \"screenshot\" (capture + AI vision)."
        }
      },
      "required": [
        "kind",
        "vendor",
        "label",
        "actions",
        "importMode"
      ],
      "additionalProperties": false,
      "description": "What a connected backend advertises it can do natively for a given artifact kind. Pure metadata — no secrets, no URLs (URLs are minted per-request by `nativeHandoff`, host-allowlisted server-side)."
    },
    "NativeSurfaceKind": {
      "enum": [
        "whiteboard",
        "document",
        "diagram",
        "sheet",
        "board",
        "schedule",
        "dashboard",
        "report",
        "form",
        "wiki"
      ],
      "description": "An artifact kind OmniProject renders inline and a backend can front NATIVELY (Miro, Notion, …). Matches our primitive/artifact kinds so the SPA can offer \"Use native\" on the right surfaces."
    },
    "NotificationIngest": {
      "type": "object",
      "properties": {
        "target": {
          "type": "object",
          "properties": {
            "sub": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "role": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "notification": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "kind": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "body": {
              "type": [
                "string",
                "null"
              ]
            },
            "projectId": {
              "type": [
                "string",
                "null"
              ]
            },
            "issueId": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "title"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "notification"
      ],
      "additionalProperties": false,
      "description": "Body of POST /api/notifications/ingest — a broker/tool pushes an event in. Authenticated by the NOTIFY_INGEST_SECRET shared secret (Bearer or X-Notify-Secret header). `notification.title` is the only required field."
    },
    "OutboundEvent": {
      "type": "object",
      "properties": {
        "event": {
          "$ref": "#/$defs/OutboundEventName"
        },
        "deliveredAt": {
          "type": "string"
        },
        "deliveryId": {
          "type": "string"
        },
        "data": {}
      },
      "required": [
        "event",
        "deliveredAt",
        "deliveryId",
        "data"
      ],
      "additionalProperties": false,
      "description": "The JSON body of every outbound delivery."
    },
    "OutboundEventName": {
      "enum": [
        "notification",
        "audit",
        "config.changed",
        "webhook.test"
      ]
    },
    "PortfolioRow": {
      "type": "object",
      "properties": {
        "projectId": {
          "type": "string"
        },
        "projectName": {
          "type": "string"
        },
        "ragStatus": {
          "type": "string"
        },
        "scheduleVarianceDays": {
          "type": "number"
        },
        "budgetVariancePercentage": {
          "type": "number"
        },
        "activeBlockersCount": {
          "type": "number"
        }
      },
      "required": [
        "projectId",
        "projectName",
        "ragStatus",
        "scheduleVarianceDays",
        "budgetVariancePercentage",
        "activeBlockersCount"
      ],
      "additionalProperties": false
    },
    "Project": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "status": {
          "type": [
            "string",
            "null"
          ],
          "description": "The backend's native project lifecycle status (kept verbatim, like `Issue.status`). Classified into live/closed by `isProjectLive` (broker/vocabulary); reads are default-live. Absent ⇒ live."
        },
        "omniInstanceId": {
          "type": "string",
          "description": "OmniProject instance ID — a GUID minted by the gateway when the project is created, echoed and stored by every backend. It is the backend-INDEPENDENT correlation key: the same project seen through two backends carries the same `omniInstanceId`, so records assemble across backends by it (whereas `source:id` is unique per backend). Optional because pre-existing rows may lack one."
        }
      },
      "required": [
        "id",
        "name"
      ],
      "additionalProperties": true,
      "description": "A normalised project row."
    },
    "ProjectMember": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "email": {
          "type": [
            "string",
            "null"
          ]
        },
        "access": {
          "enum": [
            "read",
            "write"
          ],
          "description": "\"write\" = can be assigned/act on work; \"read\" = view-only."
        },
        "skills": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Skills/competencies, when the backend tracks them (resource planning)."
        },
        "availableHours": {
          "type": [
            "number",
            "null"
          ],
          "description": "Available capacity in hours for the planning window, when tracked."
        },
        "allocatedHours": {
          "type": [
            "number",
            "null"
          ],
          "description": "Already-allocated hours in the planning window, when tracked."
        }
      },
      "required": [
        "id",
        "access"
      ],
      "additionalProperties": true,
      "description": "A person on a project, with their access level (the backend is the source)."
    },
    "ProjectWrite": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "identifier": {
          "type": [
            "string",
            "null"
          ]
        },
        "description": {
          "type": [
            "string",
            "null"
          ]
        },
        "programmeId": {
          "type": [
            "string",
            "null"
          ],
          "description": "Set/clear to group the project under a programme (derived-programme model)."
        },
        "omniInstanceId": {
          "type": "string",
          "description": "The gateway-minted correlation GUID, passed to the backend to store on create (never sent by a client). See `Project.omniInstanceId`."
        },
        "status": {
          "type": [
            "string",
            "null"
          ],
          "description": "The project's lifecycle status (backend-native string). Set/clear to move a project between live and closed. See `Project.status`."
        }
      },
      "additionalProperties": false,
      "description": "A normalised project create/update. `name` is required on create."
    },
    "Proof": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ]
        },
        "ownerSub": {
          "type": [
            "string",
            "null"
          ]
        },
        "storage": {
          "enum": [
            "user",
            "project",
            "org"
          ],
          "description": "Where the proof lives: user / project / org (encrypted-JSON) — the id also encodes this."
        },
        "deliverable": {
          "$ref": "#/$defs/Deliverable",
          "description": "The deliverable under review — a safe-scheme reference (zero-at-rest)."
        },
        "version": {
          "type": "number",
          "description": "Bumps when the deliverable is replaced; a review decision is bound to the version it was made against."
        },
        "annotations": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Annotation"
          }
        },
        "decision": {
          "$ref": "#/$defs/ProofDecision",
          "description": "The current review decision, and who/when — stamped server-side, never from the client."
        },
        "decisionVersion": {
          "type": "number"
        },
        "decidedBy": {
          "type": [
            "string",
            "null"
          ]
        },
        "decidedAt": {
          "type": [
            "string",
            "null"
          ]
        },
        "updatedAt": {
          "type": "string"
        },
        "updatedBy": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "name",
        "deliverable",
        "version",
        "annotations",
        "decision",
        "updatedAt"
      ],
      "additionalProperties": true,
      "description": "A PROOF — a deliverable (image/PDF, referenced not inlined) under creative review (roadmap 2.4). Carries a list of typed `annotation`-family primitives pinned onto it and a review decision bound to the current version. Held in the encrypted-JSON store (storage-target model), like a whiteboard."
    },
    "ProofDecision": {
      "enum": [
        "pending",
        "approved",
        "rejected",
        "changes-requested"
      ],
      "description": "A review decision on a proof version. `pending` — awaiting review; `approved` — signed off; `rejected` — declined; `changes-requested` — needs rework before re-review. Bound to a version so a new deliverable revision re-opens the decision."
    },
    "ProofMeta": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ]
        },
        "ownerSub": {
          "type": [
            "string",
            "null"
          ]
        },
        "storage": {
          "enum": [
            "user",
            "project",
            "org"
          ]
        },
        "version": {
          "type": "number"
        },
        "decision": {
          "$ref": "#/$defs/ProofDecision"
        },
        "updatedAt": {
          "type": "string"
        },
        "updatedBy": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "name",
        "version",
        "decision",
        "updatedAt"
      ],
      "additionalProperties": false,
      "description": "A proof's metadata (no annotations/deliverable body) — the list view."
    },
    "ProofWrite": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ]
        },
        "deliverable": {
          "$ref": "#/$defs/Deliverable"
        },
        "annotations": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Annotation"
          }
        }
      },
      "required": [
        "name",
        "deliverable",
        "annotations"
      ],
      "additionalProperties": false,
      "description": "A proof write (create/update) — the sanitised, client-supplied fields (decision is set via its own route)."
    },
    "Provenance": {
      "enum": [
        "sourced",
        "derived",
        "sample",
        "replayed",
        "projected"
      ]
    },
    "ResourceMember": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "email": {
          "type": [
            "string",
            "null"
          ]
        },
        "skills": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Union of skills seen across the member's projects."
        },
        "availableHours": {
          "type": [
            "number",
            "null"
          ],
          "description": "Summed capacity across projects (null when no backend supplies it)."
        },
        "allocatedHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "projectIds": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Projects this person is a member of."
        }
      },
      "required": [
        "id",
        "skills",
        "availableHours",
        "allocatedHours",
        "projectIds"
      ],
      "additionalProperties": false,
      "description": "A person aggregated across the portfolio, for resource planning."
    },
    "Row": {
      "type": "object",
      "additionalProperties": {},
      "description": "Loosely-typed record — the normalised row shape the broker exchanges."
    },
    "SchemaManifest": {
      "type": "object",
      "properties": {
        "tables": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Canonical entity keys (tables) present, e.g. [\"project\", \"issue\", \"programme\"]."
        },
        "fields": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Canonical field keys present in the schema (a subset of the superset)."
        },
        "relationships": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "from": {
                "type": "string"
              },
              "field": {
                "type": "string"
              },
              "to": {
                "type": "string"
              }
            },
            "required": [
              "from",
              "field",
              "to"
            ],
            "additionalProperties": false
          },
          "description": "Foreign-key/relationship edges between entities."
        },
        "populated": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Canonical field keys that actually hold data — a subset of `fields`. When given, the gateway surfaces only these (\"populated, not just possible\"); when omitted, all `fields` are surfaced."
        }
      },
      "required": [
        "tables",
        "fields",
        "relationships"
      ],
      "additionalProperties": false,
      "description": "A backend's self-describing SCHEMA manifest — the tables, canonical fields and relationships it actually holds, plus which fields are POPULATED (have data). Returned by the optional `describeSchema`. Only a backend that owns its schema can answer this — in practice OmniProject's own stateful self-host database. Ordinary SaaS backends (the stateless-overlay default) do NOT implement it; the gateway then falls back to the static capability flags. The gateway uses it to surface only what a backend genuinely has (superset ∩ manifest)."
    },
    "Scope": {
      "type": "object",
      "properties": {
        "level": {
          "$ref": "#/$defs/ScopeLevel"
        },
        "sub": {
          "type": "string",
          "description": "The owning principal (used for user-level ownership/membership checks)."
        },
        "programmes": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The programmes this principal may act within (used for programme-level checks)."
        },
        "projectId": {
          "type": "string",
          "description": "The single project a `project`-level (guest) principal is confined to."
        }
      },
      "required": [
        "level"
      ],
      "additionalProperties": false
    },
    "ScopeLevel": {
      "enum": [
        "user",
        "programme",
        "project",
        "all"
      ],
      "description": "DATA scope — the per-principal authorization boundary the backend enforces on top of the coarse RBAC tier. The gateway resolves it from the user's grants + claim/SCIM groups and forwards it (verified, inside the PSK-signed broker envelope) as part of `userContext`, so the system of record can confirm-and-enforce it: - `all` — pmo / admin: every project and programme. - `programme` — a programme manager: only projects in their owned programmes. In a \"basic\" (no-IdP) deployment `programmes` is empty and the backend maps `sub → owned programmes` from its own records instead. - `user` — a standard user: only resources they own or are a member of. - `project` — a GUEST principal (client-facing portal): exactly ONE project, nothing else. The narrowest scope; a guest can't even see the rest of its programme. This module is PURE (no request/IO) so it is the shared contract: the gateway resolves + forwards it, an in-repo backend (or an external n8n one) enforces it with the same helpers."
    },
    "SessionBind": {
      "type": "object",
      "properties": {
        "sub": {
          "type": "string",
          "description": "The acting subject (username) the key is bound to."
        },
        "smono": {
          "type": "string",
          "description": "Monotonic-clock reading (ns string) at session creation."
        },
        "salt": {
          "type": "string",
          "description": "Per-session CSPRNG entropy (hex)."
        },
        "bkver": {
          "type": "number",
          "description": "Broker-key version the session key was derived under (for revocation/rotation)."
        }
      },
      "required": [
        "sub",
        "smono",
        "salt"
      ],
      "additionalProperties": false,
      "description": "The non-secret material needed to re-derive a session's broker key."
    },
    "ShapeKind": {
      "enum": [
        "rectangle",
        "ellipse",
        "diamond"
      ],
      "description": "The shapes a `shape` element can be."
    },
    "StickyColor": {
      "enum": [
        "yellow",
        "green",
        "blue",
        "pink",
        "gray"
      ],
      "description": "The palette of sticky-note colours (named, not raw hex — so the renderer owns the actual values)."
    },
    "Summary": {
      "type": "object",
      "properties": {
        "projectId": {
          "type": "string"
        },
        "total": {
          "type": "number"
        },
        "byStatus": {
          "type": "object",
          "additionalProperties": {
            "type": "number"
          }
        },
        "byPriority": {
          "type": "object",
          "additionalProperties": {
            "type": "number"
          }
        },
        "completionRate": {
          "type": "number"
        },
        "overdue": {
          "type": "number"
        }
      },
      "required": [
        "projectId",
        "total",
        "byStatus",
        "byPriority",
        "completionRate",
        "overdue"
      ],
      "additionalProperties": false
    },
    "Task": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "description": "GTD status (backend-native string; classified by `normaliseTaskStatus`/`isActionable`)."
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ],
          "description": "The project this task advances, or null for a standalone next-action."
        },
        "context": {
          "type": [
            "string",
            "null"
          ],
          "description": "GTD context (@calls,"
        },
        "waitingOn": {
          "type": [
            "string",
            "null"
          ],
          "description": "For a `waiting` task: who/what it's waiting on."
        },
        "assignee": {
          "type": [
            "string",
            "null"
          ],
          "description": "Who owns the next action (a person)."
        },
        "description": {
          "type": [
            "string",
            "null"
          ],
          "description": "Free-text notes / description."
        },
        "priority": {
          "type": [
            "string",
            "null"
          ],
          "description": "Importance — reuses the canonical priority (none/low/medium/high/urgent)."
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Metadata tags/labels for filtering + grouping."
        },
        "startDate": {
          "type": [
            "string",
            "null"
          ],
          "description": "When the action becomes available (GTD defer / start date, ISO 8601)."
        },
        "dueDate": {
          "type": [
            "string",
            "null"
          ],
          "description": "Due date (ISO 8601)."
        },
        "recurrence": {
          "type": [
            "string",
            "null"
          ],
          "description": "Recurrence rule (e.g. \"every weekday\", an RRULE) — null for a one-off."
        },
        "estimateHours": {
          "type": [
            "number",
            "null"
          ],
          "description": "Estimated effort in hours."
        },
        "parentTaskId": {
          "type": [
            "string",
            "null"
          ],
          "description": "Parent task, for subtasks/checklists."
        },
        "url": {
          "type": [
            "string",
            "null"
          ],
          "description": "External link (a doc, ticket, PR)."
        },
        "completedAt": {
          "type": [
            "string",
            "null"
          ],
          "description": "When it was completed (ISO 8601), if done."
        },
        "reminderAt": {
          "type": [
            "string",
            "null"
          ],
          "description": "A notify-me time, distinct from the due date (ISO 8601)."
        },
        "energy": {
          "type": [
            "string",
            "null"
          ],
          "description": "GTD energy/effort level (low/medium/high) — orthogonal to the hour estimate."
        },
        "section": {
          "type": [
            "string",
            "null"
          ],
          "description": "Section/list this task groups under within its project (Asana section, Todoist section, ClickUp list)."
        },
        "sortOrder": {
          "type": [
            "number",
            "null"
          ],
          "description": "Manual sort position within a list/section (Todoist order, Google Tasks position)."
        },
        "collaborators": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Followers/collaborators kept in the loop (people), beyond the single assignee."
        }
      },
      "required": [
        "id",
        "title",
        "status"
      ],
      "additionalProperties": true,
      "description": "A TASK — an ACTIONABLE next-action (GTD), distinct from an Issue (a problem/blocker from a helpdesk or project). A task may belong to a project, or stand alone (a personal/portfolio next-action). Its `status` is a GTD state (see broker/vocabulary `CANONICAL_TASK_STATUS`)."
    },
    "TaskAttachment": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "taskId": {
          "type": "string"
        },
        "filename": {
          "type": "string"
        },
        "url": {
          "type": [
            "string",
            "null"
          ],
          "description": "Where the file actually lives (a backend/download URL)."
        },
        "contentType": {
          "type": [
            "string",
            "null"
          ]
        },
        "size": {
          "type": [
            "number",
            "null"
          ],
          "description": "Size in bytes, if the backend reports it."
        },
        "addedBy": {
          "type": [
            "string",
            "null"
          ]
        },
        "addedAt": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "taskId",
        "filename",
        "addedAt"
      ],
      "additionalProperties": true,
      "description": "A file ATTACHED to a task — a REFERENCE to a file that lives in the backend / an external store, not the bytes (OmniProject is zero-at-rest). Only backends that support attachments expose these."
    },
    "TaskAttachmentWrite": {
      "type": "object",
      "properties": {
        "filename": {
          "type": "string"
        },
        "url": {
          "type": [
            "string",
            "null"
          ]
        },
        "contentType": {
          "type": [
            "string",
            "null"
          ]
        },
        "size": {
          "type": [
            "number",
            "null"
          ]
        }
      },
      "required": [
        "filename"
      ],
      "additionalProperties": false
    },
    "TaskComment": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "taskId": {
          "type": "string"
        },
        "body": {
          "type": "string"
        },
        "author": {
          "type": [
            "string",
            "null"
          ]
        },
        "createdAt": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "taskId",
        "body",
        "createdAt"
      ],
      "additionalProperties": true,
      "description": "A comment on a task (a discussion note)."
    },
    "TaskCommentWrite": {
      "type": "object",
      "properties": {
        "body": {
          "type": "string"
        }
      },
      "required": [
        "body"
      ],
      "additionalProperties": false
    },
    "TaskItem": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "taskId": {
          "type": "string"
        },
        "kind": {
          "enum": [
            "issue",
            "note"
          ]
        },
        "content": {
          "type": "string"
        },
        "author": {
          "type": [
            "string",
            "null"
          ]
        },
        "createdAt": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "taskId",
        "kind",
        "content",
        "createdAt"
      ],
      "additionalProperties": true,
      "description": "A child issue/note raised against a task (the work-item)."
    },
    "TaskItemWrite": {
      "type": "object",
      "properties": {
        "kind": {
          "enum": [
            "issue",
            "note"
          ]
        },
        "content": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "content"
      ],
      "additionalProperties": false,
      "description": "Create a child issue/note on a task."
    },
    "TaskWrite": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ]
        },
        "context": {
          "type": [
            "string",
            "null"
          ]
        },
        "waitingOn": {
          "type": [
            "string",
            "null"
          ]
        },
        "assignee": {
          "type": [
            "string",
            "null"
          ]
        },
        "description": {
          "type": [
            "string",
            "null"
          ]
        },
        "priority": {
          "type": [
            "string",
            "null"
          ]
        },
        "tags": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "startDate": {
          "type": [
            "string",
            "null"
          ]
        },
        "dueDate": {
          "type": [
            "string",
            "null"
          ]
        },
        "recurrence": {
          "type": [
            "string",
            "null"
          ]
        },
        "estimateHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "parentTaskId": {
          "type": [
            "string",
            "null"
          ]
        },
        "url": {
          "type": [
            "string",
            "null"
          ]
        },
        "completedAt": {
          "type": [
            "string",
            "null"
          ]
        },
        "reminderAt": {
          "type": [
            "string",
            "null"
          ]
        },
        "energy": {
          "type": [
            "string",
            "null"
          ]
        },
        "section": {
          "type": [
            "string",
            "null"
          ]
        },
        "sortOrder": {
          "type": [
            "number",
            "null"
          ]
        },
        "collaborators": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "description": "A normalised task create/update. `title` is required on create."
    },
    "VerifyReport": {
      "type": "object",
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "actions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "ok": {
                "type": "boolean"
              },
              "status": {
                "type": "number"
              },
              "ms": {
                "type": "number"
              },
              "note": {
                "type": [
                  "string",
                  "null"
                ]
              }
            },
            "required": [
              "name",
              "ok",
              "status",
              "ms"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "ok",
        "actions"
      ],
      "additionalProperties": false,
      "description": "Dry-run verification of the broker contract — must never mutate a backend."
    },
    "WbsElement": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "projectId": {
          "type": "string"
        },
        "parentId": {
          "type": [
            "string",
            "null"
          ]
        },
        "name": {
          "type": "string"
        },
        "level": {
          "type": "number"
        },
        "status": {
          "type": "string",
          "description": "SAP system/user status label (display-only)."
        },
        "responsible": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "projectId",
        "parentId",
        "name",
        "level"
      ],
      "additionalProperties": false,
      "description": "SAP read model — a WBS element in a project's cost structure (docs/SAP-CONNECTOR.md §4.6). SAP owns these; we render them by reference (the id is the cost-collecting key), never copying at rest."
    },
    "WbsFinancials": {
      "type": "object",
      "properties": {
        "wbsId": {
          "type": "string"
        },
        "currency": {
          "type": "string"
        },
        "budget": {
          "type": "number"
        },
        "actual": {
          "type": "number"
        },
        "commitment": {
          "type": "number"
        },
        "wip": {
          "type": "number"
        },
        "planned": {
          "type": "number"
        },
        "available": {
          "type": "number"
        }
      },
      "required": [
        "wbsId",
        "currency",
        "budget",
        "actual",
        "commitment",
        "wip",
        "planned",
        "available"
      ],
      "additionalProperties": false,
      "description": "SAP read model — the financial roll-up for one WBS element, READ from SAP's ledger (ACDOCA). We never post or settle; all amounts are in `currency`. `available` = budget − (actual + commitment)."
    },
    "Whiteboard": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ],
          "description": "Optional owning project (a board raised against a project); null for an org-level board."
        },
        "ownerSub": {
          "type": [
            "string",
            "null"
          ],
          "description": "The board's creator (a user `sub`) — the owner for a personal board. Set server-side, never trusted from the client."
        },
        "visibility": {
          "$ref": "#/$defs/WhiteboardVisibility",
          "description": "Org-wide vs personal. A `user` board is visible/editable only to its `ownerSub`. Defaults to `org`. (Used by the sidecar store; the encrypted-JSON stores encode location in `storage`/the id instead.)"
        },
        "storage": {
          "enum": [
            "user",
            "project",
            "org",
            "sidecar"
          ],
          "description": "Where the board lives: user / project / org (encrypted-JSON areas) or sidecar (the built-in SoR). The id also encodes this; the field is a convenience for the client."
        },
        "scene": {
          "$ref": "#/$defs/WhiteboardScene"
        },
        "updatedAt": {
          "type": "string"
        },
        "updatedBy": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "name",
        "scene",
        "updatedAt"
      ],
      "additionalProperties": true
    },
    "WhiteboardMeta": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ]
        },
        "ownerSub": {
          "type": [
            "string",
            "null"
          ]
        },
        "visibility": {
          "$ref": "#/$defs/WhiteboardVisibility"
        },
        "storage": {
          "enum": [
            "user",
            "project",
            "org",
            "sidecar"
          ]
        },
        "updatedAt": {
          "type": "string"
        },
        "updatedBy": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "name",
        "updatedAt"
      ],
      "additionalProperties": false,
      "description": "A board's metadata (no scene body) — the list view."
    },
    "WhiteboardScene": {
      "type": "object",
      "properties": {
        "elements": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CanvasElement"
          },
          "description": "The canvas elements — typed `canvas`-family primitives (sticky/shape/text/connector/frame), validated per-type at the gateway. Built of shared primitives, not an opaque third-party scene blob."
        },
        "appState": {
          "type": "object",
          "additionalProperties": {},
          "description": "A minimal, sanitised view state (e.g. background colour) — never a full editor appState."
        }
      },
      "required": [
        "elements"
      ],
      "additionalProperties": false,
      "description": "A WHITEBOARD — a freeform visual canvas (roadmap 2.3). The drawing is an opaque scene of vector elements; like a wiki page it is authored in OmniProject but STORED through the broker (zero-at-rest), so it inherits the data seam's residency + audit. `scene` is a bounded, sanitised JSON payload (no embedded image data, links restricted to safe schemes) — never executed, just persisted + rendered."
    },
    "WhiteboardVisibility": {
      "enum": [
        "org",
        "user"
      ],
      "description": "Where a board lives: `org` = shared org-wide (any viewer+); `user` = personal to its owner only."
    },
    "WhiteboardWrite": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ]
        },
        "visibility": {
          "$ref": "#/$defs/WhiteboardVisibility",
          "description": "Requested visibility (org-wide vs personal). The OWNER is set server-side from the caller, never here."
        },
        "scene": {
          "$ref": "#/$defs/WhiteboardScene"
        }
      },
      "required": [
        "name",
        "scene"
      ],
      "additionalProperties": false
    },
    "WikiDoc": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "spaceId": {
          "type": "string"
        },
        "parentId": {
          "type": [
            "string",
            "null"
          ]
        },
        "slug": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "blocks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DocBlock"
          }
        },
        "updatedAt": {
          "type": "string"
        },
        "updatedBy": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "spaceId",
        "slug",
        "title",
        "blocks",
        "updatedAt"
      ],
      "additionalProperties": true,
      "description": "A WIKI DOCUMENT — a page in a space, built of primitive `DocBlock`s (see backend-catalogue). Nesting is by `parentId` (a page tree); `slug` is the URL segment within the space. Content is authored in OmniProject but STORED through the broker, so it inherits the data seam's residency and audit controls."
    },
    "WikiDocVersion": {
      "type": "object",
      "properties": {
        "versionId": {
          "type": "string"
        },
        "docId": {
          "type": "string"
        },
        "at": {
          "type": "string"
        },
        "author": {
          "type": [
            "string",
            "null"
          ]
        },
        "title": {
          "type": "string"
        },
        "blocks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DocBlock"
          }
        }
      },
      "required": [
        "versionId",
        "docId",
        "at",
        "title",
        "blocks"
      ],
      "additionalProperties": true,
      "description": "A saved REVISION of a wiki document — a point-in-time snapshot captured by the system of record on each write, so a page's history is auditable and any prior state can be restored (by re-saving its content through the normal update path). `versionId` is unique within the document's history."
    },
    "WikiDocVersionMeta": {
      "type": "object",
      "properties": {
        "versionId": {
          "type": "string"
        },
        "docId": {
          "type": "string"
        },
        "at": {
          "type": "string"
        },
        "author": {
          "type": [
            "string",
            "null"
          ]
        },
        "title": {
          "type": "string"
        }
      },
      "required": [
        "versionId",
        "docId",
        "at",
        "title"
      ],
      "additionalProperties": false,
      "description": "A revision's metadata (no block body) — the history list view."
    },
    "WikiDocWrite": {
      "type": "object",
      "properties": {
        "spaceId": {
          "type": "string"
        },
        "parentId": {
          "type": [
            "string",
            "null"
          ]
        },
        "slug": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "blocks": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DocBlock"
          }
        }
      },
      "required": [
        "spaceId",
        "title",
        "blocks"
      ],
      "additionalProperties": false
    },
    "WikiSpace": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "key": {
          "type": "string",
          "description": "Short stable key (URL segment)."
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "key",
        "name"
      ],
      "additionalProperties": true,
      "description": "A WIKI SPACE — a named container for documents (a knowledge base / team space). Like everything else the body lives in the backend system of record; OmniProject is zero-at-rest. Only backends that model a wiki/knowledge base expose these."
    }
  }
} as const;
