/* GENERATED by scripts/src/gen-contract.ts — do not edit. */
/* The published broker contract, embedded so GET /api/contract has no runtime
   dependency on the docs/ tree. Regenerated in lock-step with the JSON + MD. */
export const BROKER_CONTRACT_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://omniproject.dev/contract/broker.v1.schema.json",
  "title": "OmniProject Broker Contract",
  "description": "The published, versioned interface between OmniProject and any broker. Generated from artifacts/api-server/src/broker/{types,contract}.ts — do not edit by hand.",
  "x-contract-version": "v1",
  "$defs": {
    "ActorContext": {
      "type": "object",
      "properties": {
        "sub": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "role": {
          "type": "string"
        },
        "token": {
          "type": "string"
        },
        "authHeader": {
          "type": "string"
        },
        "sessionBind": {
          "$ref": "#/$defs/SessionBind",
          "description": "Binding material for the per-session broker signing key (lib/session-key). Present for authenticated calls; absent for system/unauthenticated ones (which fall back to the static broker key)."
        },
        "actorKind": {
          "$ref": "#/$defs/ActorKind",
          "description": "What kind of principal this is (default human). Autonomous actors carry their own keyed sessionBind + RBAC role, so they're keyed and provenance-bound too."
        },
        "scope": {
          "$ref": "#/$defs/Scope",
          "description": "The principal's forwarded DATA scope (user / programme / all) — the backend confirms it (it rides in the PSK-signed envelope) and enforces per-user/per-programme access."
        },
        "issuedAt": {
          "type": "number",
          "description": "For a minted autonomous principal: the invocation time it was minted for (epoch ms), so a consumer can prove it's fresh and not a replayed/cached context."
        },
        "expiresAt": {
          "type": "number",
          "description": "For a minted autonomous principal: its (short) expiry — autonomous sessions are deliberately brief since re-keying is free."
        }
      },
      "additionalProperties": false,
      "description": "Forwarded actor identity. A write is performed \"as\" this principal so the backend system of record authorises it under the real user (not a shared admin key). `authHeader` is the transport credential to forward; `token` is the same access token echoed in the per-user context. Demo brokers ignore both."
    },
    "ActorKind": {
      "enum": [
        "human",
        "automation",
        "agent"
      ],
      "description": "Who initiated an action. Autonomous actors (scheduled jobs, AI agents) are first-class principals — keyed, RBAC-roled and provenance-bound like a human."
    },
    "BackendFieldMap": {
      "type": "object",
      "properties": {
        "fields": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/FieldSupport"
          }
        },
        "entities": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/FieldSupport"
          }
        }
      },
      "required": [
        "fields",
        "entities"
      ],
      "additionalProperties": false,
      "description": "Per-field / per-entity support a backend declares. Finer-grained than the domain flags: e.g. a backend may surface `dueDate` read-only (surface without store), or have no `programmeId` field at all (programme entity unsupported)."
    },
    "Baseline": {
      "type": "object",
      "properties": {
        "projectId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "capturedAt": {
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "issueId": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "plannedStart": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "plannedFinish": {
                "type": [
                  "string",
                  "null"
                ]
              }
            },
            "required": [
              "issueId",
              "title",
              "plannedStart",
              "plannedFinish"
            ],
            "additionalProperties": false
          }
        },
        "provenance": {
          "enum": [
            "sourced",
            "derived",
            "sample"
          ]
        }
      },
      "required": [
        "projectId",
        "capturedAt",
        "items",
        "provenance"
      ],
      "additionalProperties": false
    },
    "BrokerEnvelope": {
      "type": "object",
      "properties": {
        "success": {
          "type": "boolean"
        },
        "data": {},
        "message": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "success"
      ],
      "additionalProperties": false,
      "description": "The wire envelope an HTTP-transport broker returns. The gateway unwraps it before anything above the seam sees data; a bare body (no `success` key) is treated as `{ success: true, data: <body> }`. In-process brokers (DemoBroker) return domain values directly and never construct an envelope — the envelope is the reference HTTP binding, not a domain concept."
    },
    "BrokerErrorCode": {
      "enum": [
        "conflict",
        "not_found",
        "unauthorized",
        "bad_request",
        "unavailable"
      ],
      "description": "Normalised error taxonomy — no broker-specific status quirks leak upward."
    },
    "CapabilityFlags": {
      "type": "object",
      "additionalProperties": {
        "type": "boolean"
      },
      "description": "Raw capability flags a backend can populate (domain → available)."
    },
    "ContractVersion": {
      "const": "v1"
    },
    "EnumeratedField": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "surface": {
          "type": "boolean"
        },
        "store": {
          "type": "boolean"
        },
        "references": {
          "type": "string",
          "description": "If the backend's API schema says this field references another entity."
        },
        "sourceSystem": {
          "type": "string",
          "description": "The system of record this field is read from (e.g. \"jira\", \"openproject\"). Lets the UI show granular lineage: \"this canonical field ← that backend.\""
        },
        "sourceField": {
          "type": "string",
          "description": "The backend's NATIVE field name/id this canonical field maps from (e.g. \"duedate\", \"customfield_10016\") — supplied by the broker/workflow, so the overlay can say exactly which backend field a value came from."
        }
      },
      "required": [
        "key"
      ],
      "additionalProperties": false,
      "description": "A field a backend reports it can expose, from API enumeration during wiring."
    },
    "FieldSupport": {
      "type": "object",
      "properties": {
        "surface": {
          "type": "boolean"
        },
        "store": {
          "type": "boolean"
        }
      },
      "required": [
        "surface",
        "store"
      ],
      "additionalProperties": false,
      "description": "Whether a field/entity can be surfaced (read) and stored (written)."
    },
    "FxRates": {
      "type": "object",
      "properties": {
        "base": {
          "type": "string"
        },
        "rates": {
          "type": "object",
          "additionalProperties": {
            "type": "number"
          }
        },
        "provenance": {
          "enum": [
            "sourced",
            "sample"
          ]
        },
        "asOf": {
          "type": "string"
        }
      },
      "required": [
        "base",
        "rates",
        "provenance",
        "asOf"
      ],
      "additionalProperties": false
    },
    "HistoryPoint": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string"
        },
        "completionRate": {
          "type": "number"
        },
        "totalIssues": {
          "type": "number"
        },
        "completedIssues": {
          "type": "number"
        },
        "openBlockers": {
          "type": [
            "number",
            "null"
          ]
        },
        "provenance": {
          "enum": [
            "sourced",
            "derived",
            "sample"
          ]
        }
      },
      "required": [
        "date",
        "completionRate",
        "totalIssues",
        "completedIssues",
        "openBlockers",
        "provenance"
      ],
      "additionalProperties": false
    },
    "HistoryState": {
      "type": "object",
      "properties": {
        "at": {
          "type": "string"
        },
        "completionPct": {
          "type": "number"
        },
        "openBlockers": {
          "type": [
            "number",
            "null"
          ]
        },
        "provenance": {
          "enum": [
            "replayed",
            "projected",
            "sourced",
            "derived",
            "sample"
          ]
        }
      },
      "required": [
        "at",
        "completionPct",
        "openBlockers",
        "provenance"
      ],
      "additionalProperties": false,
      "description": "A portfolio-level state at a point in time, served by the time-travel replay (read back from the operator's logging server). `replayed` = a real recorded state; `projected` = a model of the future (never fact); `sample` = demo."
    },
    "IngestedNotification": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "body": {
          "type": [
            "string",
            "null"
          ]
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ]
        },
        "issueId": {
          "type": [
            "string",
            "null"
          ]
        },
        "read": {
          "type": "boolean"
        },
        "timestamp": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "kind",
        "title",
        "body",
        "projectId",
        "issueId",
        "read",
        "timestamp"
      ],
      "additionalProperties": false,
      "description": "The normalised notification the gateway fans out after ingest."
    },
    "Issue": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "projectId": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "version": {
          "type": "number"
        },
        "budget": {
          "type": [
            "number",
            "null"
          ]
        },
        "actualCost": {
          "type": [
            "number",
            "null"
          ]
        },
        "billable": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "costCenter": {
          "type": [
            "string",
            "null"
          ]
        },
        "currency": {
          "type": [
            "string",
            "null"
          ]
        },
        "estimateHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "loggedHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "remainingHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "storyPoints": {
          "type": [
            "number",
            "null"
          ]
        },
        "healthStatus": {
          "type": [
            "string",
            "null"
          ]
        },
        "riskLevel": {
          "type": [
            "string",
            "null"
          ]
        },
        "impact": {
          "type": [
            "string",
            "null"
          ]
        },
        "urgency": {
          "type": [
            "string",
            "null"
          ]
        },
        "blocked": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "blockedReason": {
          "type": [
            "string",
            "null"
          ]
        },
        "mitigation": {
          "type": [
            "string",
            "null"
          ]
        },
        "defectCount": {
          "type": [
            "number",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "projectId",
        "title",
        "status"
      ],
      "additionalProperties": true,
      "description": "A normalised issue/work-item row. `version` is the concurrency token."
    },
    "IssueWrite": {
      "type": "object",
      "properties": {
        "projectId": {
          "type": "string"
        },
        "issueId": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "description": {
          "type": [
            "string",
            "null"
          ]
        },
        "status": {
          "type": "string"
        },
        "priority": {
          "type": "string"
        },
        "assignee": {
          "type": [
            "string",
            "null"
          ]
        },
        "labels": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "startDate": {
          "type": [
            "string",
            "null"
          ]
        },
        "dueDate": {
          "type": [
            "string",
            "null"
          ]
        },
        "budget": {
          "type": [
            "number",
            "null"
          ]
        },
        "actualCost": {
          "type": [
            "number",
            "null"
          ]
        },
        "billable": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "costCenter": {
          "type": [
            "string",
            "null"
          ]
        },
        "currency": {
          "type": [
            "string",
            "null"
          ]
        },
        "estimateHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "loggedHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "remainingHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "storyPoints": {
          "type": [
            "number",
            "null"
          ]
        },
        "healthStatus": {
          "type": [
            "string",
            "null"
          ]
        },
        "riskLevel": {
          "type": [
            "string",
            "null"
          ]
        },
        "impact": {
          "type": [
            "string",
            "null"
          ]
        },
        "urgency": {
          "type": [
            "string",
            "null"
          ]
        },
        "blocked": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "blockedReason": {
          "type": [
            "string",
            "null"
          ]
        },
        "mitigation": {
          "type": [
            "string",
            "null"
          ]
        },
        "defectCount": {
          "type": [
            "number",
            "null"
          ]
        },
        "expectedVersion": {
          "type": "number"
        }
      },
      "required": [
        "projectId"
      ],
      "additionalProperties": false,
      "description": "A normalised issue mutation. `expectedVersion` drives optimistic concurrency."
    },
    "NotificationIngest": {
      "type": "object",
      "properties": {
        "target": {
          "type": "object",
          "properties": {
            "sub": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "role": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "notification": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "kind": {
              "type": "string"
            },
            "title": {
              "type": "string"
            },
            "body": {
              "type": [
                "string",
                "null"
              ]
            },
            "projectId": {
              "type": [
                "string",
                "null"
              ]
            },
            "issueId": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "title"
          ],
          "additionalProperties": false
        }
      },
      "required": [
        "notification"
      ],
      "additionalProperties": false,
      "description": "Body of POST /api/notifications/ingest — a broker/tool pushes an event in. Authenticated by the NOTIFY_INGEST_SECRET shared secret (Bearer or X-Notify-Secret header). `notification.title` is the only required field."
    },
    "OutboundEvent": {
      "type": "object",
      "properties": {
        "event": {
          "$ref": "#/$defs/OutboundEventName"
        },
        "deliveredAt": {
          "type": "string"
        },
        "deliveryId": {
          "type": "string"
        },
        "data": {}
      },
      "required": [
        "event",
        "deliveredAt",
        "deliveryId",
        "data"
      ],
      "additionalProperties": false,
      "description": "The JSON body of every outbound delivery."
    },
    "OutboundEventName": {
      "enum": [
        "notification",
        "audit",
        "config.changed",
        "webhook.test"
      ]
    },
    "PortfolioRow": {
      "type": "object",
      "properties": {
        "projectId": {
          "type": "string"
        },
        "projectName": {
          "type": "string"
        },
        "ragStatus": {
          "type": "string"
        },
        "scheduleVarianceDays": {
          "type": "number"
        },
        "budgetVariancePercentage": {
          "type": "number"
        },
        "activeBlockersCount": {
          "type": "number"
        }
      },
      "required": [
        "projectId",
        "projectName",
        "ragStatus",
        "scheduleVarianceDays",
        "budgetVariancePercentage",
        "activeBlockersCount"
      ],
      "additionalProperties": false
    },
    "Project": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "status": {
          "type": [
            "string",
            "null"
          ],
          "description": "The backend's native project lifecycle status (kept verbatim, like `Issue.status`). Classified into live/closed by `isProjectLive` (broker/vocabulary); reads are default-live. Absent ⇒ live."
        },
        "omniInstanceId": {
          "type": "string",
          "description": "OmniProject instance ID — a GUID minted by the gateway when the project is created, echoed and stored by every backend. It is the backend-INDEPENDENT correlation key: the same project seen through two backends carries the same `omniInstanceId`, so records assemble across backends by it (whereas `source:id` is unique per backend). Optional because pre-existing rows may lack one."
        }
      },
      "required": [
        "id",
        "name"
      ],
      "additionalProperties": true,
      "description": "A normalised project row."
    },
    "ProjectMember": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "email": {
          "type": [
            "string",
            "null"
          ]
        },
        "access": {
          "enum": [
            "read",
            "write"
          ],
          "description": "\"write\" = can be assigned/act on work; \"read\" = view-only."
        },
        "skills": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Skills/competencies, when the backend tracks them (resource planning)."
        },
        "availableHours": {
          "type": [
            "number",
            "null"
          ],
          "description": "Available capacity in hours for the planning window, when tracked."
        },
        "allocatedHours": {
          "type": [
            "number",
            "null"
          ],
          "description": "Already-allocated hours in the planning window, when tracked."
        }
      },
      "required": [
        "id",
        "access"
      ],
      "additionalProperties": true,
      "description": "A person on a project, with their access level (the backend is the source)."
    },
    "ProjectWrite": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "identifier": {
          "type": [
            "string",
            "null"
          ]
        },
        "description": {
          "type": [
            "string",
            "null"
          ]
        },
        "programmeId": {
          "type": [
            "string",
            "null"
          ],
          "description": "Set/clear to group the project under a programme (derived-programme model)."
        },
        "omniInstanceId": {
          "type": "string",
          "description": "The gateway-minted correlation GUID, passed to the backend to store on create (never sent by a client). See `Project.omniInstanceId`."
        },
        "status": {
          "type": [
            "string",
            "null"
          ],
          "description": "The project's lifecycle status (backend-native string). Set/clear to move a project between live and closed. See `Project.status`."
        }
      },
      "additionalProperties": false,
      "description": "A normalised project create/update. `name` is required on create."
    },
    "Provenance": {
      "enum": [
        "sourced",
        "derived",
        "sample",
        "replayed",
        "projected"
      ]
    },
    "ResourceMember": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "email": {
          "type": [
            "string",
            "null"
          ]
        },
        "skills": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Union of skills seen across the member's projects."
        },
        "availableHours": {
          "type": [
            "number",
            "null"
          ],
          "description": "Summed capacity across projects (null when no backend supplies it)."
        },
        "allocatedHours": {
          "type": [
            "number",
            "null"
          ]
        },
        "projectIds": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Projects this person is a member of."
        }
      },
      "required": [
        "id",
        "skills",
        "availableHours",
        "allocatedHours",
        "projectIds"
      ],
      "additionalProperties": false,
      "description": "A person aggregated across the portfolio, for resource planning."
    },
    "Row": {
      "type": "object",
      "additionalProperties": {},
      "description": "Loosely-typed record — the normalised row shape the broker exchanges."
    },
    "SchemaManifest": {
      "type": "object",
      "properties": {
        "tables": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Canonical entity keys (tables) present, e.g. [\"project\", \"issue\", \"programme\"]."
        },
        "fields": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Canonical field keys present in the schema (a subset of the superset)."
        },
        "relationships": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "from": {
                "type": "string"
              },
              "field": {
                "type": "string"
              },
              "to": {
                "type": "string"
              }
            },
            "required": [
              "from",
              "field",
              "to"
            ],
            "additionalProperties": false
          },
          "description": "Foreign-key/relationship edges between entities."
        },
        "populated": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Canonical field keys that actually hold data — a subset of `fields`. When given, the gateway surfaces only these (\"populated, not just possible\"); when omitted, all `fields` are surfaced."
        }
      },
      "required": [
        "tables",
        "fields",
        "relationships"
      ],
      "additionalProperties": false,
      "description": "A backend's self-describing SCHEMA manifest — the tables, canonical fields and relationships it actually holds, plus which fields are POPULATED (have data). Returned by the optional `describeSchema`. Only a backend that owns its schema can answer this — in practice OmniProject's own stateful self-host database. Ordinary SaaS backends (the stateless-overlay default) do NOT implement it; the gateway then falls back to the static capability flags. The gateway uses it to surface only what a backend genuinely has (superset ∩ manifest)."
    },
    "Scope": {
      "type": "object",
      "properties": {
        "level": {
          "$ref": "#/$defs/ScopeLevel"
        },
        "sub": {
          "type": "string",
          "description": "The owning principal (used for user-level ownership/membership checks)."
        },
        "programmes": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The programmes this principal may act within (used for programme-level checks)."
        }
      },
      "required": [
        "level"
      ],
      "additionalProperties": false
    },
    "ScopeLevel": {
      "enum": [
        "user",
        "programme",
        "all"
      ],
      "description": "DATA scope — the per-principal authorization boundary the backend enforces on top of the coarse RBAC tier. The gateway resolves it from the user's grants + claim/SCIM groups and forwards it (verified, inside the PSK-signed broker envelope) as part of `userContext`, so the system of record can confirm-and-enforce it: - `all` — pmo / admin: every project and programme. - `programme` — a programme manager: only projects in their owned programmes. In a \"basic\" (no-IdP) deployment `programmes` is empty and the backend maps `sub → owned programmes` from its own records instead. - `user` — a standard user: only resources they own or are a member of. This module is PURE (no request/IO) so it is the shared contract: the gateway resolves + forwards it, an in-repo backend (or an external n8n one) enforces it with the same helpers."
    },
    "SessionBind": {
      "type": "object",
      "properties": {
        "sub": {
          "type": "string",
          "description": "The acting subject (username) the key is bound to."
        },
        "smono": {
          "type": "string",
          "description": "Monotonic-clock reading (ns string) at session creation."
        },
        "salt": {
          "type": "string",
          "description": "Per-session CSPRNG entropy (hex)."
        },
        "bkver": {
          "type": "number",
          "description": "Broker-key version the session key was derived under (for revocation/rotation)."
        }
      },
      "required": [
        "sub",
        "smono",
        "salt"
      ],
      "additionalProperties": false,
      "description": "The non-secret material needed to re-derive a session's broker key."
    },
    "Summary": {
      "type": "object",
      "properties": {
        "projectId": {
          "type": "string"
        },
        "total": {
          "type": "number"
        },
        "byStatus": {
          "type": "object",
          "additionalProperties": {
            "type": "number"
          }
        },
        "byPriority": {
          "type": "object",
          "additionalProperties": {
            "type": "number"
          }
        },
        "completionRate": {
          "type": "number"
        },
        "overdue": {
          "type": "number"
        }
      },
      "required": [
        "projectId",
        "total",
        "byStatus",
        "byPriority",
        "completionRate",
        "overdue"
      ],
      "additionalProperties": false
    },
    "Task": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "description": "GTD status (backend-native string; classified by `normaliseTaskStatus`/`isActionable`)."
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ],
          "description": "The project this task advances, or null for a standalone next-action."
        },
        "context": {
          "type": [
            "string",
            "null"
          ],
          "description": "GTD context (@calls,"
        },
        "waitingOn": {
          "type": [
            "string",
            "null"
          ],
          "description": "For a `waiting` task: who/what it's waiting on."
        },
        "dueDate": {
          "type": [
            "string",
            "null"
          ],
          "description": "Optional due/defer date (ISO 8601)."
        },
        "assignee": {
          "type": [
            "string",
            "null"
          ],
          "description": "Who owns the next action."
        }
      },
      "required": [
        "id",
        "title",
        "status"
      ],
      "additionalProperties": true,
      "description": "A TASK — an ACTIONABLE next-action (GTD), distinct from an Issue (a problem/blocker from a helpdesk or project). A task may belong to a project, or stand alone (a personal/portfolio next-action). Its `status` is a GTD state (see broker/vocabulary `CANONICAL_TASK_STATUS`)."
    },
    "TaskItem": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "taskId": {
          "type": "string"
        },
        "kind": {
          "enum": [
            "issue",
            "note"
          ]
        },
        "content": {
          "type": "string"
        },
        "author": {
          "type": [
            "string",
            "null"
          ]
        },
        "createdAt": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "taskId",
        "kind",
        "content",
        "createdAt"
      ],
      "additionalProperties": true,
      "description": "A child issue/note raised against a task (the work-item)."
    },
    "TaskItemWrite": {
      "type": "object",
      "properties": {
        "kind": {
          "enum": [
            "issue",
            "note"
          ]
        },
        "content": {
          "type": "string"
        }
      },
      "required": [
        "kind",
        "content"
      ],
      "additionalProperties": false,
      "description": "Create a child issue/note on a task."
    },
    "TaskWrite": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "projectId": {
          "type": [
            "string",
            "null"
          ]
        },
        "context": {
          "type": [
            "string",
            "null"
          ]
        },
        "waitingOn": {
          "type": [
            "string",
            "null"
          ]
        },
        "dueDate": {
          "type": [
            "string",
            "null"
          ]
        },
        "assignee": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "additionalProperties": false,
      "description": "A normalised task create/update. `title` is required on create."
    },
    "VerifyReport": {
      "type": "object",
      "properties": {
        "ok": {
          "type": "boolean"
        },
        "actions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "ok": {
                "type": "boolean"
              },
              "status": {
                "type": "number"
              },
              "ms": {
                "type": "number"
              },
              "note": {
                "type": [
                  "string",
                  "null"
                ]
              }
            },
            "required": [
              "name",
              "ok",
              "status",
              "ms"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "ok",
        "actions"
      ],
      "additionalProperties": false,
      "description": "Dry-run verification of the broker contract — must never mutate a backend."
    }
  }
} as const;
